### ISSUE TITLE
changeCamel to change_camel in python

### ISSUE THREAD

**Issue by hainm** [arose/nglview#10]
this is for my TODO.

```python
aspectRatio
```

to
 ```python
aspect_ratio
```

```python
tv._add_representation('all', type='cartoon', aspect_ratio=...)
```

**Comment by hainm** [comment]
@arose 
 
what do you think about this issue?

I can work on this if you feel ok.

```python
tv.parameters = {'theme': 'dark', 'zoomSpeed': 5}
```

should be 
```python
tv.parameters = {'theme': 'dark', 'zoom_speed': 5}
```

**Comment by arose** [comment]
Your rationale is to follow the Python way of naming for the keywords, right?

I do not want to change it for ngl, but i am okay with allowing `zoom_speed` from Python. Probably good to allow `zoomSpeed` too.

**Comment by hainm** [comment]
> Your rationale is to follow the Python way of naming for the keywords, right?

Yes

> I do not want to change it for ngl, but i am okay with allowing zoom_speed from Python

I only want to change in nglview notebook.

> Probably good to allow zoomSpeed too.
yeah. I think so. If the syntax is consistent, it's easy to replacye 'zoom_speed' --> 'zoomSpeed' and so on.

**Comment by hainm** [comment]
done
