### ISSUE TITLE
automatically create documentation from docstrings

### ISSUE THREAD

**Issue by arose** [arose/nglview#101]
and remove most stuff from the README.md

@hainm what do you think?

**Comment by hainm** [comment]
> automatically create documentation from docstrings

agree. I do the same thing for pytraj. So it's trivial. Need to create another branch `gh-pages` too.

> and remove most stuff from the README.md

absolutely. We should add only eye-catchy and stable API stuff.

**Comment by hainm** [comment]
> README.md

review please: https://github.com/arose/nglview/pull/107

**Comment by hainm** [comment]
Website is on the way

http://arose.github.io/nglview/latest/index2.html

**Comment by hainm** [comment]
@arose can you add this link to the top of nglview github page? I do not have permision to do it.

http://arose.github.io/nglview

**Comment by hainm** [comment]
done.

**Comment by hainm** [comment]
change to 'nature' theme for website.

http://arose.github.io/nglview/dev/api.html

![nglview_website](https://cloud.githubusercontent.com/assets/4451957/17425455/7c4fe494-5a9b-11e6-886c-16c217114068.png)
