### ISSUE TITLE
link viewer

### ISSUE THREAD

**Issue by hainm** [arose/nglview#11]
What's about link two widgets together (share rotation matrix?)

![tz2_closest_100](https://github.com/hainm/nglview/blob/master/notebook/closest_waters.png?raw=true)

**Comment by arose** [comment]
This needs first be added to ngl. Using stage.setOrientation/getOrientation and add an listener to the "change" event of stage.viewer.controls. Something like the following might work as a prototype (not tested):

```JavaScript
stage1.viewer.controls.addEventListener( "change", function(){ stage2.setOrientation( stage1.getOrientation() ) }, false );
```

**Comment by hainm** [comment]
yeah. I just (will) make a list of suggestions/features here and there (ngl repo). In the future, we can prioritize/decide things to implement.

**Comment by hainm** [comment]
@arose can we link in Python's side by syncing camera?

```python
from trailets import link
link((view1, 'camera_str'), (view2, 'camera_str'))
```

where `camera_str` is `Unicode().tag(sync=True)`, synced with JS side.
Getting `camera_str` by JSON.stringify.

**Comment by hainm** [comment]
closed by https://github.com/arose/nglview/pull/110
