### ISSUE TITLE
passing unitcells info

### ISSUE THREAD

**Issue by hainm** [arose/nglview#115]
wait for NGL-dev

**Comment by arose** [comment]
do you mean crystallographic unitcells? Those are read from pdb/mmcif files

**Comment by hainm** [comment]
I want to display box for trajectory too.

**Comment by arose** [comment]
I see, that is not really the unitcell and it can also change from frame to frame. New feature for NGL.

**Comment by hainm** [comment]
I am not sure about usage of passing box info. closed.
