### ISSUE TITLE
wishlist: save png

### ISSUE THREAD

**Issue by hainm** [arose/nglview#12]
yeah, we should bring this feature from ngl repo.

**Comment by hainm** [comment]
Example

```python
tv.savefig(filename, frame=None) # current frame
tv.savefig(filename, frame=3)
```

**Comment by arose** [comment]
Do you want to save it through the Python kernel or just as a browser download?

The browser download is straightforward, just call `stage.exportImage(...)` in the widget.

Via Python would require some changes to ngl to get the image data and the widget would then convert to a base64 string to send to the kernel; Or send it via the more efficient approach outlined in #3.

**Comment by arose** [comment]
see also https://github.com/arose/ngl/issues/33

**Comment by hainm** [comment]
I am more interested in saving png file jupyter notebook. Might be two ways to save?

- from viewer
```python
import nglview as nv
view = nv.TrajectoryViwer(...)
view.savefig(...)
```

- from right clicking from the screen in the viewer (in notebook).

**Comment by arose** [comment]
I am not sure I understand. Should the image be saved via a download from the browser or via the Jupyter kernel running Python?

**Comment by hainm** [comment]
>  via the Jupyter kernel running Python

**Comment by arose** [comment]
Ok, then the NGL issue needs to be addressed first.

**Comment by hainm** [comment]
What I have in mind is

```python
import pytraj as pt
import nglview as nv

traj = pt.load('t.nc', 't.parm7')
view = nv.show_pytraj(traj)

for idx_frame in range(traj.n_frames):
    view.frame = idx_frame
    view.save_snapshot('snapshot_{}'.format(idx_frame))

# or better
view.make_movie([...], engine='external_program_can_make_movie')

**Comment by arose** [comment]
This means a lot of data will travel from Browser to Kernel, which brings us back to #3.

**Comment by hainm** [comment]
so now user can download snapshot from Python side. I am thinking about method's name.
Prefer short one.

- [ ] export_image
- [ ] savefig
- [ ] download_snapshot
- [ ] screenshot
- [ ] ...

example
```python
def screenshot(self):
    self._remote_call('screenshot', target='stage', kwargs=params)
```

`screenshot` seems to be good name. :D

**Comment by cksajil** [comment]
I have created a semi-automated solution for this. Please see https://intuitivetutorial.com/2021/07/06/visualizing-3d-protein-structures-and-exporting-into-images-using-jupyter-notebook/
