### ISSUE TITLE
NGLView version: does is work properly?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#128]
```python
In [3]: nv.__version__
Out[3]: '0.4+144.g6f7ea35'
```

Should it be `0.5....` version? [0.4 is already released](https://github.com/arose/nglview/releases)

**Comment by arose** [comment]
it means it is 144 commits ahead of 0.4 and the short hash of the commit is g6f7ea35

**Comment by hainm** [comment]
in our website, I manually added `0.5dev`: http://arose.github.io/nglview/latest/

Should I update to `'0.4+144.g6f7ea35` (or whatever version shows up with `nv.__version__`?

**Comment by arose** [comment]
I think 0.5dev is ok for now but in the future we can avoid this by only having a manual for a released version.
