### ISSUE TITLE
broke with large factor for `export_image`

### ISSUE THREAD

**Issue by hainm** [arose/nglview#130]
![broke](https://cloud.githubusercontent.com/assets/4451957/15115365/a1bf05fc-15cc-11e6-890d-6103879b1d1d.png)

**Comment by arose** [comment]
that's odd

**Comment by hainm** [comment]
@arose `w` is ipywidgets.widget_image.Widget

**Comment by hainm** [comment]
it's fine if using `IPython.display.Image(view._image_data)`

**Comment by arose** [comment]
Oh, I see. I would say it is expected then. If the image is not wrap in a container that limits its size it will break the layout.

**Comment by hainm** [comment]
yeah.

**Comment by hainm** [comment]
alternatively we can manually change its width value.

`w.width = 1000` works fine with my TV screen.

**Comment by hainm** [comment]
uhm, but if we have NGLWidget, why does we need `widget_image.Image` from ipywidget?

The only reason I uses it because it (widget_image) can display higher quality image that `Ipython.display.Image`. Probably need to read more (specifying `retina=True` cause some errors related to string)

**Comment by arose** [comment]
is this still an issue for you?

**Comment by hainm** [comment]
Ah no. Just use factor<=4.
