### ISSUE TITLE
atom index selection + bitset 

### ISSUE THREAD

**Issue by hainm** [arose/nglview#14]
from this doc: http://arose.github.io/ngl/doc/#User_manual/Usage/Selection_language

there is no selection for atom indices?

saying I am having a series of atoms and want to make red color, how can I do the selection.

This is Amber syntax

```python
tv._add_representation('@1,2,4,10,11', 'ball+sticks', color='red')
```

**Comment by arose** [comment]
Hi, your example should actually work (though it is not documented)!

In the future it will be possible to send a bitset corresponding to the atom selection status to NGL. This is in the works.
