### ISSUE TITLE
block cell execution until receiving image data?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#147]
currently, we need to run two Cells to get image data

cell 1
```python
view.export_image(...)
```

then cell 2
```python
view.get_image()
```

this is necessary since `view.export_image` sends a message to NGL to tell it to `exportImage` to base64. If calling `view.get_image() right after calling `export_image` in the same Cell, the view._image_data is not updated.

How can we wait until the data is sent back from JS to Python?

**Comment by arose** [comment]
I would suggest to create a custom widget that shows a placeholder image/text and has some JavaScript code to wait (or periodically ask) for the image data.

**Comment by hainm** [comment]
I close this issue. Creating `widget` in JavaScript is actually not my desire anymore. Initial attempt is to save image to notebook so we can display it statically. If using widget, there won't be image, so it's just like using `NGLView widget`.

**Comment by hainm** [comment]
turns out that this is easy fix.

https://github.com/arose/nglview/pull/335

![render](https://cloud.githubusercontent.com/assets/4451957/16542109/0a1f7df4-4069-11e6-9bfd-1bb58ae71957.png)

I have not thought of any useful case for this, so just for fun for now.

**Comment by hainm** [comment]
thanks @arose for you tip.
