### ISSUE TITLE
option to show atom name for specific selection

### ISSUE THREAD

**Issue by hainm** [arose/nglview#15]
might be good for publication or viewing

```
tv.show_atom_name('1-3')
```
Source: http://x3dna.org/images/chi_anti_syn.png

![](http://x3dna.org/images/chi_anti_syn.png)

**Comment by arose** [comment]
There is the "label" representation

```
w.add_representation( "label", ".CA", color="grey" )
```

is this what you had in mind?

**Comment by hainm** [comment]
Oh really? Cool. I will try.

**Comment by hainm** [comment]
just tried label and this works.

may be adding `view.add_label('.CA', color='grey')`.

In my view, `add_representation` is something like cartoon, licorice.

**Comment by arose** [comment]
I suppose an API method `.add_label` is ok. Currently the API mirrors the way the underlying functionality  is implemented, which simplifies having an API (especially true for NGL itself).

**Comment by hainm** [comment]
we have 'add_label' now.
