### ISSUE TITLE
load binary file?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#150]
For example, how to load `ccp4` file?

- if file is in the current folder or subfolder, let NGL handle

- If not: open file, read then passing binary to NGL?

**Comment by hainm** [comment]
can we pass binary from Python to loadFile ins JS?

```python
import gzip
content = gzip.open('file.ccp4.gz').read()
# send content to `loadFile` in JS
```

**Comment by hainm** [comment]
```python
fh = open("./1CRN.cif.bz2", 'rb').read()
kw = dict(compressed=True, ext='cif', binary='bz2')
view.load_model(fh, **kw)
```
does not work. uhm.

**Comment by arose** [comment]
To load the file data into NGL a `Blob` object is used. For binary data the `type` of the blob needs to be different (`text/plain` does not work):

```JavaScript
var blob = new Blob( [ msg.args[0].data ], { type: "application/octet-binary" } );
```

**Comment by hainm** [comment]
@arose 

and, need to encode binary to base64 in Python, send to JS, decode in JS, create Blob with type: "application/octet-binary".

Such a long way but I made it work. Hopefully notebook >=5 (ipywidgets, ipykernels, ..) has better way to send binary.

**Comment by hainm** [comment]
closed by https://github.com/arose/nglview/pull/164
