### ISSUE TITLE
signal file drag and drop

### ISSUE THREAD

**Issue by hainm** [arose/nglview#152]
User can drag a file to Widget. We need to keep track of this event.

- file drop. NGL (JS side) send message to NGLView (python side).
- NGLView create an unique ID and append to '_model_ids'

**Comment by hainm** [comment]
@arose I've checked ngl code and there is no more "initFileDragDrop". Do you exclude it now?

If yes, I can close this issue.

**Comment by hainm** [comment]
ok, we should go through all issues in our meeting this weekend.

**Comment by arose** [comment]
I removed the drag'n'drop code as I found it too application specific. Here is how to handle it yourself.

```JavaScript
var container = stage.viewer.container;
container.dom.addEventListener( 'dragover', function( e ){
    e.stopPropagation();
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
}, false );

container.dom.addEventListener( 'drop', function( e ){
    e.stopPropagation();
    e.preventDefault();
    var file = e.dataTransfer.files[0]
    stage.loadFile( file, { defaultRepresentation: true } );
}, false );
```

**Comment by hainm** [comment]
ok, I will add it to widget.

**Comment by hainm** [comment]
to make your script works, I need to replace `container.dom` by `container.`

**Comment by hainm** [comment]
closed by https://github.com/arose/nglview/pull/165

**Comment by hainm** [comment]
wow, I am very productive today, after having long meeting with @arose. lol.
