### ISSUE TITLE
vmd-like: click two atoms to display distance

### ISSUE THREAD

**Issue by hainm** [arose/nglview#16]
In VMD, there is shortcut key (2) to change to click mode to display distance between two atoms.

**Comment by arose** [comment]
Yeah, this would be nice. Needs support in NGL, see https://github.com/arose/ngl/issues/46.

**Comment by hainm** [comment]
it's quite handy in `pv`

http://pv.readthedocs.io/en/v1.8.1/sample-measure-distance.html?highlight=distance

**Comment by hainm** [comment]
should be NGL.

**Comment by arose** [comment]
I recently added mouse bindings to do distance, angle, dihedral measurements. In the ts2 branch hold down shift and click 2 to 4 atoms and then click on the last atom again to get a measurement. Click on all the atoms of a measurement and click the last one twice to remove it.

**Comment by hainm** [comment]
wanna cut a release for it so I can try in nglview? or I just use the local build.

**Comment by arose** [comment]
need to setup making releases for the ts2 branch, local build is faster for now

**Comment by hainm** [comment]
okie

**Comment by hainm** [comment]
@arose  what's the exact command(s) to get ngl.js in ts2 branch?

**Comment by hainm** [comment]
```
npm install
npm run ts
npm run build-min
``` ?

**Comment by arose** [comment]
yes, looks good

**Comment by hainm** [comment]
thanks, but the updated ngl.dev.js does not work as expected. Shift with left mouse click will trigger the autoview to clicked atom.

**Comment by arose** [comment]
alt not shift, sorry

**Comment by hainm** [comment]
thanks. work now. Do you want to get feed back about that now or just experimenting?

**Comment by arose** [comment]
sure, feedback is always welcome
