### ISSUE TITLE
Don't show player when only a structure is loaded/only a single frame is available

### ISSUE THREAD

**Issue by arose** [arose/nglview#160]

**Comment by hainm** [comment]
ok. I added due to technical issue.

view.add_component(a_single_structure)  # no player

view.add_trajectory(traj) # --> should display

**Comment by arose** [comment]
I see, would be nice to workaround that eventually

**Comment by arose** [comment]
Maybe always create the player but hide it when only a single frame is available `this.$player.hide()`.

**Comment by hainm** [comment]
hide it is good. Will do.

**Comment by hainm** [comment]
closed b https://github.com/arose/nglview/pull/161
