### ISSUE TITLE
File drag: using the same default representation as when loading from Python?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#166]
@arose is there any code I can copy and paste? 

If not, I will make it my low priority since this is not a big deal right now.

**Comment by hainm** [comment]
related PR: https://github.com/arose/nglview/pull/165

**Comment by arose** [comment]
It is defined here https://github.com/arose/nglview/blob/master/nglview/__init__.py#L565-L575

**Comment by hainm** [comment]
can you point me to the method that update all representations from a list? 

```javascript
stage.loadFile(file).then(function(o) {
    o.addRepresentation(...);
}
```

The aim is to reuse `_init_representations` without copy and paste its content.

**Comment by arose** [comment]
you have to write to loop yourself

```JavaScript
reprDefList.forEach(function(reprDef){
  o.addRepresentation(reprDef.type, reprDef.params);
});
```

**Comment by hainm** [comment]
cool. that's what I need.

**Comment by hainm** [comment]
PR: https://github.com/arose/nglview/pull/167
