### ISSUE TITLE
Better repr default for nucleic

### ISSUE THREAD

**Issue by hainm** [arose/nglview#169]
Currently use cartoon.

**Comment by arose** [comment]
We could add a `base` representation?

**Comment by hainm** [comment]
like this? 

![index](https://cloud.githubusercontent.com/assets/4451957/15297568/d73c10ac-1b68-11e6-9423-678be628548b.png)

**Comment by hainm** [comment]
or just use `licorice`?

![index](https://cloud.githubusercontent.com/assets/4451957/15297627/1a10678e-1b69-11e6-8d5a-5259c63235b4.png)

**Comment by hainm** [comment]
related https://github.com/arose/ngl/issues/177

**Comment by hainm** [comment]
should be in NGL.
