### ISSUE TITLE
representation template?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#172]
try best to  guess

``` python
from nglview.representation_template import membrane
view.set_presentation(membrane, component=1)
```

**Comment by arose** [comment]
Do you have a list with common lipid residue names? Or do you have a suggestion on how to identify a lipid based on its atom names and bonds? I would happily add something to NGL.

**Comment by hainm** [comment]
I can do that survey for you. stay tuned.

**Comment by hainm** [comment]
not worth keeping this issue.
