### ISSUE TITLE
measure data sending speed (python to JS)

### ISSUE THREAD

**Issue by hainm** [arose/nglview#173]
in python
```python
from time import time
print(time())
view.send({'type': 'binary', 'data': ...}, buffers=...)
```

in Javascript:
```javascrip
if( msg.type == 'binary' ) {
    dateObj.getTime()?
}
```

**Comment by arose** [comment]
[`Date.now()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now)  gives you a unix timestamp

**Comment by hainm** [comment]
yeah. I updated to `binmsg` branch. Check them out. You can compare speed of sending base64 and binary.

**Comment by hainm** [comment]
Not sure if I did correctly. Getting negative value. :D 

reopen.

**Comment by hainm** [comment]
Close. Don't need now. (But still don't know why getting negative number)
