### ISSUE TITLE
faster sending get_structure_string

### ISSUE THREAD

**Issue by hainm** [arose/nglview#176]
You (@arose) asked me if I got issue with slow speed of sending structure to JS. I've always visualize large protein (30K atoms) in lap desktop so no slowness. But it took times to have NGL to display if using remote notebook.

**Comment by hainm** [comment]
or may be my internet at home is freaking slow.

**Comment by arose** [comment]
Thanks for testing. One option could be to encode/compress the data using our new mmtf file format. There is a very, very alpha python library (https://github.com/rcsb/mmtf-python). NGL can read that.

**Comment by hainm** [comment]
does it only support python2? I saw the `print` syntax.

**Comment by arose** [comment]
Probably, as I said, very alpha.

**Comment by hainm** [comment]
We (me) need to refactor `show_file_struture`. It's very slow for 1 million atom system. 

```python
class FileStructure(Structure):

    def __init__(self, path):
        super(FileStructure, self).__init__()
        self.fm = FileManager(path)
        self.ext = self.fm.ext
        self.params = {}
        self.path = path

    def get_structure_string(self):
        return self.fm.read(force_buffer=True)
```

`force_buffer=True` means the file content will be read by python, then will be sent to JS. Just let `ngl` handle that file if it (file) in the current or subfolder.

**Comment by hainm** [comment]
uhm, not sure about the 'slow' statement above. My computer is crazy.

**Comment by hainm** [comment]
close until getting the complain.
