### ISSUE TITLE
add show_url (or similiar)?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#177]
for example: https://raw.githubusercontent.com/arubenstein/PDZ_ddG/master/ancillary_files/input_pdbs/3qdo_complex.pdb

**Comment by arose** [comment]
One option would be to just send the url string to NGL and do `stage.loadFile( url ).then( ... )`

**Comment by arose** [comment]
I like to have such an API method

**Comment by hainm** [comment]
> One option would be to just send the url string to NGL and do stage.loadFile( url ).then( ... )

will do. just need to update code a bit.

**Comment by hainm** [comment]
so do you agree with `show_url` name?

**Comment by arose** [comment]
> so do you agree with show_url name?

yes

**Comment by hainm** [comment]
![url_nglview](https://cloud.githubusercontent.com/assets/4451957/15348080/6730a97a-1c95-11e6-9db9-e2a088aa09e3.png)
