### ISSUE TITLE
how to connect 2 notebooks?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#178]

**Comment by arose** [comment]
Have you seen someone doing that in another project?

**Comment by hainm** [comment]
I have not. Someone mentioned the same idea before (not sure where) and suggested to follow ipyparallel.

**Comment by hainm** [comment]
I just wish notebook has this function so I can use two screen.

**Comment by arose** [comment]
I say we wait until there is official support for it.

**Comment by hainm** [comment]
agree.

**Comment by hainm** [comment]
I say `I can't wait`

<img width="1279" alt="two_screens" src="https://cloud.githubusercontent.com/assets/4451957/15524784/21775876-21f3-11e6-9e98-fa52740c66de.png">

**Comment by hainm** [comment]
closed by https://github.com/arose/nglview/pull/201

**Comment by hainm** [comment]
also

```bash
jupyter console --exist
```
