### ISSUE TITLE
render many frames

### ISSUE THREAD

**Issue by hainm** [arose/nglview#180]
Need to think about implementation.

May be send frame indices to NGL, let it render and send back array of base64 data. 

We need to compute memory usage. Currently if using factor=12, one image will cost ~30mb

**Comment by hainm** [comment]
Q: how to estimate image size?

**Comment by arose** [comment]
the `factor` parameter is a multiplication factor for the width and height of the NGL canvas. A factor of 12 seems incredibly large, more than HD resolution, too large for a video I would say.

**Comment by hainm** [comment]
what's your suggestion for a reasonable factor?

**Comment by arose** [comment]
It kind of depends how big the canvas is, but for video 4 is probably more than enough.

**Comment by hainm** [comment]
I am fine with current solution: http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_movie/

so close this issue.
