### ISSUE TITLE
coloring does not work properly for this protein

### ISSUE THREAD

**Issue by hainm** [arose/nglview#181]
issue

```python
import nglview as nv
view = nv.show_structure_file('rhodopsin_step5_assembly.pdb')
view

view.clear_representations()
view.add_cartoon()
```

file: http://ambermd.org/tutorials/advanced/tutorial16/include/rhodopsin_step5_assembly.pdb

image: 
![download](https://cloud.githubusercontent.com/assets/4451957/15347275/3786a1cc-1c8e-11e6-9fff-5b019d02db65.png)

Note that if I use PDB ID: 1U19, NGL display beautifully.

Motivation try to make amber images nicer :D : http://ambermd.org/tutorials/advanced/tutorial16/#Membrane-Bound_Proteins

**Comment by hainm** [comment]
try to use color='rersidueindex' but no effect.

**Comment by arose** [comment]
I can't get to ambermd.org, seems down for me :-(

I suspect the problem is due to NGL coloring based on all atoms/residues, including water/lipid molecules and thus laving only a small part of the colorscale for the protein. I know this is problematic and I will fix this.

**Comment by hainm** [comment]
with 1U19 PDBID

**Comment by hainm** [comment]
no worry, github is not down yet :D 

https://github.com/hainm/amber_things/blob/master/things/ngl/rhodopsin_step5_assembly.pdb

**Comment by arose** [comment]
I see, lots of water and lipid molecules, so I was correct with my suspicion.

**Comment by arose** [comment]
see https://github.com/arose/ngl/issues/127

**Comment by arose** [comment]
"residueindex" colors now on a per chain basis, try ngl 0.10.0-dev.1

**Comment by hainm** [comment]
look good now. thanks.
