### ISSUE TITLE
How to render a bunch of snapshots? 

### ISSUE THREAD

**Issue by hainm** [arose/nglview#184]
Hint please. 

Issue:

- FileReader async
- how to update coordinates? By sending all needed frames like caching?

**Comment by hainm** [comment]
I spent whole afternoon writing code for this but decided to delete all of them. Debugging Javascript async is hard for me now.

**Comment by arose** [comment]
Hmm, I don't know what you did, but generally I think it is important to do everything sequentially (1) getting a frame, (2) rendering an image, (3) sending the image back, back to (1).

I think developing a robust solution will be a lot of work.

**Comment by hainm** [comment]
I am happy with current solution

http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_movie/

**Comment by arose** [comment]
> http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_movie/

cool!

Just using a hard coded timeout is also a solution :-)

**Comment by hainm** [comment]
> Just using a hard coded timeout is also a solution :-)

this is even better.

**Comment by hainm** [comment]
added this in nglview GUI. closed.
