### ISSUE TITLE
add some color templates

### ISSUE THREAD

**Issue by hainm** [arose/nglview#185]
NGL has so many combinations for color_sheme. So it may be best if we only pick up the nicest ones (subjectively).

```python
from nglview.color_scheme import MYCOLOR
view.add_cartoon(color_scheme=MYCOLOR)
```

Rationale: auto-completion.

**Comment by arose** [comment]
sounds good

**Comment by hainm** [comment]
We have selection widgets now. Close.

**Comment by jaimergp** [comment]
Sorry to write in a closed issue but... how can we use color schemes? I am trying to color by element, but no luck yet... I even cloned the repo to get the latest changes.

```python
w.parameters = {"colorScheme":"element"}
w.add_representation('ball+stick', radius=0.2, nearClip=False, selection='not #H', color_scheme="element")
```

I am also having problems selecting metals by element, by the way (C, N, O work fine with hashtag, but can't select Fe or Rh, for example).

Thanks,
Jaime.

**Comment by hainm** [comment]
@jaimergp: did you delete your question? I saw yours in my notification but can not see it here.

**Comment by jaimergp** [comment]
@hainm Yes, sorry about the confusion and the necrobump! I realized 2 mins after posting that it wasn't a problem of nglview, but my script's. Apparently, elements must be typed in uppercase to be recognized as a standard PDB ATOM entry (at least for ngl). With uppercase, atoms are colored by element properly.

**Comment by hainm** [comment]
I see.

I think case-insensitive is in TODO list: https://github.com/arose/ngl/issues/157
