### ISSUE TITLE
wrap NGL params with traitlets.Enum

### ISSUE THREAD

**Issue by hainm** [arose/nglview#189]
to avoid typos and to have good error message.

**Comment by arose** [comment]
+1 

Do you have an example?

Would you still do the "color templates #185"?

**Comment by hainm** [comment]
> Do you have an example?

```python
camera_type = Enum(["orthographic", "perspective"], default_value="perspective")
view.camera_type = "orthographci" # error will be raised.
```

> Would you still do the "color templates #185"?

Yes I think so. Need to discuss with your about which templates should be brought to NGLView.
I've tried on NGL website but there are so many choices and got confused. :D

**Comment by arose** [comment]
Is there a minimum Python version needed for `Enum`s?

**Comment by hainm** [comment]
We should use Enum from traitlets.

**Comment by hainm** [comment]
On going. Close.
