### ISSUE TITLE
Minimize sync 

### ISSUE THREAD

**Issue by hainm** [arose/nglview#195]
- `parameters`
- `orientation` #254

**Comment by arose** [comment]
+1 especially the orientation stuff, I guess

**Comment by hainm** [comment]
I hesitate to turn it off.

- I want to use it to set exact orientation after open the notebook.

- sync two screens (not a big deal, just in plan)

- make a test by compare the rendered image with saved image.

The question is: 

- Can we turn on/off sync in the fly?

- If not, should we make a meta class (to make new NGLView class with/without syncing `orientation`, ...)

**Comment by hainm** [comment]
ok. we can use `type` to create new class to turn on/off sync

check this out: https://github.com/arose/nglview/pull/213

**Comment by hainm** [comment]
```python
view = nv.show_pytraj(view, sync_camera=True)
```

**Comment by arose** [comment]
> Per orientation, I hesitate to turn it off.

wrapping the callback with a "throttle" function can help http://underscorejs.org/#throttle

**Comment by hainm** [comment]
thanks. will look into it.

currently we can turn on/off camera syncing by https://github.com/arose/nglview/pull/254
