### ISSUE TITLE
we need to sleep

### ISSUE THREAD

**Issue by hainm** [arose/nglview#198]
Playing with [`binary` message](https://github.com/arose/nglview/pull/168) I got interesting observation: need to add `sleep`

normal
```python
import pytraj as pt, nglview as nv
import numpy as np

traj = pt.datafiles.load_tz2_ortho()
traj = pt.replicate_cell(traj, direction='all') # 143K atoms

view = nv.show_pytraj(traj)
view
```

This requires few hundreds milliseconds to send the data from python to JS. However, If using `sleep`
and this explicit loop, the speed is 5 times faster.

```python
from time import time, sleep

for i in list(range(10))*5:
    xyz = traj[i].xyz.astype('f4')
    xyz_bytes = xyz.tobytes()
    mytime = time() * 1000
    msg = dict(type='binary_single', data={0: 0}, mytime=mytime)
    view.send(msg, buffers=[xyz_bytes])
    sleep(0.2)
```

**Comment by hainm** [comment]
So I guess we should definitely send a small chunk of data and join them in JS side.

might need to read `distributed`'s issues/PRs

https://github.com/dask/distributed/pull/221/files

https://github.com/dask/distributed/pull/224

**Comment by hainm** [comment]
or may be because `view.frame` is synced.

**Comment by hainm** [comment]
@arose : https://github.com/arose/nglview/blob/binmsg/nglview/tests/notebooks/playing_trick.ipynb

**Comment by hainm** [comment]
Will try to add delaying to NGL player.

**Comment by hainm** [comment]
Good motivation to reuse NGL player.

**Comment by arose** [comment]
Yeah, the current widget player is very rough. It just asks every 100 ms for a new frame, with complete disregard of the current state. I hope to have some time soon to look at NGL for that.

```javascript
this.playerInterval = setInterval( function(){
    var frame = this.model.get( "frame" ) + 1;
    var count = this.model.get( "count" );
    if( frame >= count ) frame = 0;
    this.model.set( "frame", frame );
    this.model.save();
}.bind( this ), 100 );
```

**Comment by hainm** [comment]
alternatively we can look at `IntSlider` and `Button` class in ipytwidgets.

http://stackoverflow.com/questions/32634142/linking-ipython-widget-button-and-slider-values

**Comment by hainm** [comment]
adding to Python side might be a good idea, since you only need to change `frame` in `python`, if `frame_change`, coordinates will be sent to `NGL` JS. 

If adding player in JS side, `frame` need to be sent to Python first. Syncing is the evil. :D

**Comment by hainm** [comment]
Done. We need to sleep without round trip.
