### ISSUE TITLE
Automatically refresh static assets/resources

### ISSUE THREAD

**Issue by arose** [arose/nglview#2]
For the notebook, static assets/resources (like JavaScript files) are installed with `notebook.nbextensions.install_nbextension`. When the assets are updated (often during development, for the user upon a new release) the browser still has them cached and a "forced" refresh is needed. This should happen automatically for new releases and caching should be switched off during development.

**Comment by arose** [comment]
try this (from https://github.com/ipython/ipywidgets/blob/master/examples/notebooks/Widget%20Low%20Level.ipynb)

```Python
from notebook.nbextensions import install_nbextension
from notebook.services.config import ConfigManager

def install(user=False, symlink=False, enable=False):
    """Install the widget nbextension and optionally enable it.

    Parameters
    ----------
    user: bool
        Install for current user instead of system-wide.
    symlink: bool
        Symlink instead of copy (for development).
    """
    staticdir = pjoin(dirname(abspath(__file__)), 'static')
    install_nbextension(staticdir, destination='widgets', user=user, symlink=symlink)

    cm = ConfigManager()
    cm.update('notebook', {
        "load_extensions": {
            "widgets/notebook/js/extension": True,
        }
    })
```

**Comment by marscher** [comment]
@arose This change actually makes it for the moment impossible to test the import statement in our preliminary conda recipe in omnia.md

The recipe simply imports nglview, which triggers the symlink creation. Can one circumvent this somehow?

``` python
===== testing package: nglview-0.4-py35_0 =====
import: u'nglview'
symlink /home/marscher/.local/share/jupyter/nbextensions/nglview -> /home/marscher/anaconda/envs/_test/lib/python3.5/site-packages/nglview/html/static
Traceback (most recent call last):
  File "/home/marscher/anaconda/conda-bld/test-tmp_dir/run_test.py", line 25, in <module>
    import nglview
  File "/home/marscher/anaconda/envs/_test/lib/python3.5/site-packages/nglview/__init__.py", line 447, in <module>
    install(symlink=True)
  File "/home/marscher/anaconda/envs/_test/lib/python3.5/site-packages/nglview/__init__.py", line 438, in install
    user=user, symlink=symlink)
  File "/home/marscher/anaconda/envs/_test/lib/python3.5/site-packages/notebook/nbextensions.py", line 204, in install_nbextension
    os.symlink(path, full_dest)
FileExistsError: [Errno 17] File exists: '/home/marscher/anaconda/envs/_test/lib/python3.5/site-packages/nglview/html/static' -> '/home/marscher/.local/share/jupyter/nbextensions/nglview'
TESTS FAILED: nglview-0.4-py35_0
```

**Comment by marscher** [comment]
@arose you can find the conda recipe here: https://github.com/omnia-md/conda-recipes/tree/master/nglview

**Comment by arose** [comment]
Yeah, the symlink is more for development.

**Comment by hainm** [comment]
Why does this cause error? I built the receipt for ambermd and got no problem importing it.

**Comment by marscher** [comment]
Probably because you use a custom statement (python -c 'import nglview as nv') to perform the import while I use the built in import test from conda, which tries to symlink to the test environment.

**Comment by hainm** [comment]
I see. Thanks.

Hai

**Comment by arose** [comment]
Removed it in this PR https://github.com/arose/nglview/pull/43

**Comment by hainm** [comment]
@arose can we close this issue now?
