### ISSUE TITLE
add testing on travis build

### ISSUE THREAD

**Issue by hainm** [arose/nglview#21]
we should do it.

chemview has very nice travis build here: https://github.com/gabrielelanaro/chemview/blob/master/.travis.yml

**Comment by arose** [comment]
That would certainly be nice. Feel free to have a go at it. I can add you as a collaborator so that you can work directly on the repository if you like.

**Comment by hainm** [comment]
> Feel free to have a go at it. I can add you as a collaborator so that you can work directly on the repository if you like.

sure (for both).

**Comment by arose** [comment]
I added you as a collaborator. I suggest that we both do PRs from now on for non-trivial changes.

**Comment by hainm** [comment]
yes, we should make a PR and have code review (except minor change like typos, fix style, ...)

**Comment by hainm** [comment]
done.
