### ISSUE TITLE
rename `html` folder

### ISSUE THREAD

**Issue by hainm** [arose/nglview#22]
there is nothing related to `html`. So what's about 'static' or 'js' or something else?

**Comment by arose** [comment]
I suppose we could move the `static` folder a directory up.

**Comment by hainm** [comment]
any other meaningful name? :D

**Comment by arose** [comment]
`resources`? I think I picked up html from some Jupyter example.

**Comment by hainm** [comment]
how's about `nbextension`

https://github.com/bloomberg/bqplot/tree/master/bqplot/nbextension

**Comment by hainm** [comment]
done, rename to `js`.
