### ISSUE TITLE
migrate to ipywidgets 5.x

### ISSUE THREAD

**Issue by hainm** [arose/nglview#220]
this is unavoidable but I think this would take lot of time, given the description in https://github.com/ipython/ipywidgets/issues/618

@arose This task is more JS related so I hope that you can work on this. :D

**Comment by hainm** [comment]
some related issues showing that users can not see the widgets

- https://github.com/arose/nglview/issues/214

- https://github.com/mdtraj/mdtraj/issues/1122

PS: I am not really sure if those issues happens because users installed ipywidgets 5.x or not.

**Comment by arose** [comment]
Should we do a release before migrating? I think yes as this seems a major change.

I am happy to work on that but would like to finish the reorganizing of the ngl code first.

**Comment by hainm** [comment]
> Should we do a release before migrating? I think yes as this seems a major change.

yeah, we should. how's about releasing by the end of June? or by next two weeks?)

**Comment by hainm** [comment]
@arose  my initial attempt here. You can start from there. https://github.com/hainm/test_ipywidget5

can not make it work yet, still got "Uncaught ReferenceError: THREE is not defined"

I myself really really don't like this migration even though it's unavoidable.

- First, require install `node` for development.

- complicated build process. With current code, I can add more code to `widget_ngl.js`, restart notebook and able to see the change. For this new migration, I need to use npm to rebuild whole process.

man, I really really hate that different packages keep breaking its API.

**Comment by arose** [comment]
thanks @hainm 

> man, I really really hate that different packages keep breaking its API.

:-) Widgets are still fairly new

**Comment by hainm** [comment]
I finally can make `nglview` works with `ipywidgets5`. Still on https://github.com/hainm/test_ipywidget5 repo.

Currently, for regular nbextensions, user need to to perform very complicated process to make it work with master branch

- `python setup.py install`

- `jupyter nbextension install --py --user nglview`

- `jupyter nbextension enable --py --user nglview`

It's really easy to make mistake (from my own pain experience). Also, `npm` is also required.

But for current development of nglview, I will (doing)

- included static/*.js files in nglview folder. So if users want to try master branch, they don't need `npm`.

- make `install` and `enable` extension in `__init__.py` (like what we have now). User only need to `python setup.py install`.

PS: My main motivation is to try `nglview` with [jupyterlab](https://github.com/jupyter/jupyterlab).

The Jupyter ecosystem is not really stable now (in my opinion), so I think we will postpone migrating to
`ipywidgets5`. To make a simple extension work, it's require to master Python, Javascript, to understand how the install stuff in Javascript works, to facepalm every non-informative error message (which is not intuitive at all).

**Comment by hainm** [comment]
Just make 'ipywidgets5' branch now.

**Comment by hainm** [comment]
TODO 

- [ ] install and activate nglview-js during setup so users don't need to do anything else.

**Comment by hainm** [comment]
done.
