### ISSUE TITLE
More info/docs on coloring or selections?

### ISSUE THREAD

**Issue by davidlmobley** [arose/nglview#222]
BTW, this is great. Beautiful smooth viewer.

But, now that I have this working on my mixed solvent system (as discussed here: https://github.com/mdtraj/mdtraj/issues/1122#issuecomment-222601126) I run into the issue that I'd like to be able to control the viewer to make, say, phenol molecules be one color and cyclohexane be another. 

It is unclear to me how to do this from the info I can find easily. I find code like this in the README.md:

```python
view.add_cartoon("protein", color="residueindex")
view.add_surface("protein", opacity=0.3)
```

But I have no protein, and it's unclear to me what is acceptable for the first argument. If I try `help(view.add_cartoon)` it only gives  me:
`func(this, selection='all', **kwargs) method of nglview.NGLWidget instance`

which is unhelpful. And, trying `view.add_cartoon("phenol", color="residueindex")` makes my viewer window disappear without any error message or anything (bug?).

**Comment by arose** [comment]
what are the group names of your phenol/cyclohexane molecules?

**Comment by hainm** [comment]
Can you try to replace 'phenol' by its resname? 

view.add_surface('ASP', opacity=0.3)

Please see selection language here

http://arose.github.io/ngl/doc/#User_manual/Usage/Selection_language

We are working in writing more doc now, but feel free to ask anything here.

**Comment by hainm** [comment]
Change color

view.add_surface('1', color='blue')

**Comment by davidlmobley** [comment]
My phenol has residue name `ZTF`, it seems (these are actually assigned randomly in this case). However, coloring it seems to fail, i.e. 
`view.add_surface('ASP', color='blue')`
results in no viewer window appearing (with no error) and likewise
`view.add_surface('1', color='blue')`

I'll consult the selection language and see if I can do anything useful.

**Comment by davidlmobley** [comment]
Hmm, so it seems not to be a problem with my selections, in that I don't get any viewer window even if I just do: 
`view.add_surface('all', opacity=0.3)`
which seems like it ought to work.

(Also, again, I get no info at all - just no viewer appearing, and no error messages or anything).

**Comment by davidlmobley** [comment]
I have the same issue (viewer window disappears) if I try:
`view.add_representation('spacefill', selection='all' )`
or any variant I've been able to come up with.

**Comment by davidlmobley** [comment]
@hainm - I also tried the same experiment in the test_mdtraj_nglview environment we created in the other thread, but I have the same issue - any messing with representation/surface/etc at all causes the viewer window to disappear. 

I also have two related problems with my other notebook which tries to view a simple trajectory run with OpenMM:
* If I view a trajectory run with OpenMM, I get an empty viewer window with a "play" button at the bottom but there is no content to play
* In troubleshooting, if I just remove that trajectory and instead view via `view = nglview.show_pdbid("3pqr")`, it works, UNTIL I try to change the representation at all, such as via `view.add_representation('spacefill', selection='all' )` in which case the viewer window just doesn't come up (no error message, etc).

I'm guessing this means I should probably find something else to show in my class (which was supposed to be today but I switched the lecture to Thursday so I'd have time to deal with this) as this seems maybe not quite ready for general usage, unless I'm missing something obvious.

**Comment by hainm** [comment]
Can you attach a simple notebook so i can look?

**Comment by davidlmobley** [comment]
The one(s) in teh other thread should work but I'll re-attach.

**Comment by hainm** [comment]
Btw, in my example 'ASP' is Aspartic residue. :d what I really meant is to replace it with whatever name that mdtraj/openmm give you.

**Comment by davidlmobley** [comment]
(About "ASP", I mistyped my code. I'd tried to select "ZTF" but it failed).

**Comment by hainm** [comment]
Ok, i will check your nb in about 1-2 hours later.

**Comment by davidlmobley** [comment]
[debugging.zip](https://github.com/arose/nglview/files/292398/debugging.zip)

OK, please try this. Maybe try Lec17_mixtures.ipynb first. Note the box at the top should be run to import stuff, but will fail with an exception because of the existing files I've included in 'data'. AMBER prmtop and .crd files are there in the `tleap` directory. I've also tried loading GROMACS ones but I can't get that to work for some reason.

**Comment by davidlmobley** [comment]
So, er, to get it to work, try making the top two lines:
```python
traj = md.load( 'data/tleap/phenol_cyclohexane_3_100.inpcrd', top = 'data/tleap/phenol_cyclohexane_3_100.prmtop' )
#traj = md.load( 'data/gromacs/phenol_cyclohexane_3_100.gro', top = 'data/gromacs/phenol_cyclohexane_3_100.gro' )
```

and then removing the line
`view.add_representation('1', opacity=0.3)`

If you add that last line back in, the viewer will disappear again (at least if it works for you the way it does for me).

**Comment by hainm** [comment]
@davidlmobley The first thing I realize is that you never display `view` to make it work

In first cell
```python
view = nglview.show_mdtraj(traj)
#view = nglview.show_pytraj(traj_pt)
view # you need to call this to display
```

then in 2nd cell
```python
view.add_surface(...)
view.add_licorice(...)
```

I will look other issues.

**Comment by davidlmobley** [comment]
The code in my notebook has:
```python
view = nglview.show_mdtraj(traj)
#view = nglview.show_pytraj(traj_pt)
view
```

**Comment by davidlmobley** [comment]
Elaborating, the relevant box has (stripping out commented stuff):
```python

import mdtraj as md
traj = md.load( 'data/tleap/phenol_cyclohexane_3_100.inpcrd', top = 'data/tleap/phenol_cyclohexane_3_100.prmtop' )

import nglview
import pytraj as pt

view = nglview.show_mdtraj(traj)
view

#view.add_representation('1', opacity=0.3)
```

If I leave it as is, I get a viewer with useful info in it. If I comment out the last line, I get nothing (no view window, no error, nothing).

**Comment by hainm** [comment]
yes, that is my point. To display in notebook, it need to call `view` in the last command.

**Comment by hainm** [comment]
You need to add `view.add_representation('1', opacity=0.3)` in another notebook cell.

**Comment by hainm** [comment]
![fireshot capture 13 - lec17_mixtures-_ - http___localhost_8888_notebooks_lec17_mixtures-copy1 ipynb](https://cloud.githubusercontent.com/assets/4451957/15695242/2ea384ea-2773-11e6-8ead-53f81524b0e2.png)

**Comment by davidlmobley** [comment]
Ah, so you're saying I just have to move the change of representation up. 

Well, that wasn't clear at all from the docs or examples. But yes, that seems to work for this.

OK, so that solves the problem with my mixed solvent notebook. However, I still have the issue that my OpenMM simulation brings up an empty viewer.

**Comment by davidlmobley** [comment]
(Thanks for that example you just sent though! Extremely helpful. So nwo I can use this for mixed solvents. Now if only I could view trajectories...)

**Comment by hainm** [comment]
> OK, so that solves the problem with my mixed solvent notebook. However, I still have the issue that my OpenMM simulation brings up an empty viewer.

can you make a list of bullet points in your 1st post so I can easily check?

**Comment by hainm** [comment]
this is your residue names

```python
print("residue set: %s" % set(residue.name for residue in traj.topology.residues))
# residue set: {'pheno', 'cyclo', 'solut'}
```

so, you can use
```python
view.add_surface('pheno', opacity=0.3)
```

**Comment by davidlmobley** [comment]
I'm going to have to disappear for a couple of hours momentarily. Bullet points on what?

Here's the code
```python
import os
import mdtraj
import mdtraj.reporters
from simtk import unit
import simtk.openmm as mm
from simtk.openmm import app
import mdtraj.testing
#pdb = mdtraj.load(mdtraj.testing.get_fn('native.pdb'))
pdb = mdtraj.load_pdb('http://www.rcsb.org/pdb/files/1LE1.pdb')
topology = pdb.topology.to_openmm()
forcefield = app.ForceField('amber99sbildn.xml', 'amber99_obc.xml')
system = forcefield.createSystem(topology, nonbondedMethod=app.CutoffNonPeriodic)
integrator = mm.LangevinIntegrator(330*unit.kelvin, 1.0/unit.picoseconds, 2.0*unit.femtoseconds)
simulation = app.Simulation(topology, system, integrator)
simulation.context.setPositions(pdb.xyz[0])
simulation.context.setVelocitiesToTemperature(330*unit.kelvin)
if not os.path.exists('test.h5'):
    simulation.reporters.append(mdtraj.reporters.HDF5Reporter('test.h5', 10))
    simulation.step(100)
print("Done")

from __future__ import print_function
import nglview
from IPython import display

traj = mdtraj.load('test.h5')
print(traj)

view = nglview.show_mdtraj(traj)
view
```
and it yields just an empty view window.

I'm not totally sure I'm doing the OpenMM simulation right, but this DID work a year ago with TrajectoryView, so one would think it should work. Really, I'm just after a minimal example of visualizing ANY OpenMM simulation, so if you don't like this one I'm open to anything else.

**Comment by hainm** [comment]
> Bullet points on what?

never mind. (I just want you make like this)

- [ ] phenol selection ...
- [ ] openmm issue ...

```bash
- [ ] phenol selection ...
- [ ] openmm issue ...
```

**Comment by hainm** [comment]
Per `openmm` issue, it's likely due to `openmm` and `mdtraj` themself. If I ran you script in my notebook with py35. I got 


```bash
/Users/haichit/miniconda/lib/python3.5/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    302                 raise ValueError(
    303                     "The file '%s' is already opened, but "
--> 304                     "not in read-only mode (as requested)." % filename)
    305             # 'a' and 'r+' are compatible with everything except 'r'
    306             elif mode in ('a', 'r+') and omode == 'r':

ValueError: The file 'test.h5' is already opened, but not in read-only mode (as requested).
```

**Comment by hainm** [comment]
After running openmm in one notebook, than open another one to reload `test.h5` file, it's ok too me.

![fireshot capture 14 - untitled - http___localhost_8890_notebooks_untitled ipynb_kernel_name python3](https://cloud.githubusercontent.com/assets/4451957/15695422/e6921728-2774-11e6-9afd-22765d9d31db.png)

**Comment by hainm** [comment]
more fun stuff

![fireshot capture 15 - untitled - http___localhost_8890_notebooks_untitled ipynb_kernel_name python3](https://cloud.githubusercontent.com/assets/4451957/15695448/3d4dfbcc-2775-11e6-8727-82ea4027148a.png)

**Comment by davidlmobley** [comment]
In Python 2.7, it doesn't work for me even if I just try to load the trajectory; after the usual import stuff at the top (cut off) I get this:
<img width="837" alt="mdtraj" src="https://cloud.githubusercontent.com/assets/7132257/15695922/af333d3e-2760-11e6-94e0-72d47f21b520.png">

**Comment by davidlmobley** [comment]
Maybe send me your traj.h5 and I can check if it's a problem with that?

**Comment by davidlmobley** [comment]
I could also go back to trying the minimal test environment you created earlier.

I had a couple minutes before I run out the door, hence the responses. But I'll (shortly) be delayed by a while.

**Comment by hainm** [comment]
sorry, just had dinner. This `test.h5` works for me.
[test.h5.zip](https://github.com/arose/nglview/files/292518/test.h5.zip)

**Comment by hainm** [comment]
also try files from `nglview`
![trr](https://cloud.githubusercontent.com/assets/4451957/15696151/df0f0c5c-277b-11e6-8b7d-458fec46270d.png)

this is also a trajectory

**Comment by davidlmobley** [comment]
Well, yup, your test.h5 works for me. So something is wrong with mine. 

That narrows things down by about, well, 50%. :) Any advice? Otherwise I'll go work on my openmm knowledge and bug those guys. Thanks for your help!

**Comment by hainm** [comment]
> Otherwise I'll go work on my openmm knowledge and bug those guys. Thanks for your help!

this definitely should go to `openmm` issue, out of our league since we (me and @arose) are not using openmm.

**Comment by hainm** [comment]
btw, I just install `openmm` and `mdtraj` from `omnia`

```bash
conda install openmm -c omnia --force
conda install mdtraj -c omnia --force
```

**Comment by hainm** [comment]
I just update a bit about coloring and atom selection: https://github.com/arose/nglview/commit/d90f57a3575e222babfacfa443ebd0923300c402

Due to our limited resource, doc is never done thoroughly.  But please ask anything you need, we might have it in `nglview` but hidden ( :D ).

For example, you can even add more `mdtraj.Trajectory` as you like

```python
# 1st cell
view = nglview.show_mdtraj(traj0)
view

# 2nd cell
# wrap mdtraj.Trajectory in nglview object
view.add_trajectory(nglview.MDTrajTrajectory(traj2))

# you can even mix pytraj and mdtraj too
view.add_trajectory(nglview.PyTrajTrajectory(pytraj_object))

# or even rdkit :D 
view.add_trajectory(nglview.RdkitStructure(its_object))
```

Of course, you need to take care by your own trajectory superimpose in `mdtraj`.

**Comment by davidlmobley** [comment]
Thanks for all the help! Turns out I have my issues resolved now. It appears the main problem was that I was just using an old .h5 file that wasn't being overwritten when I ran new ones because of the `if` statement. :) So now everything works. Nice viewer - good work! I'll definitely use this again in the future.

**Comment by hainm** [comment]
cool.

**Comment by davidlmobley** [comment]
So, @hainm - if I DO try:

> `view.add_surface('pheno', opacity=0.3)`

for some reason I get a surface which seems to correspond to the surface of my box rather than the surface of the individual phenol molecule. Insights?

**Comment by hainm** [comment]
can you post screenshot?

**Comment by davidlmobley** [comment]
Also, relatedly, if I clear all representations and then do 
`view.add_licorice('solut', color="blue")`
or
`view.add_licorice('pheno', color="blue")`

I end up with everything colored blue... 

This is with my residue set as `residue set: set(['pheno', 'solut', 'cyclo'])`. 

I'd really like to be able to color things separately and visualize just certain tings. 
![cursor_and_lec17_mixtures](https://cloud.githubusercontent.com/assets/7132257/15727522/e5ce8bf4-280b-11e6-9291-14123c731b4c.png)

**Comment by davidlmobley** [comment]
The surface issue. Zoomed in: 
![cursor_and_lec17_mixtures](https://cloud.githubusercontent.com/assets/7132257/15727540/09f187ca-280c-11e6-8e65-9b5463af4b41.png)

Zoomed out:
![cursor_and_lec17_mixtures](https://cloud.githubusercontent.com/assets/7132257/15727547/18460508-280c-11e6-8c8a-9a2dc2fdf424.png)

Sorry, I'm sure all of this is just me doing something wrong. But, maybe it will help you in terms of knowing the minimum you have to explain to a novice to get them going (i.e. the "view command has to be last" was a key piece of info which was non-obvious).

**Comment by hainm** [comment]
you need to set `opacity=0.3` (or others). The default is 1.0.

**Comment by hainm** [comment]
> (i.e. the "view command has to be last" was a key piece of info which was non-obvious).

this is my English issue.

**Comment by davidlmobley** [comment]
No, no. The problem is that I should be selecting only one molecule! i.e., "solut" specifies a single residue/moelcule.

**Comment by davidlmobley** [comment]
In other words, what I should be seeing is a single molecule represented as a surface and everything else should be licorice.

**Comment by hainm** [comment]
hold on. Let me check myself.

**Comment by davidlmobley** [comment]
Ah, OK. It seems as though it's the selection by residue name which is not working. If I use residue numbers I get the expected result:

![cursor_and_lec17_mixtures](https://cloud.githubusercontent.com/assets/7132257/15727622/b41bfffa-280c-11e6-96ce-896f12aef173.png)

**Comment by hainm** [comment]
I see why now. `nglview` uses `mdtraj`'s pdb resname for selection.

```python
print(view._trajlist[0].get_structure_string())
```

Got

```
REMARK   1 CREATED WITH MDTraj 1.7.2, 2016-06-01
CRYST1   26.790   26.791   26.790  90.00  90.00  90.00 P 1           1 
MODEL        0
ATOM      1  C1  sol A   1       0.860  24.880  21.210  1.00  0.00          C   
ATOM      2  C2  sol A   1       0.530  23.520  21.220  1.00  0.00          C   
ATOM      3  C3  sol A   1       0.400  22.840  22.430  1.00  0.00          C   
ATOM      4  C4  sol A   1       0.590  23.520  23.630  1.00  0.00          C   
ATOM      5  C5  sol A   1       0.920  24.870  23.630  1.00  0.00          C   
ATOM      6  C6  sol A   1       1.060  25.550  22.420  1.00  0.00          C   
ATOM      7  O1  sol A   1       0.460  22.850  24.810  1.00  0.00          O   
ATOM      8  H1  sol A   1       0.970  25.410  20.270  1.00  0.00          H   
ATOM      9  H2  sol A   1       0.380  23.000  20.280  1.00  0.00          H   
ATOM     10  H3  sol A   1       0.140  21.790  22.420  1.00  0.00          H   
ATOM     11  H4  sol A   1       1.070  25.400  24.560  1.00  0.00          H   
ATOM     12  H5  sol A   1       1.310  26.610  22.410  1.00  0.00          H   
ATOM     13  H6  sol A   1       0.620  23.450  25.560  1.00  0.00          H   
ATOM     14  C1  phe A   2       4.730  11.870  23.600  1.00  0.00          C   
ATOM     15  C2  phe A   2       4.490  12.310  24.910  1.00  0.00          C   
ATOM     16  C3  phe A   2       3.190  12.620  25.320  1.00  0.00          C   
ATOM     17  C4  phe A   2       2.130  12.490  24.420  1.00  0.00          C   
ATOM     18  C5  phe A   2       2.370  12.050  23.120  1.00  0.00          C   
ATOM     19  C6  phe A   2       3.660  11.740  22.710  1.00  0.00          C   
ATOM     20  O1  phe A   2       0.870  12.790  24.820  1.00  0.00          O   
ATOM     21  H1  phe A   2       5.740  11.630  23.290  1.00  0.00          H   
ATOM     22  H2  phe A   2       5.320  12.410  25.600  1.00  0.00          H   
ATOM     23  H3  phe A   2       3.020  12.970  26.330  1.00  0.00          H   
ATOM     24  H4  phe A   2       1.540  11.940  22.420  1.00  0.00          H   
...
```

so `pheno` should not work.

In your case, it's better to specify residue number as you are doing.

**Comment by hainm** [comment]
Here is mine

```python
view.clear_representations()
view.add_surface('1', opacity=0.3) # sol
view.add_surface('2, 3', color='blue', opacity=0.3) # phe
view.add_licorice() # all
```

make sure to specify space between residue number: `2,3` won't wok but `2, 3` does.

**Comment by hainm** [comment]
>  But, maybe it will help you in terms of knowing the minimum you have to explain to a novice to get them going 

Yes, your issues help us improve our doc a lot. thanks.

**Comment by davidlmobley** [comment]
Ah, OK. Probably would be helpful to have an example of how to retrieve residue names in the docs for the selections, here. My case is a little bizarre in that I don't actually have "normal" residue names nor do I pay that much attention to what they are, so I just need an easy way to look them up. :)

**Comment by hainm** [comment]
> Probably would be helpful to have an example of how to retrieve residue names in the docs for the selections, here. 

sure, I just open new issue #229 to remind us.

hint: You can click your mouse to specific residue and saw the atom or resname in top left of your screen.

**Comment by hainm** [comment]
![phe](https://cloud.githubusercontent.com/assets/4451957/15728154/c1805828-2828-11e6-8bf4-7baaa3b529f3.png)

**Comment by davidlmobley** [comment]
Thanks! Very helpful. Any easy ways to adjust depth clipping, etc. interactively? I haven't figured out much other than zooming and re-orienting; I was just starting to poke around to figure out if I could tell how to shift the view or to change depth clipping, etc.

**Comment by hainm** [comment]
I don't think you can do that interactively.

But you can update from commands. Here is example from README

```python
# parameters for the NGL stage object
view.parameters = {
    # "percentages, "dist" is distance too camera in Angstrom
    "clipNear": 0, "clipFar": 100, "clipDist": 10,
    # percentages, start of fog and where on full effect
    "fogNear": 0, "fogFar": 100,
    # background color
    "backgroundColor": "black",
}
```

if you just want to update one or two params, just
```python
view.parameters = {'clipNear': 50, 'backgroundColor': 'black'}
```

@arose knows better than me about those thing, so I let him chime when he is available.

**Comment by davidlmobley** [comment]
Hmm, I tried adding `view.parameters = {'clipNear': 50, 'backgroundColor': 'black'}` and I don't get a black background. Does this have to go somewhere in specific?

**Comment by hainm** [comment]
I am not sure. Just copy and paste your command

![black](https://cloud.githubusercontent.com/assets/4451957/15728436/526802e0-282a-11e6-9a8e-7abdb2e8dbfe.png)

**Comment by davidlmobley** [comment]
OK, thanks. I'm, er, going to declare victory without resolving this one. I'm doing the same thing as you for my mixture one and it's not working for me, but I need to do some other things and it's just not worth it. :) Thanks for all your help!

**Comment by hainm** [comment]
yeah.
