### ISSUE TITLE
better add_representation

### ISSUE THREAD

**Issue by hainm** [arose/nglview#24]
currently whenever `add_representation` is called, the viewer is re-rendered (?) so the transition is not smooth (structure disappears and reload).

try yourself in notebook

1st cell

```python
import pytraj as pt
import nglview as nv

t0 = pt.fetch_pdb('3pqr')
view = nv.show_pytraj(t0)

view.representations = []
view.add_representation('cartoon', color='residueindex')
view
```

2nd cell (cause non-smooth transition)
```python
view.add_representation('label', '.CA', color='blue')
```

**Comment by arose** [comment]
I see. This is expected as the representations are re-created, so `view.add_representation` is somewhat misleading. Currently there is no mechanism to keep track of what representation are shown in the viewer and hence it is not clear if update, addition or removal of representations is necessary given the synced dict of parameters. A set of parameters does not uniquely identify a representation, you could have two distinct given the same parameters.

**Comment by hainm** [comment]
check chemview: https://github.com/gabrielelanaro/chemview/blob/master/chemview/widget.py#L95

**Comment by hainm** [comment]
@arose does this feature need to be done in NGL? Or I can do it in NGLView widget js?

**Comment by hainm** [comment]
closed by https://github.com/arose/nglview/pull/73
