### ISSUE TITLE
Ctrl + right mouse for downloading current snapshot?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#250]
current implementation
```
# Using mouse to adjust desired frame
# Using mouse to adjust desired angle

# then
view.download_image()
```

We can add "Ctrl + right click" on widget to save image too.

**Comment by hainm** [comment]
since this is API, we need more discussion about this.

**Comment by arose** [comment]
> We can add "Ctrl + right click" on widget to save image too.

That seems a bit like a hidden "trick"

**Comment by hainm** [comment]
Ha ha. Agree. What your fastest way to save images? For example rotating by mouse, save, rotate different angle, save....

**Comment by arose** [comment]
some button to click on?
