### ISSUE TITLE
release next Monday?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#255]
I am thinking about releasing `nglview` next Monday if you (@arose) don't have any objection. Will do thorough testing this weekend.

I will upload tar file from `python setup.py sdist` to github so you can upload to your pypi account.

**Comment by arose** [comment]
> I am thinking about releasing nglview next Monday if you (@arose) don't have any objection. Will do thorough testing this weekend.

I have some time this weekend and will have a look!

**Comment by hainm** [comment]
cool. this is a list of notebooks you might want to look first: https://github.com/arose/nglview/blob/master/devtools/make_test_js.py

I frequently them automatically in my laptop with `nightwatch`.

**Comment by hainm** [comment]
I just create `v0.5.rc-0` [tag](https://github.com/arose/nglview/releases/tag/v0.5-rc.0)

travis: [ok](https://travis-ci.org/arose/nglview/builds/137123975)
notebooks were tested on my mac: ok

**Comment by hainm** [comment]
created tag [v0.5](https://github.com/arose/nglview/releases/download/v0.5/)

Please upload to your pypi account:
https://github.com/arose/nglview/releases/download/v0.5/nglview-0.5.tar.gz

**Comment by arose** [comment]
I'll put the issues I am finding here as it probably only small stuff.

Doing `from mdtraj.testing import get_fn` in `examples/view_trajectory.ipynb` requires `nose` which isn't a requirement (and should not be).

**Comment by hainm** [comment]
ok. For notebook issues, I will make a PR after gathering all of yours. They are not included in `.tar.gz` file anyway. :D

**Comment by hainm** [comment]
and please make bullet points.

```bash
- [ ]
```

**Comment by kain88-de** [comment]
Is the 0.5 release already final as the tags suggest? When do you update the conda packages?

**Comment by hainm** [comment]
> Is the 0.5 release already final as the tags suggest?

yes.

> When do you update the conda packages?

I submitted a PR here: https://github.com/bioconda/bioconda-recipes/pull/1319
(But I am thinking about creating `nglview` channel too. Probably this week).

**Comment by kain88-de** [comment]
ok so bioconda is the channel to use and not omnia?

**Comment by hainm** [comment]
I think either is ok to use. I dont have control over omnia channel so I myself prefer to use bioconda (once nglview is accepted).

**Comment by arose** [comment]
> Please upload to your pypi account:

Will update this evening

**Comment by hainm** [comment]
so I just fixes most of the notebook and I updated your comment (with bullet points). https://github.com/arose/nglview/pull/264

The only thing left is if you add a structure (not trajectory) and then add trajectory, the player won't play. I don't know how to fix yet.

**Comment by hainm** [comment]
>  trajectory not playing in tests/notebooks/test_show_pdbid.ipynb

ok. I think I am just lucky to have a fix https://github.com/arose/nglview/pull/270.

We definitely should release `v0.5.1`.

Please try to finish those steps this evening:

- [ ] test 
```bash
notebooks/fix_player_if_adding_single_struture_first.ipynb
notebooks/test_show_pdbid.ipynb
# and few others if you want (but I already tested and they are not critical)
```
- [ ] make tag `v0.5.1`

- [ ] upload to `pypi`

- [ ] update `README.md` for `pip` section. I will take of conda stuff.

**Comment by arose** [comment]
* uploaded v0.5 to PyPI https://pypi.python.org/pypi/nglview/0.5
* updated the v0.5 release notes on github

**Comment by arose** [comment]
:-) https://pypi.python.org/pypi/nglview/0.5.1

**Comment by hainm** [comment]
Great. Thanks. 

Can you also update "Development status" on pypi from "alpha" to something else (stable?).

**Comment by arose** [comment]
> Great. Thanks.

Thank YOU! Lots of cool stuff in this release.

> Can you also update "Development status" on pypi from "alpha" to something else (stable?).

That is done in setup.py `CLASSIFIERS`. I would suggest "Development Status :: 4 - Beta". We can do that for the next release.

**Comment by hainm** [comment]
> That is done in setup.py CLASSIFIERS

I always edit directly on pypi with `pytraj` :D 

But it's not a big deal.

**Comment by hainm** [comment]
- [x] updated website http://arose.github.io/nglview/release/v0.5.1/

- [x] updated `mybinder` with `v0.5.1`: mybinder.org/repo/hainm/nglview-notebooks

**Comment by hainm** [comment]
@arose I just crated `v0.5.2` tag. Please update to pypi too. thanks.

https://github.com/arose/nglview/releases/tag/v0.5.2

**Comment by hainm** [comment]
updated to `bioconda` channel: https://github.com/bioconda/bioconda-recipes/pull/1815

**Comment by arose** [comment]
will do this evening
