### ISSUE TITLE
add_representation is too sensitive to space

### ISSUE THREAD

**Issue by hainm** [arose/nglview#26]
FYI:

working
```python
view.add_representation('cartoon', color='residueindex')
```

NOT working (there is extra space in `cartoon` word

```python
view.add_representation('cartoon ', color='residueindex')
```

- can you confirm in your computer?
- if my statement is true, what's our solution here, either
    - I can use python to strip left and right spaces
    - you take care js side

**Comment by arose** [comment]
Yes, that does not work. I am okay with sanitizing the input on the Python side. It is always good to sanitize user input as early as possible.
