### ISSUE TITLE
density map and so on

### ISSUE THREAD

**Issue by hainm** [arose/nglview#27]
hi,

is there anyway to add the electron density map?

![](http://www.topsan.org/@api/deki/files/6426/=LLPdmmap.png)

**Comment by arose** [comment]
There is support for `map`, `ccp4`, `dx`, `bindx` and `cube` volume files in NGL but adding them via the nglview widget is not implemented.

**Comment by hainm** [comment]
@arose what's the difficulty of adding that to notebook? (if not that difficult, I can spend time on learning to port to nb).

My lab is interested in crystall simulation so it would be helpful to see it in notebook.

**Comment by arose** [comment]
Adding the file to the viewer with `stage.loadFile` is straightforward. I see two obstacles. 1) Getting the binary data to the Browser. 2) Keeping track of what files are loaded into the viewer.

1) You could to a base64 encoding in Python to get a text representation, send it over and decode it in the Browser.
2) Related to https://github.com/arose/nglview/issues/29. If we limit it to a single density a similar approach to the single structure that we currently allow to load can be done.

**Comment by hainm** [comment]
given the popularity of [Coot](https://www.google.com/search?q=Coot%3A+model-building+tools+for+molecular+graphics&rlz=1C1CHMO_enUS485US485&oq=Coot%3A+model-building+tools+for+molecular+graphics&aqs=chrome..69i57j69i58&sourceid=chrome&ie=UTF-8)

I highly recommend to add this feature to notebook. :D

**Comment by hainm** [comment]
so now I know 

- how to loadFile via `view._remote_call`
- how to control each component in compList

made progress. :D 

> You could to a base64 encoding in Python to get a text representation, send it over and decode it in the Browser.

Now I know how to do it.
