### ISSUE TITLE
Binary messages between kernel and browser

### ISSUE THREAD

**Issue by arose** [arose/nglview#3]
Does IPython support binary messages between kernel and browser? Modern browsers can receive binary and save it in an ArrayBuffer. This would make sending coordinates and topology data to the browser more efficient. It is often in an binary format in the kernel and can consumed as such in the browser thus avoiding converting/parsing to/from JSON.

**Comment by hainm** [comment]
you meant this? https://github.com/ipython/ipython/pull/6110

**Comment by arose** [comment]
This seems to be it, now, how to use it?

Looking at the VisPy widget suggests to handle messaging yourself and not via "traitlet" properties
https://github.com/vispy/vispy/blob/master/vispy/html/static/js/webgl-backend.js#L85

**Comment by hainm** [comment]
we should definitely explore this binary support. For large system, I got lagging.

**Comment by hainm** [comment]
@arose is there anyway to send 3D array coordinates at once to JS side? (instead of calling get_coordinate_list). The current implementation is quite slow for movie. :D

**Comment by arose** [comment]
> @arose is there anyway to send 3D array coordinates at once to JS side? (instead of calling get_coordinate_list). The current implementation is quite slow for movie. :D

Yeah, I agree it is too slow. I have no quick fix in mind, will think about it. It should be much better when passing binary data. Not sure if this would be sufficient or preloading or caching of coordinates will then be still needed.

**Comment by hainm** [comment]
yeah, if cache is good solution, we can add it

```python
nv.show_pytraj(traj, cache=True)
```

**Comment by arose** [comment]
> yeah, if cache is good solution, we can add it

If this helps, sure!

I meant caching on the Browser side, though.

**Comment by hainm** [comment]
`tobyes()` we go.

```python
In [11]: xyz.shape
Out[11]: (5293, 3)

In [12]: %timeit xyz.ravel().tolist()
1000 loops, best of 3: 752 µs per loop

In [14]: %timeit xyz.flatten().tolist()
1000 loops, best of 3: 789 µs per loop

In [13]: %timeit xyz.ravel().tobytes()
10000 loops, best of 3: 22 µs per loop
```

**Comment by hainm** [comment]
@arose 
supposed we can send binary data to JavaScript side, how to pass the data to NGL? (how to convert python's bytes to ArrayBuffer?)

**Comment by hainm** [comment]
base64-inizing numpy array and use cache (send dict of base64) to JS make the trajectory playing smoother when playing.

Also adding option to sync a single `coordinates`  by encode it to base64.

PR: https://github.com/arose/nglview/pull/67

Hopefully I don't not have false positive.

**Comment by arose** [comment]
Just figured ok how to send binary data without serialization, preparing a PR now.

**Comment by hainm** [comment]
> Just figured ok how to send binary data without serialization, preparing a PR now.

really? wow. You rock, man.

**Comment by arose** [comment]
first version in this PR #168

**Comment by hainm** [comment]
interested to read: http://matthewrocklin.com/blog/work/2016/04/14/dask-distributed-optimizing-protocol

(having `msgpack` too)

**Comment by hainm** [comment]
I think we can close it. Binary is implemented (by you :d). Will open another issue about how to send binary efficiently.
