### ISSUE TITLE
Orthographic view?

### ISSUE THREAD

**Issue by dotsdl** [arose/nglview#31]
Couldn't find anything in the docs, but is there a way to switch the viewer to an orthographic mode instead of perspective?

**Comment by arose** [comment]
wip, see https://github.com/arose/ngl/issues/28

**Comment by hainm** [comment]
@dotsdl thanks to @arose, NGLView does have orthographic camera now.

https://github.com/arose/nglview/pull/158

**Comment by hainm** [comment]
notebook: https://github.com/arose/nglview/blob/master/nglview/tests/notebooks/test_camera_type.ipynb

**Comment by dotsdl** [comment]
Sweet! Thanks! I hope to start using NGLViewer for production images now instead of *just* quick visualization. :D

**Comment by hainm** [comment]
you can use `view.download_image(factor=12)` to have high resolution rendering. good for publication too.
