### ISSUE TITLE
can not display widget more than once

### ISSUE THREAD

**Issue by hainm** [arose/nglview#312]
Not sure why. In the past, we can displayed the same widget as many times as we like. 

![2parts](https://cloud.githubusercontent.com/assets/4451957/16397411/50e3fd6c-3c92-11e6-9757-a56cac779a78.png)

**Comment by hainm** [comment]
bad news: So now we can not include `view` in `ipywidgets's VBox and HBox`. What did I do???

**Comment by hainm** [comment]
@arose I need your advice here.

**Comment by arose** [comment]
I'll have a look, but it will probably take a few weeks as there are some upcoming conferences

**Comment by hainm** [comment]
Thanks. Take your time. It's low priority but i can't fix due to limited js skill.

**Comment by hainm** [comment]
I originally thought this was due to the camera syncing I introduced. However removing camera sync code does not help.

**Comment by hainm** [comment]
I just tried to checkout v0.4 (can display two widgets), update ngl.js dev code and still able to see two widgets. I guess I made some changes `widget_ngl`. :D

**Comment by hainm** [comment]
phew, the trouble code is here

```javascript
            this.displayed.then( function(){
                var width = this.$el.parent().width() + "px";
                var height = "300px";
                var state_params = this.stage.getParameters();

                this.setSize( width, height );
                this.$container.resizable(
                    "option", "maxWidth", this.$el.parent().width()
                );
                this.model.set('loaded', true);
                this.model.set('camera_str', JSON.stringify( this.stage.viewer.camera ) );
                this.model.set('orientation', this.stage.viewer.getOrientation() );
                this.requestUpdateStageParameters();
                this.model.set('_original_stage_parameters', state_params);
                this.touch();
            }.bind( this ) );
```

removing all the `this.mode.set ...` lines will help.

I misunderstood that the `displayed` method is equal to `widget created` :D
