### ISSUE TITLE
View is only changeable when it's displayed.

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#328]
I'm always confused at first that I can only interact with the view once I have it shown. Initially I always try to do this in a cell

```python
view = ng.add_mdanalysis(u.atoms)
view.clear_representations
view.add_backbone()
view
```

and then I wonder why I only see the default representation. It would be nice if the representations could already be changed before I display the view.

**Comment by hainm** [comment]
Are you using Firefox? It's known bug and I don't know how to fix yet. 

Work fine for me with Chrome

![display](https://cloud.githubusercontent.com/assets/4451957/16492197/f0e015f8-3eae-11e6-911c-dd6ca57e70b7.png)

Detail implementation: `view` has `_ngl_displayed_callbacks` list that stores all functions needed to be executed **right after** the `view` is displayed (which is good for your case :D).

https://github.com/arose/nglview/blob/master/nglview/__init__.py#L680-L683

**Comment by hainm** [comment]
oops, `add_backbone`

![display](https://cloud.githubusercontent.com/assets/4451957/16492605/5edf4ba4-3eb0-11e6-8f06-502bec99b712.png)

**Comment by hainm** [comment]
it've just tested three OS

- win: firefox and chrome work fine
- osx: safari + chrome work fine. (I don't have firefox in my mac)
- linux: chrome works fine. Firefox seems problematic.

**Comment by kain88-de** [comment]
Yes I'm using Firefox on Linux.  Firefox v47.0 on Fedora 23 to be exact.

**Comment by hainm** [comment]
@kain88-de if you use the most updated dev code, below will do the trick with your Firefox on Linux

`view.show_mdanalysis(u, gui=True)`
![nglview_firefox](https://cloud.githubusercontent.com/assets/4451957/16597631/f9088086-42c7-11e6-8095-ed72b829b3a4.png)

PS: I have no idea why. :D

**Comment by kain88-de** [comment]
Yup that works. Strange

**Comment by hainm** [comment]
@kain88-de welcome to asynchronous world. I **think** I have a fix now. try it out.

https://github.com/arose/nglview/pull/351

![nglview_firefox](https://cloud.githubusercontent.com/assets/4451957/16599159/0b69b16c-42cf-11e6-9be3-0b5c48e40990.png)

**Comment by kain88-de** [comment]
works. Thanks
