### ISSUE TITLE
Preparing 0.4 release

### ISSUE THREAD

**Issue by arose** [arose/nglview#33]
- [x] Update API documentation
- [x] Update Changelog
- [ ] Add notebook examples
- [x] Note support for pytraj, mdanalysis, mdtraj, simpletraj prominently in README
- [x] Resolve dependency issue #17

**Comment by hainm** [comment]
- [ ] update this figure too: https://github.com/arose/nglview/blob/master/nglview.png

(should use show_mdtraj)

**Comment by arose** [comment]
I am inclined to leave the notebook examples for later and release asap. Anything else that might be blocking?

**Comment by hainm** [comment]
nothing else I can think of.

> I am inclined to leave the notebook examples for later and release asap

:+1:

**Comment by arose** [comment]
@hainm thx for the code review!

**Comment by hainm** [comment]
can you highlight the new features in v0.4 here: https://github.com/arose/nglview/releases/tag/v0.4?

**Comment by arose** [comment]
I could copy the changlog into it

**Comment by hainm** [comment]
also, the `README.md` is not displayed nicely in pypi:

https://pypi.python.org/pypi/nglview/0.4

**Comment by arose** [comment]
> also, the README.md is not displayed nicely in pypi:

I know, sometimes it is rendered as markdown, sometimes not, not sure why.

**Comment by hainm** [comment]
may be because of 

Installation
============

(should be
Installation
========)

and so on?

**Comment by arose** [comment]
no, the headings underlines have the correct length, it just looks like they are too long because of the variable width font

**Comment by hainm** [comment]
@arose I think you need to update the pypi doc by yourself.

I did that for pytraj: https://pypi.python.org/pypi/pytraj
