### ISSUE TITLE
create new organization for nglview?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#35]
what do you think about create `ngl` organization? or anything that has fancy name.

pros:
- you (@arose) can make a PR and let travis do the install and testing rather pushing directly to arose/nglview
- Other can review your PR :D

**Comment by hainm** [comment]
`ngl` org
`ngl/nglview`
`ngl/ngl`
`ngl/nglview-notebooks`

**Comment by arose** [comment]
Well, I could just do PRs from another branch, but was too lazy today :-)

**Comment by hainm** [comment]
> Well, I could just do PRs from another branch, but was too lazy today :-) 

lol. ok. But when I finish with the travis testing stuff, you should do that to make sure nglview runnable and passes the tests.

**Comment by arose** [comment]
I will think about it, feels bit over-engineered with the low amount of contributors.

**Comment by arose** [comment]
> lol. ok. But when I finish with the travis testing stuff, you should do that to make sure nglview runnable and passes the tests.

:+1:

**Comment by hainm** [comment]
> I will think about it, feels bit over-engineered with the low amount of contributors.

agree.
