### ISSUE TITLE
make Widget draggale?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#353]
Here is the issue we need to discuss

- If keep adding cells, we can not see the Widget.

- We can not let two notebooks communicate

- We can use `jupyter console` to pop up to control the widget but we can not use GUI

How's about make our widget draggable and floatable? 

It's easy to do but need discussion ('cause it's crazy).

```javascript
$(this.$container).draggable();
```

![screenshot](https://cloud.githubusercontent.com/assets/4451957/16601880/ca90e7c8-42dd-11e6-9cfd-32966a24e288.png)

**Comment by hainm** [comment]
basically we can rearrange notebook layout to make more space.

**Comment by hainm** [comment]
lol. this is even crazier.

![screenshot-1](https://cloud.githubusercontent.com/assets/4451957/16602119/abbcfb82-42df-11e6-9cf4-8c46c0f36f5b.png)

**Comment by arose** [comment]
maybe with dialog (would need to remember to cell element to bring back into the cell)

```
$( "#nglCanvasElem" ).dialog({
  appendTo: "#someElem"
});
```

**Comment by hainm** [comment]
Can we communicate with dialog in notebook?

**Comment by hainm** [comment]
If yes, your solution is very good.

**Comment by arose** [comment]
> Can we communicate with dialog in notebook?

I don't see why not, we just put it somewhere else on the same page. IMHO, there should be a general solution to "pop-out" a notebook cell. Is there?

**Comment by hainm** [comment]
Should be. But we can try dialog first.

**Comment by hainm** [comment]
another try (my local branch)

![display](https://cloud.githubusercontent.com/assets/4451957/16606280/bcd53e28-4304-11e6-8018-9b369a1dfbaf.png)

**Comment by hainm** [comment]
Done by #362

**Comment by hainm** [comment]
dialog is awesome. Making player GUI by `ipywidgets` then creating `dialog`.

@arose you should keep making suggestions. ;)

![viewer_pop_up](https://cloud.githubusercontent.com/assets/4451957/16709241/d8083084-45d8-11e6-9d13-33a49af739a6.png)

**Comment by arose** [comment]
> dialog is awesome. Making player GUI by ipywidgets then creating dialog.

nice!

> @arose you should keep making suggestions. ;)

always
