### ISSUE TITLE
showing a AtomGroup loses local changes

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#359]
When I show a AtomGroup the coordinates are reloaded from the trajectory. If I made any local changes for modeling or analysis they are lost and I can't check if any of my transformation had the desired effect. To reproduce this see code below.

``` python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD
import nglview as ng

u = mda.Universe(PSF, DCD)
p = u.select_atoms('all')

# change into principle axes frame
pa = p.principle_axes()
p.translate(-p.center_of_geometry())
p.rotate(pa)

p.write('psf_in_pa.pdb')

# this will show the protein with the original loaded coordinates
view = ng.show_mdanalysis(p)
view

# now the protein is shown in the principal axes coordinates system
u2 = mda.Universe('psf_in_pa.pdb')
view2 = ng.show_mdanalysis(u2)
view2
```

I'm aware this is mostly a problem of MDAnalysis and the  current behavior is good to look at a trajectory. To look at a single AtomGroup this isn't ideal though. Adding a new keyword to `show_mdanalysis` to not reload the coordinates would be good solution.

**Comment by hainm** [comment]
@kain88-de 

I am really confusing. Can you please re-explain your point here?

PS: your script does not work for me. 

```bash
AttributeError: 'AtomGroup' object has no attribute 'principle_axes'
```

Installed from

```
commit 5d78f0302bf55180c34a80fa897dc2a960cd298a
Merge: c11cb74 852daec
Author: Oliver Beckstein <orbeckst@gmail.com>
Date:   Wed Jul 6 17:34:55 2016 -0700
```

**Comment by hainm** [comment]
this is how `nglview` get coordinates from MDA

https://github.com/arose/nglview/blob/master/nglview/__init__.py#L504-L528

**Comment by hainm** [comment]
@kain88-de what's the status of this issue?

**Comment by hainm** [comment]
I go ahead closing this issue. Feel free to reopen it.

**Comment by kain88-de** [comment]
Here is a [gist]https://gist.github.com/kain88-de/726a2446a7b0f93d5e316db124b59d5f) for the problem. I expect both views to show the same rotation for the protein but they don't.

Sorry for the late answer

**Comment by hainm** [comment]
uhm I am confused. I think other programs behave the same when you transform your molecule based on principal axes.

![paxes](https://cloud.githubusercontent.com/assets/4451957/17438054/fe15aa4c-5aee-11e6-9e34-046118208b70.png)

**Comment by hainm** [comment]
@arose ping you if you have any comment.

**Comment by kain88-de** [comment]
you can even store the coordinates in `p.positions.copy()` and compare them before and after showing them with nglview. They will don't be identical anymore.

**Comment by hainm** [comment]
can you paste exact script here?

**Comment by hainm** [comment]
damn, I see now. Did you mean the in memory transformed Universe and the saved pdb should have the same orientation, right? (because they have the same coordinates).

**Comment by kain88-de** [comment]
I updated the gist. And yes that's what I meant.

**Comment by hainm** [comment]
ok. Let me see why.

**Comment by hainm** [comment]
@kain88-de can you make a PR to your need? You just need to update the `get_structure_string` code.

```python
    def get_structure_string(self):
        try:
            import MDAnalysis as mda
        except ImportError:
            raise ImportError(
                "'MDAnalysisTrajectory' requires the 'MDAnalysis' package"
            )
        u = self.atomgroup.universe
        u.trajectory[0]
        f = mda.lib.util.NamedStream(StringIO(), 'tmp.pdb')
        print(f)
        atoms = self.atomgroup.atoms
        # add PDB output to the named stream
        atoms.write(f)
        # extract from the stream
        pdb_string = f.read()
        return pdb_string
```

`pytraj` and `MDAnalysis` have very different philosophy so I had very hard time using MDA.

Or you can post the updated code here so I can make a PR.

**Comment by hainm** [comment]
FYI: this is from `pytraj` implementation with on-disk trajectory

![pt](https://cloud.githubusercontent.com/assets/4451957/17443550/33ecabba-5b09-11e6-9a75-64e8063e6615.png)

**Comment by hainm** [comment]
> Adding a new keyword to show_mdanalysis to not reload the coordinates would be good solution.

we do not need to add any keyword. I inline to make `nglview` to show only updated coordinates after the transformation.

**Comment by kain88-de** [comment]
The code that you show also has issues when I use a MDAnalysis universe that has no frames, I do create some of them during modeling.

Since MDAnalysis reads coordinates again during iteration the default mode of nglview (showing a trajectory) is absolutely OK to reset the coordinates and I would expect it. But this means I can't view a single atomgroup as it is in memory. I would suggest to add a `single_frame` kwarg to tell nglview that it shouldn't iterate over the trajectory. @dotsdl what do you think of such a solution to view single atomgroups in nglview?w

```python
# default to a trajectory
view = ng.show_mdanalysis(ag)  #  uses default single_frame=False

# show only the coordinates in the atom group as is
ng.show_mdanalysis(ag, single_frame=True)
```

I don't think this is possible without a kwarg. If we use the current contents of the atomgroup to display the protein during the first draw it will be impossible to get these coordinates back when I'm hitting play. It's just fundamentally different in MDAnalysis to look at a single Atomgroup or to iterate over a trajectory.

**Comment by hainm** [comment]
adding additional keyword is not an issue, but what's real code for 

```python
if single_frame:
   ...
```

You're welcome to make a PR about that and we can discuss further.

**Comment by hainm** [comment]
it's likely this issue is due to the design of `MDAnalysis`, so I close it. Feel free to reopen or make a new one.
