### ISSUE TITLE
should have a conda channel?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#36]
currently nglview uses omnia channel.

Should nglview has its own channel to have more control? or just need make a PR to https://github.com/omnia-md/conda-recipes/blob/master/nglview/meta.yaml?

another thought: can bioconda accepts nglview? https://github.com/bioconda/bioconda-recipes

**Comment by hainm** [comment]
I added nglview to ambermd channel  too: https://anaconda.org/AmberMD/nglview

But I prefer to centralize it. May be should focus on omnia channel.

**Comment by hainm** [comment]
@arose I think we should make a PR to `bioconda` channel. (vs ambermd, omnia, ...) since there are more people to maintain it.

https://github.com/bioconda/bioconda-recipes/issues/1305

**Comment by hainm** [comment]
will finish this PR once v0.5 released. https://github.com/bioconda/bioconda-recipes/pull/1319#discussion_r59671767

**Comment by hainm** [comment]
we are using `bioconda` as our official channel. close.

**Comment by hainm** [comment]
uhm, `bioconda` channel is too big now and it takes really long (12 hours) to wait for the PR checking. Given that it's easy to build `nglview`, I think we just need to build it by our own then uploading to `nglview` channel.

**Comment by kain88-de** [comment]
MDAnalysis and datreant are going to use conda forge. They are pretty nice lots of help with packaging and you have control over the packages you publish as a maintainer. The current release is not on conda forge yet but the next one will be and I already created packages for all missing dependencies.

**Comment by hainm** [comment]
Same as bioconda (i have control the pr). The main point is the waiting time since travis resource is limited. conda-forge is using travis too.

**Comment by kain88-de** [comment]
conda-forge actually uses travis for MAC builds and circle CI for linux builds. In my experience the builds are done a lot faster then 12 hours. But travis also had a lot of problems recently with available mac os machines.

**Comment by kain88-de** [comment]
BTW there is a conda-forge package now. 

https://github.com/conda-forge/nglview-feedstock
