### ISSUE TITLE
add link to matplotlib animation + more interactive with other libraries 

### ISSUE THREAD

**Issue by hainm** [arose/nglview#37]
You posed a script on gist and I also have an adaped version to link viewer to matplotlib 

Consider this as a potential feature.

![image](https://cloud.githubusercontent.com/assets/4451957/13231672/f3fc4338-d978-11e5-969a-a2eb4781713e.png)

**Comment by hainm** [comment]
adapted from your (@arose)

https://github.com/hainm/nglview/blob/master/nglview/link.py

Note: this script does not work with current nglview code.

**Comment by arose** [comment]
yes, good idea

the gist in question: https://gist.github.com/arose/ce0fdf44bd508f6fc216

**Comment by hainm** [comment]
more example

![ani](https://cloud.githubusercontent.com/assets/4451957/14933974/e5f31962-0e6e-11e6-89b9-e7229dd86298.gif)

**Comment by cing** [comment]
Do we know why this gist isn't working with the current nglview code?

**Comment by hainm** [comment]
I am not sure why. I will try to add a working notebook for this. will ping you later. cheers.

**Comment by cing** [comment]
It seems to me that it works fine without the `frame_changed()` method, see here: https://gist.github.com/cing/925d2eead0ecba2fe066455269a7941a

**Comment by hainm** [comment]
ah yes. I removed `frame_changed` method in favor of using `observe`  decorator

https://github.com/arose/nglview/blob/master/nglview/__init__.py#L697-L701

**Comment by cing** [comment]
Cool, but why should we use `observe`? The coordinates/frame already change when you click on the scatterplot. 

If you want, I can take a shot at contributing a notebook about this, RMSD or end to end distance with one of the existing sample datafiles.

**Comment by hainm** [comment]
> Cool, but why should we use observe? 

this relates to other things, not only matplotlib. It's suggested from [ipywidgets](http://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#Arguments-that-are-dependent-of-each-other) too.

> If you want, I can take a shot at contributing a notebook about this, RMSD or end to end distance with one of the existing sample datafiles.

yeah please. Update your notebook and you link to example here: https://github.com/arose/nglview/tree/master/examples.

Feel free to contribute any notebook that you would like to.
Cheers

**Comment by hainm** [comment]
Ideally we should just use `traitlets.link` to link widgets.

http://ipywidgets.readthedocs.io/en/latest/examples/Custom%20Widget%20-%20Hello%20World.html

(note for myself too).

**Comment by hainm** [comment]
> Cool, but why should we use observe? The coordinates/frame already change when you click on the scatterplot. 

oh, did you ask `why` in the context of the maplotlib linking in this post? You can ignore it if that works for you. `nglview` API change a lot, so ...

**Comment by cing** [comment]
Oh my mistake, when you click on the plot it updates the trajectory frame, but the opposite doesn't work when you remove frame_changed. I'll try to get it working nicely with matplotlib widgets first.

**Comment by hainm** [comment]
if does not work, try this

```python
from traitlets import observe

@observe('frame')
def frame_changed(self, change):
    # nglview.NGLWidget.on_frame(ngl_widget) # do we need this?
    self._set_coordinates(self.frame)
    
    if ngl_widget.isClick is True:
        ngl_widget.isClick = False
    else:
        dot.set_xdata((x[ngl_widget.frame]))
        dot.set_ydata((y[ngl_widget.frame]))
        linev.set_xdata(ax.get_ybound()[0])
        lineh.set_ydata(ax.get_xbound()[0])
        
ngl_widget.on_frame = frame_changed
```

**Comment by hainm** [comment]
We have bokeh example now. 

I still find it difficult to play with matplotlib.
 
Close.

**Comment by gph82** [comment]
Hi IDK the status of this issue, in particular the "backward"-link mode where moving the slide-bar moves the dot on the plot, but this works:
https://github.com/gph82/nglview_notebooks/blob/master/frame_observer(1).ipynb
Thanks @arose for the initial idea (almost a year ago?) and @clonker for the help

**Comment by gph82** [comment]
BTW:
```conda list | grep -e nbext -e widg -e ngl -e mdtraj -e notebook -e ipython -e jupy
ipython                   5.1.0                    py34_0  
ipython-notebook          4.0.4                    py34_0  
ipython_genutils          0.1.0                    py34_0  
ipywidgets                5.2.2                    py34_0  
jupyter                   1.0.0                    py34_3  
jupyter_client            4.1.1                    py34_0  
jupyter_console           4.1.0                    py34_0  
jupyter_core              4.0.6                    py34_0  
nglview                   0.6.2.1                  py34_0    bioconda
notebook                  4.2.3                    py34_0  
widgetsnbextension        1.2.6                    py34_0 
```

**Comment by hainm** [comment]
cool. thanks.

**Comment by hainm** [comment]
@gph82 is that link stable? I would like to make show cases for `nglview` and will put your link there.

**Comment by gph82** [comment]
yeah, but perhaps you can guide me as to how to save the state of the nglviewer widget as a bitmap so that it gets rendered. Then I'll so some cleaning and renaming and you can add it. 

How do I save the notebook with the rendered structure?

**Comment by hainm** [comment]
Please see here

http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_notebook/

Basically you need to call

render_image
_display_image

in two cells 

Hai

**Comment by gph82** [comment]
I don't mean the image itself, I mean something like this:
![snap5](https://cloud.githubusercontent.com/assets/7518004/21144637/bde97dae-c14b-11e6-9d83-5a6d307f4c87.png)

**Comment by hainm** [comment]
It's on going work in ipywidgets, no there is ni way to do that for now.

I will ping you when that's available.

**Comment by gph82** [comment]
Ok, this link should be fine: 

https://github.com/gph82/nglview_notebooks/blob/master/frame_observer.ipynb

**Comment by gph82** [comment]
I'm noticing it's not entirely robust towards paying around with the ngl_viewer's GUI and some its function (i.e. the plot becomes unresponsive) but I guess this is a start and the kinks can be worked out in the future.

**Comment by hainm** [comment]
> but I guess this is a start and the kinks can be worked out in the future.

True

btw, I just made a link: https://github.com/arose/nglview#showcase-from-users
thanks

**Comment by gph82** [comment]
great, thanks

**Comment by gph82** [comment]
Hi guys, no need for other issue whatsoever. Here's the updated version of the the notebook that uses nglview, for you to include in your examples.

https://github.com/gph82/molPX_notebooks

There you can find a mybinder.org badge. It works, but their servers are down very often...

The notebook is very extended and showcases molPX, https://github.com/markovmodel/molPX, a module that obviously would be impossible without nglview, so @hainm thanks for the support these last days and thanks @arose for the first proof-of-function of this.
