### ISSUE TITLE
Q: workflow?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#39]
what's your workflow when modifiying ngl, then update code to nglview?

I tried to modified `nglview/html/static/ngl.js` but my VIM program was freezing because it does not like that many lines of codes (41K). Can you just keep the original files from ngl (https://github.com/arose/ngl/tree/master/js/ngl)

If keeping the original files degrades the performance, can you post the exact commands you used? thanks from JS noob.

**Comment by arose** [comment]
Call `make.sh` within the `build` directory from the ngl repository. This will create/update a number of files in the `js/build/` directory from ngl. The `ngl.js` file from that directory is what you are looking for.

However, it should really, really not be necessary to change the ngl build! Anything in particular your are trying to achieve?

I don't think putting the plain source from ngl here. At best it should be just one minified file including all the libraries. Currently it is not minified for debugging purposes.

**Comment by hainm** [comment]
> Anything in particular your are trying to achieve?

camera and snapshot stuff. But mostly just for my curiosity to play with your code.

**Comment by arose** [comment]
> camera and snapshot stuff. But mostly just for my curiosity to play with your code.

I see. For ngl development the are html files (html/ngl.dev.html & html/embedded.dev.html) setup that use the source files so that no compiling is required.

**Comment by hainm** [comment]
thanks.

**Comment by hainm** [comment]
@arose which text editor you're using to write JS? I am using VIM for python but don't feel comfortable with JS (mostly because JS does not have command line tool like Ipython or notebook so I can't explore all methods easily). Any tips?
