### ISSUE TITLE
wishlist: bring menu to jupyter

### ISSUE THREAD

**Issue by hainm** [arose/nglview#4]
the right menu so users can make different representation.

http://arose.github.io/ngl/?example=3pqr

**Comment by arose** [comment]
Yeah, you could just put it into the widget, but then there would be no syncing between the browser and the kernel. I think it is best to postpone adding an elaborate GUI to after such syncing is handled.

At least it is currently possible to change the representations via Python

```Python
w = NGLWidget(...)
w.representations = [
    { "type": "cartoon", "params": {
        "sele": "protein", "color": "residueindex"
    } },
    { "type": "ball+stick", "params": {
        "sele": "hetero"
    } }
]
```

**Comment by hainm** [comment]
> At least it is currently possible to change the representations via Python

sounds good.
