### ISSUE TITLE
Cel shading render style

### ISSUE THREAD

**Issue by hainm** [arose/nglview#40]
IMO, pv package has very cute render: https://biasmv.github.io/pv/demo.html

not sure how hard to implement it in nglview

![download](https://cloud.githubusercontent.com/assets/4451957/13244417/1b7e3f64-d9d4-11e5-841b-4d73568c44d1.png)

**Comment by dotsdl** [comment]
Looks cel-shaded. No idea about the technical difficulties in making it work in `ngl`, but would use.

**Comment by arose** [comment]
Good that you bring that up. IIRC I had it at one point but removed it :-)

Just created an ngl issue https://github.com/arose/ngl/issues/52

**Comment by hainm** [comment]
should be NGL.
