### ISSUE TITLE
Headless render?

### ISSUE THREAD

**Issue by jaimergp** [arose/nglview#404]
I need to screenshot a bunch of small molecules and was previously using Chimera for that. However, I don't want to such a large package as a dependency of my tiny script... 

The question is... Is it possible to use nglview to render images programatically, from a script, without a notebook? 

Thanks!

**Comment by hainm** [comment]
> is it possible to use nglview to render images programatically, from a script, without a notebook?

No, it's impossible without a notebook.

But we can auto-make a notebook from your Python script, let the notebook run by itself. 

I will ping you when we finish this stuff.

Meanwhile, please check the command line usage with autorun the first cell of the notebook.

https://github.com/arose/nglview#command-line

**Comment by jaimergp** [comment]
That'd mean we'd need a browser and a notebook anyway, which would not be suitable for server-side tasks. I was thinking of trying something like selenium + phantomjs or similar, but don't even know how to start.

Another possibility would to export the 3D polygons and render that with vapory, vispy or any 3d library...  Any ideas?

**Comment by hainm** [comment]
>  I was thinking of trying something like selenium + phantomjs or similar, but don't even know how to start.

We are using nightwatch and selenium for testing the notebooks. You can check it out here

```bash
# cd nglview/root/folder
git clone https://github.com/hainm/nbtests
# edit ./devtools/make_test_js.py to your need (but try to run the default first)
python ./devtools/make_test_js.py
nightwatch
```

**Comment by hainm** [comment]
> Another possibility would to export the 3D polygons and render that with vapory, vispy or any 3d library... Any ideas?

I will let @arose reply to you.

**Comment by hainm** [comment]
alternatively, you can use pymol for script rendering.

**Comment by arose** [comment]
> The question is... Is it possible to use nglview to render images programatically, from a script, without a notebook?

It is currently not supported but in the future it will be using [NGL](https://github.com/arose/ngl/) directly, see https://github.com/arose/ngl/issues/173.

**Comment by jaimergp** [comment]
Wow, that'd be so nice. Do you have any estimations on when it would be ready? Thanks for your time, @hainm, @arose!

**Comment by arose** [comment]
> Do you have any estimations on when it would be ready?

It will probably be mounth. We need it ourselves but it is not the current priority.

**Comment by jaimergp** [comment]
> alternatively, you can use pymol for script rendering.

This is what I am doing for now. Thanks for the suggestion, @hainm. I'll be waiting for the changes anyway, @arose!

**Comment by hainm** [comment]
Just for the record, ipyvolume seems have a work around: https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/headless.py

**Comment by jaimergp** [comment]
This could be a cool alternative: https://twitter.com/jonmmease/status/1283766297650749440?s=19

**Comment by hainm** [comment]
Great. I will check it out. Thanks.
