### ISSUE TITLE
Can I have two MDA.Atomgroups in the same view?

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#434]
I want to show two different simulations at the same time in a view. Which function of a view to I need call to show another simulation as well.

```python
ref = mda.Universe(...)
u = mda.Universe(...)
# do some alignment 
view = ng.show_mdanalysis(u)
view. #? what do i call here to also show ref in the view?
```

**Comment by hainm** [comment]
```python
view.add_trajectory(ref)
```

**Comment by hainm** [comment]
doc:

https://github.com/arose/nglview#trajectory

**Comment by kain88-de** [comment]
OK now I feel stupid that I overlooked that one. Thanks.
