### ISSUE TITLE
add alias for commonly used representations?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#45]
for example
```python
view.add_representation('cartoon', selection='not hydrogen', color='red')
```

alias
```python
view.cartoon('not hydrogen', color='red')
```

and so on.

What do you think?
(learn from chemview and pv programs).

**advantage**: we can use autocompletion.

**Comment by hainm** [comment]
@arose what's your opinion about this? If OK, I can submit a PR this week (before going to AMBER meeting this March 17).

**Comment by arose** [comment]
Should we call it `add_cartoon` to make clear that it adds a representation? Otherwise I like it.

**Comment by hainm** [comment]
> add_cartoon

:+1:  yeah, I like this one better (vs. self.cartoon(...))

**Comment by hainm** [comment]
check https://github.com/arose/nglview/pull/47
