### ISSUE TITLE
Some documentation links are broken

### ISSUE THREAD

**Issue by maxentile** [arose/nglview#466]
Hi -- thanks for this really great project! It's been super helpful to have access to the NGL viewer as an IPython widget.

Just wanted to point out that there are a couple of broken documentation links. E.g. [the docstring for `add_representation`](http://arose.github.io/nglview/dev/api.html#nglview.NGLWidget.add_representation) points to http://arose.github.io/ngl/doc/#User_manual/Usage/Molecular_representations , which doesn't exist

There are a few other references to http://arose.github.io/ngl/doc/ which end up at 404 pages: https://github.com/arose/nglview/search?utf8=%E2%9C%93&q=http%3A%2F%2Farose.github.io%2Fngl%2F

These should probably point to http://arose.github.io/nglview/dev/index.html instead?

**Comment by hainm** [comment]
should be fixed now (https://github.com/arose/nglview/pull/467). thanks for your report. cheers.

**Comment by maxentile** [comment]
Awesome, thanks @hainm !
