### ISSUE TITLE
get_atom_indices

### ISSUE THREAD

**Issue by hainm** [arose/nglview#48]
currently, AMBER use non-friendly atom mask syntax (but very flexible). Since we are proposing passing atom indices for nglview, we can also get the atom indices back by using nglview's selection too.

```python
atom_indices = view.get_atom_indices(selection='charged')
```

**Comment by arose** [comment]
When atom bitsets are available in NGL this can be implemented

**Comment by hainm** [comment]
@arose: I don't like `get_atom_indices` name, so do you have any suggestion?

**Comment by hainm** [comment]
close. already discussed in SD. no need.
