### ISSUE TITLE
Add vdw display option

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#488]
Having easy access to a vdw representation would be nice. Like `add_vdw`. I currently need to manually set the representation. Example and picture below. (protein is 1E8L)

```
v.representations = [
    {"type": "spacefill", "params": {
        "radiusType": 'vdw',
    }}
]
```

![screenshot 1](https://cloud.githubusercontent.com/assets/4302678/18880762/4e554ab2-84d9-11e6-82c9-378b946e5d07.png)

I would also be interested in a general `add_ball` method to only show balls of a specific radius. See example below. That is great to visualize some coarse grained models vy some software (e.g. [HYDROPRO](http://leonardo.inf.um.es/macromol/programs/hydropro/hydropro.htm) )

```
view.representations = [
    {"type": "spacefill", "params": {
        "radiusType": 'size',
        "radius": 4.2
    }}
]
```

![screenshot](https://cloud.githubusercontent.com/assets/4302678/18880607/bed383e0-84d8-11e6-9b41-73de0d594e3e.png)

**Comment by hainm** [comment]
I just added `spacefill` (should have better way to sync with `ngl` with this aspect)

your 1st example:

`view.add_spacefill(radius_type='vdw')`

your 2nd example
`view.add_spacefill(radius_type='size', radius=4.2)`

About the naming, I tend to keep things consistent. 

e.g
```bash
v.representations = [
    {"type": "spacefill", "params": {
        "radiusType": 'vdw',
    }}
]
```

will be translated as `view.add_spacefill(radius_type='vdw')`

**Comment by hainm** [comment]
#489

**Comment by kain88-de** [comment]
thanks that already helps.
