### ISSUE TITLE
how to color each residue differently 

### ISSUE THREAD

**Issue by msultan** [arose/nglview#491]
Hey guys, 
Thanks a lot for developing this package. Its really awesome! I am trying to setup a view where I color each residue in my protein differently(similar to the default layout but with custom colors). I was trying to play with the ```view.add_repr ``` method but i cant seem to get it to work. 

```python
import seaborn as sns

view = nglview.show_mdtraj(t1.superpose(t1[0]))
view.clear()
view.add_cartoon('protein', color=sns.cubehelix_palette(t1.n_residues))
```

Am I missing something very simple here?

**Comment by hainm** [comment]
Hi

It is not implemented yet in nglview although NGL does has that. I will ping you when it's available. Cheers.

**Comment by msultan** [comment]
Thanks for the quick reply @hainm . And please do keep me in the loop.

**Comment by hainm** [comment]
Can you reopen this to remind us.

Hai

**Comment by hainm** [comment]
@msultan I have a quick demo here: #492 for your need.
Still need more time to think about API. You need to create a list of hex colors by yourself.

```python
import nglview as nv

view = nv.demo()
view

# use hex values for now.
colors = ['0x0000FF', '0xFF0000'] * 1000 # for 2000 residues.
view._set_color_by_residue(colors, component_index=0, repr_index=0)
```

**Comment by hainm** [comment]
from your example

```python
import seaborn as sns

view = nglview.show_mdtraj(t1.superpose(t1[0]))
view.clear()
view

view.add_cartoon('protein')
view._set_color_by_residue(sns.cubehelix_palette(t1.n_residues).as_hex())
```

**Comment by msultan** [comment]
@hainm this is awesome! Thanks a lot for putting this together so quickly. Its working perfectly.

**Comment by msultan** [comment]
Closing this now.

**Comment by tonka-balonka** [comment]
Hi, I've successfully used the `view._set_color_by_residue(colors)` function before, but since I've updated `nglview` to `2.6.1`, I get the following error: `'NGLWidget' object has no attribute '_set_color_by_residue'`.
I've checked the source code and the function is missing from `widget.py` and I couldn't work out if there's an alternative that will allow me to custom color my residues. Any help is greatly appreciated as I really need this function :smile:

**Comment by hainm** [comment]
hi, sorry about that. Can you please adapt this function below?

```python
    def _set_color_by_residue(self, colors, component_index=0, repr_index=0):
        self._remote_call('setColorByResidue',
                           target='Widget',
                           args=[colors, component_index, repr_index])
    if not hasattr(view, '_set_color_by_residue'):
        view._set_color_by_residue = _set_color_by_residue
```

**Comment by hainm** [comment]
Otherwise, use can try to use the private (unfortunately) `_ColorScheme` class.
https://github.com/arose/nglview/pull/755

**Comment by tonka-balonka** [comment]
Thanks a lot for the quick reply!
I've managed to sort it out with `_ColorScheme`.

**Comment by dwhswenson** [comment]
@hainm Any chance custom residue coloring might move into the API? It is really useful, and although I know *I* can hack something that works when I need to, I'm not keen on recommending something that my downstream users do something that isn't necessarily stable upstream.

I came across this issue, coincidentally having had the same problem as @tonka-balonka at about the same time -- I was trying custom coloring for the first time in a year. I wanted to color a protein by the fraction of time a drug molecule spends in contact with each residue -- you see how this could be neat?

**Comment by hainm** [comment]
Hi, ok, this will be my top priority. Cheers.

**Comment by dwhswenson** [comment]
Thank @hainm! I'll open a PR soon so you can see the specific use case

**Comment by hainm** [comment]
hi all, please try v2.6.7 for public API for customize color scheme: 

https://github.com/arose/nglview/issues/839

**Comment by tonka-balonka** [comment]
Hi, I def agree with @dwhswenson that this is a really useful option to have and thank you for implementing it so quickly.
I rewrote my code and it works like a charm!

**Comment by shayanhoss** [comment]
Hi @hainm I am trying to create a custom color mapping by position of amino acid residue but not using a simple 3 color RGB color map. For each position I have a hex color code (color representation of values from -2 to +2). I have tried using 'ColormakerRegistry.add_selection_scheme' to generate a list with [Position, hexcode] but this mapping doesn't seem to work. Is there a way to do custom color mapping using hexcodes to reflect gradients ?

**Comment by shayanhoss** [comment]
Is there any color mapping function that takes continuous inputs rather than discrete?
