### ISSUE TITLE
pep8

### ISSUE THREAD

**Issue by hainm** [arose/nglview#5]
I think nglview should follow Python's pep8 (https://www.python.org/dev/peps/pep-0008/)

If anyone does not want to remember anything, just install `autopep8` and do

```bash
autopep8 -a -i your_file.py
```

the magic will happen.

**Comment by arose** [comment]
Yeah, this is good. Thanks for bringing this up!

**Comment by arose** [comment]
Fixed starting in c05944cb106b59971542df389e40be49e656bd20.
