### ISSUE TITLE
NGLviewer doesn't start in jupyter-notebook

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#505]
Hey,
I am having some troubles with NGLviewer in jupyter notebook. If I check with Firebug the console output I am getting:
"NetworkError: 404 Not Found - http://localhost:8888/static/nglview-js.js?v=20161102152701"

and nothing visualizes.

The `~/.jupyter/nbconfig/nglview.json` file contains this:

```
{
  "load_extensions": {
    "": true
  }
}
```
How do I install the js?

I tried installing (and uninstalling and reinstalling) nglview from conda. Didn't seem to help.

**Comment by hainm** [comment]
Can you install github version and let us know if that work?

**Comment by hainm** [comment]
The possible reason is that notebook, ipywidgets, jupyterlab, .... evolved quickly that make incompatible API. You might accidentally overwrite required ipywidgets version by installing another package that need newer version.

**Comment by stefdoerr** [comment]
Yep, works with github version. Now how do I uninstall it though? :P Because I need to be able to check if the conda one works

**Comment by hainm** [comment]
pip uninstall nglview

**Comment by hainm** [comment]
The  conda one should work but it require ipywidgets < 5.0

The github version only work with >5.0.

**Comment by stefdoerr** [comment]
Oh! Ok then we should make a release from the github version. Are you planning to make one soon? Otherwise I will make one.

**Comment by stefdoerr** [comment]
Also I can't break it anymore. Uninstalling with pip and conda doesn't help. I think once I installed the github version it left something over.

**Comment by hainm** [comment]
Try to remove related stuff in

.local/share/jupyter

Hai

**Comment by hainm** [comment]
And double check your ipywidgets version.

**Comment by stefdoerr** [comment]
ok great that broke it again :) thanks. ipywidgets version is 5.2.2
So we need the github version then

**Comment by hainm** [comment]
So I can close this now. current nglview in bioconda require version <=4.1.1.

A part of conda recipe:

```bash
package:
  name: nglview
  version: !!str 0.5.1

source:
  url: https://github.com/arose/nglview/archive/v0.5.1.tar.gz
  fn: v0.5.1.tar.gz

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - ipywidgets <=4.1.1
    - traitlets

  run:
    - python
    - numpy
    - ipywidgets <=4.1.1
    - jupyter
    - traitlets
    - notebook
    - ipython <=4.1.2
```

Per @stefdoerr about releasing, I open an issue here #506

**Comment by stefdoerr** [comment]
Awesome! Love the GUI as well :) I will advertise it a bit in our [workshop](http://workshop.htmd.org/) next week if it's ok.

**Comment by hainm** [comment]
cool. yeah. You're also very welcome to suggest any new features.

**Comment by stefdoerr** [comment]
Now that you mention :) A really minor thingy that bothers me is that "kernel restart (clear output)" clears all jupyter output except the widgets. I guess there is more important stuff but if you ever get to fix that it would be great.

**Comment by hainm** [comment]
That's ipywidgets issue, not ours. :D 

https://github.com/ipython/ipywidgets/issues/607
