### ISSUE TITLE
release 0.6 version?

### ISSUE THREAD

**Issue by hainm** [arose/nglview#506]
from  @stefdoerr
> Oh! Ok then we should make a release from the github version. Are you planning to make one soon? Otherwise I will make one.

@arose: I am fine with making a release now. So it's up to you. 

- 259 commits from last version: https://github.com/arose/nglview/releases
- should we bump to `1.0`? `ipywidgets` seems to be stable now.
- Please take time to run few notebook test but do not expect all of them work. I just don't have time to fix them. But `nglview` code coverage is quite good (95%) and I also added some mocking tests for GUI.

**Comment by stefdoerr** [comment]
I'm making a PR with wrappers for HTMD in 20 min. Would be cool if that gets included as well.

**Comment by hainm** [comment]
you can build `nglview` in your own channel with given git tag.

**Comment by stefdoerr** [comment]
Yeah we already did that. Just saying in case you make an official release we could then also drop the one from our own channel.

**Comment by hainm** [comment]
@stefdoerr btw, this should be updated

https://github.com/Acellera/htmd/blob/master/htmd/molecule/molecule.py#L1018-L1019

`def get_coordinates(self, index)` should return a numpy 3D array. We use raw array for better performance.

**Comment by stefdoerr** [comment]
what are the dimensions?
Because ours are [natoms, 3, nframes]

**Comment by stefdoerr** [comment]
Ah a 3D array with [natoms, 3, 1] dimensions?

**Comment by hainm** [comment]
Oops, 2d n_atoms, 3

**Comment by arose** [comment]
> @arose: I am fine with making a release now. So it's up to you.

Sounds great, I will do some testing of my own and then do a release as soon as possible. There are indeed a lot of improvements. Thank you! I am also ok with calling it 1.0 though if we do so we should be extra diligent with testing.

**Comment by kain88-de** [comment]
I would appreciate a new release. The current release isn't working in Firefox 50 but the current git/master is.

**Comment by arose** [comment]
yes, yes, plan to do it this afternoon, thanks for the reminder

**Comment by arose** [comment]
@hainm can I use the current master for the release? will test myself but you know best!

**Comment by hainm** [comment]
Yes

Hai

**Comment by hainm** [comment]
> should we bump to 1.0? ipywidgets seems to be stable now.

I change my mind. Too many issues with compatibility (ipywidgets, notebook, jupyterlab). So I think `v0.6` is fine.

**Comment by hainm** [comment]
Hi all,

`nglview v0.6.1` is released now (pypi, conda)
Please check the (new) install info here and let us know if there is any issue. thanks

https://github.com/arose/nglview#released-version

**Comment by gph82** [comment]
Hi guys, I know the issue is closed and this question might be cleared elswhere, but why is the conda version of nglview 9.4?
https://anaconda.org/omnia/nglview
omnia / packages / nglview 0.4

**Comment by hainm** [comment]
Hi we are using bioconda channel.
