### ISSUE TITLE
IPython console support

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#510]
I was wondering if you could do something like [bokeh](http://bokeh.pydata.org/en/latest/) does.
It's a JS plotting library for python. But if you run it from ipython console and plot something it opens up a browser with your plot in it.

That way we would not be bound to using jupyter notebooks and could totally replace VMD as a viewer in the future.

**Comment by arose** [comment]
[mdsrv](http://arose.github.io/mdsrv/) lets you run ngl standalone. It would be nice to reuse the GUI between ngl, mdsrv, nglview.

I agree that it would be nice to start a ngl viewer standalone (in the browser) from any python process. Just starting a viewer is fairly straightforward, allowing bidirectional communication is much more involved.

**Comment by hainm** [comment]
it would be nice to have but we need to think about the design a bit.

- First, there is `mdsrv` package that does not require Jupyter notebook: [mdsrv](https://github.com/arose/mdsrv). I made [a fork](https://github.com/Amber-MD/mdsrv) to work with [pytraj](https://github.com/Amber-MD/pytraj) but it's trivial to add more backends (for those interested).
`mdsrv` use `NGL` for rendering and `flask` for server. We can add Ipython console but still need to think about implementation like Jupyter notebook, which is like reinventing the wheel.

> That way we would not be bound to using jupyter notebooks

I don't see why we need to not to bound to Jupyter notebook. It's great and evolve nicely. Especially the [Jupyterlab](https://github.com/jupyterlab/jupyterlab) is wonderful. I tried it and very like it. Will intergrate `nglview` when it (lab) is stable.

> could totally replace VMD as a viewer in the future.

I am really doubt about this. Programs like VMD, PyMol, ... is very powerful and they requires years of development with lots of funtionality. I think the strength of `NGL` is to produce very beautiful rendering, high performance, web-based, ... but it still lack of many functions (e.g structure editing, mouse interaction, ...).

**Comment by hainm** [comment]
a demo from `jupyterlab` (what if a `nglview` widget is there).

from: https://github.com/bloomberg/bqplot/pull/324#issuecomment-248959830
![](https://cloud.githubusercontent.com/assets/2397974/18757504/79b067de-80f4-11e6-8c7c-92ac7f7c1e6a.gif)

**Comment by stefdoerr** [comment]
Ok just wanted to throw the idea out there :)

**Comment by hainm** [comment]
yeah, keep throwing. cheers and thanks.

**Comment by hainm** [comment]
@stefdoerr  just FYI: you can connect IPython console with Jupyter notebook too (using `%qtcosole` magic). It's good for using two screens.

![](https://github.com/arose/nglview/raw/1efaa5013ee057724f3255ac13e1b01aa124e012/examples/images/two_screens.png)
