### ISSUE TITLE
camera orientation of viewer

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#511]
I was wondering why you are viewing down the z axis (or viewing the x-y plane) in nglviewer.
I find it more intuitive the way VMD does it viewing the x-z plane. Especially since most membrane systems are typically built with the membrane on the x-y plane and z positive looking up.
So every time I build a membrane system I need to rotate all the way around to see my molecule.

Is there maybe an option for changing the default camera orientation?

**Comment by hainm** [comment]
> I find it more intuitive the way VMD does it viewing the x-z plane. Especially since most membrane systems are typically built with the membrane on the x-y plane and z positive looking up. 

agree. 

> Is there maybe an option for changing the default camera orientation?

@arose

**Comment by arose** [comment]
> Is there maybe an option for changing the default camera orientation?

I will look into changing the default to look down the x or y axis instead of the z axis. Should be straightforward (https://github.com/arose/ngl/issues/230).

There is also the axis representation with has an align method (`repr.align()`) to orient everything based on the principal axes of the selection (see http://arose.github.io/ngl/).

The camera model in ngl needs a rewrite, but after I have done that I want to provide an API to do changed the view/orientation in any way you like.

**Comment by hainm** [comment]
@arose what's the syntax for changing different view with 0.10.0-dev8 NGL?

same question for `nglview`: https://github.com/arose/nglview/issues/596#issuecomment-288601065

**Comment by arose** [comment]
the API is described here http://arose.github.io/ngldev/api/ViewerControls.html

have a look at `.getOrientation` and `.orient`

**Comment by arose** [comment]
Here is how to change the view to look at the y-z plane:

```
var m = new NGL.Matrix4().makeRotationX( Math.PI / 2 );
var q = new NGL.Quaternion().setFromRotationMatrix( m );
stage.viewerControls.rotate( q );
```

Is that good for you @stefdoerr?

**Comment by hainm** [comment]
Note: This is `nglview` :)) 

I guess we just need to pass python list (len=16) to `view.control.rotate(q)`?

**Comment by arose** [comment]
almost, `.rotate` takes a quaternion (len=4)

**Comment by hainm** [comment]
I thought you did allow Array? 

https://github.com/arose/ngl/commit/0d383a5701c83d3aa11348989b8740c897769e91

**Comment by arose** [comment]
yes, the array for a quaternion is of length 4

**Comment by hainm** [comment]
I see, something like [1, 2, 3, 4] :D

**Comment by kain88-de** [comment]
MDAnalysis includes a transformation library that can convert rotation matrices to quaternions. I'll have time to check it next week.

@arose. What convention are you using for the quaternions? Where is the scalar saved and where the ijk variables?

**Comment by stefdoerr** [comment]
@arose thanks! I'll take a look

**Comment by hainm** [comment]
> I find it more intuitive the way VMD does it viewing the x-z plane. 

@arose 

Naive question: what's the exact number to pass to `view.control.rotate(...)` in this case? :D

**Comment by arose** [comment]
```
var m = new NGL.Matrix4().makeRotationX( Math.PI / 2 );
var q = new NGL.Quaternion().setFromRotationMatrix( m );
stage.viewerControls.rotate( q );
```

**Comment by stefdoerr** [comment]
This is not released yet on conda, right? Just on github

**Comment by hainm** [comment]
not yet.
