### ISSUE TITLE
Atom selections with index

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#512]
I used to use `@0,1,2` to select atoms with indexes 0,1,2. But from [what I see](http://arose.github.io/ngl/api/tutorial-selection-language.html) this is not supported anymore?

I needed this to convert from the VMD atomselection language to NGL selections because an exact translation between the two is impossible, so the best solution was to go VMDsel -> indexes -> NGLsel

**Comment by stefdoerr** [comment]
Ah no still seems to work. I'm mucking up something else. Sorry for the false alarm

**Comment by stefdoerr** [comment]
Well it's not in the docs. You might want to add it

**Comment by hainm** [comment]
```python
view.add_cartoon(selection=range(100)
# or any 1D array should also work too
```

**Comment by hainm** [comment]
`nglview` doc: http://arose.github.io/nglview/dev/api.html?highlight=add_representation#nglview.NGLWidget.add_representation

**Comment by arose** [comment]
> I used to use @0,1,2 to select atoms with indexes 0,1,2. But from what I see this is not supported anymore?

was never documented :-) good point

**Comment by arose** [comment]
added documentation, see https://github.com/arose/ngl/commit/371f4d9ae677ff7df57d8752b328d08a951aacee
