### ISSUE TITLE
'atomindex' color doesn't work sometimes

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#513]
I have a case where if I choose 'atomindex' color in a representation I don't see anything in the viewer, yet with 'residueindex' it works.

```python
# shows nothing
viewer.representations = [{'params': {'color': 'atomindex', 'sele': '@'+','.join(map(str, range(2000)))}, 'type': 'ball+stick'}] 

# shows fine
viewer.representations = [{'params': {'color': 'residueindex', 'sele': '@'+','.join(map(str, range(2000)))}, 'type': 'ball+stick'}]
```

Any clue what might be the underlying cause?

**Comment by hainm** [comment]
Please make a simple example so we can reproduce it.

**Comment by stefdoerr** [comment]
Here you go
[test.zip](https://github.com/arose/nglview/files/572540/test.zip)

```python
import nglview
view = nglview.show_structure_file('test.pdb')  # load "3pqr" from RCSB PDB and display viewer widget
view

# nothing
view.representations = [{'params': {'color': 'atomindex', 'sele': '@'+','.join(map(str, range(2000)))}, 'type': 'ball+stick'}] 
# works
view.representations = [{'params': {'color': 'residueindex', 'sele': '@'+','.join(map(str, range(2000)))}, 'type': 'ball+stick'}]  
```

**Comment by hainm** [comment]
thanks. I can reproduce your error and will have a look.

PS: you can shorten your scrip by
```python
view.add_ball_and_stick(selection=range(2000), color='residueindex')
```

**Comment by stefdoerr** [comment]
Good to know :) But I'm doing it programmatically with a dictionary to map VMD representations to NGL ones so it's easier to do it the "hard" way in this case.

**Comment by hainm** [comment]
I see. It's a good idea to add that to `nglview` too. Might go to [py_utils.py](https://github.com/arose/nglview/blob/master/nglview/utils/py_utils.py)

**Comment by hainm** [comment]
@arose can you double-check with `NGL` dev? `atomindex` works with `nv.datafiles.PDB` but does not with @stefdoerr  file.

![atomindex](https://cloud.githubusercontent.com/assets/4451957/20025872/6c13fef0-a2c9-11e6-8d7b-62c0ccb2b611.png)

**Comment by hainm** [comment]
never mind. Upgrading to `0.10.0.-dev.3` does the job.

**Comment by arose** [comment]
ok, thanks (was just testing it :)

**Comment by hainm** [comment]
@stefdoerr fixed in #515. Please give it a try.

**Comment by hainm** [comment]
Can we close this issue?

**Comment by stefdoerr** [comment]
I didn't have a chance to try but sure. If it's still an issue I'll reopen
