### ISSUE TITLE
extend rdkit support to trajectories

### ISSUE THREAD

**Issue by arose** [arose/nglview#516]
new in rdkit, see https://github.com/rdkit/rdkit/pull/863

**Comment by hainm** [comment]
Yeah

**Comment by hainm** [comment]
@arose does it really support 3D structure? If I recall correctly, the z-coordinates are set to 0.

**Comment by arose** [comment]
hmm, I don't know

**Comment by hainm** [comment]
anyone has a minimal example of rdkit's Trajectory? It's like entering a maze when reading its API docs. :(

**Comment by hainm** [comment]
uhm, I've looked at rdkit's Trajectory test cases and I admit I don't understand how to use it in the context of nglview.
