### ISSUE TITLE
Grid of nglviewers

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#517]
Is it possible to make a grid of nglviewers?
I tried it like this:

```python
import ipywidgets
import nglview
from IPython.display import display
view = nglview.show_structure_file('test.pdb')
hb = ipywidgets.HBox((ipywidgets.VBox((view,)),ipywidgets.VBox((view,))))
display(hb)
```

but with no success

**Comment by hainm** [comment]
Should work. What do you mean 'no success'?

**Comment by stefdoerr** [comment]
Doesn't display anything. Seems to be squeezing it all to the left of the screen

![untitled](https://cloud.githubusercontent.com/assets/7935362/20041161/96a20052-a465-11e6-9965-53f47f5ae7aa.png)

**Comment by hainm** [comment]
Can you try

Hbox([view0, view1])? 

I think nglview does not work with your nested box yet due to some technical difficulties.

**Comment by stefdoerr** [comment]
Ok that works but it needs some manual resizing to fit them both into the screen. I will look more into it later.

**Comment by hainm** [comment]
@stefdoerr you can try `BoxNGL`

```python
vb = nv.show_mdtraj(b)
va = nv.show_mdtraj(a)

from ipywidgets import HBox
from nglview.widget_box import BoxNGL

box = BoxNGL([va, vb])
box
```

check its code for setting widget size: https://github.com/arose/nglview/blob/master/nglview/widget_box.py

(note: unstable API)

**Comment by hainm** [comment]
I think this can be closed now. Feel free to reopen.
