### ISSUE TITLE
Multiple VMD-like molecules in a single viewer

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#518]
I would love to have something like in VMD where you can enable and disable multiple structure/trajectories in a single viewer.
I know it's probably some work and requires a GUI for switching them on and off.

**Comment by hainm** [comment]
You can check 'show_only' or 'hide' methods.

**Comment by stefdoerr** [comment]
This is coooool! Do I understand correctly that the NGLWidget's representations are inherited by all components? And each component can then have it's own representations?

Also, any reason why your components are not in a list? Looping over them is a bit hacky now. 
```python
for i in range(100):
    compname = 'component_{}'.format(i)
    if compname in view.__dict__:
        print(view.__dict__[compname])
```

I see that even you internally loop over them in a bit of an ugly manner.

**Comment by hainm** [comment]
Either use

view[0] 

Or view.component_0

**Comment by hainm** [comment]
I will reply to other comments later since using phone.

**Comment by stefdoerr** [comment]
ok, no worries, this is really helpful

**Comment by arose** [comment]
> Do I understand correctly that the NGLWidget's representations are inherited by all components?

Each NGL component (think file) can have as many representations and trajectories as you like. They can all be controlled independently. Thanks to @hainm it also works in NGLWidget :-)

**Comment by stefdoerr** [comment]
Great!

Sorry to bother you so much but I'm having a bit of trouble loading two separate trajectory/structure pairs as separate components.

```python
import mdtraj as md
a = md.load('./MiniProject/filtered/e1s1_0/output.filtered.xtc', top='./MiniProject/filtered/filtered.pdb')
b = md.load('./MiniProject/filtered/e1s2_0/output.filtered.xtc', top='./MiniProject/filtered/filtered.pdb')

from nglview import NGLWidget
view = NGLWidget()
view.add_trajectory(a)
view.add_trajectory(b)
view
```
This shows a white box with a slider
So I thought maybe I'm missing the structure and I tried this:

```python
view = NGLWidget()
view.add_trajectory(a)
view.add_structure(nglview.FileStructure('./MiniProject/filtered/filtered.pdb'))
view
```

This also gives a white box with a slider

```python
x = nglview.show_mdtraj(a)
x
```
This works perfectly fine.

So I'm missing something here. Ideally I would want to be able to load different trajectory/structure pairs, switch them on and off with the show/hide component and hopefully use the slider to loop throught the shown trajectory's frames.

**Comment by hainm** [comment]
Can you post pdb file with few frames of xtc file?

Hai

**Comment by stefdoerr** [comment]
[filtered.zip](https://github.com/arose/nglview/files/574126/filtered.zip)

**Comment by hainm** [comment]
ok, so the `show_xxx` and `add_trajectory` uses different type of representations. 

You can try to add:
```python
view.clear()
view[0].add_line()
view[1].add_licorice()
``` and so on.

**Comment by hainm** [comment]
![fireshot capture 57 - tmpnb_ngl - http___localhost_8888_notebooks_tmpnb_ngl ipynb](https://cloud.githubusercontent.com/assets/4451957/20042389/34919e72-a447-11e6-943c-5b9d0d67602f.png)

**Comment by hainm** [comment]
> show_xxx and add_trajectory uses different type of representations.

note for myself: make them consistent.

**Comment by stefdoerr** [comment]
Oh it was that simple. Thanks!

**Comment by hainm** [comment]
cool. Fee free to open new issues.
