### ISSUE TITLE
Visualizing all frames at once

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#520]
Is it possible to visualize all frames of a trajectory at once (without a slider?)?

**Comment by hainm** [comment]
no really convenient to do so yet.

But you can
- save your trajectory to a single pdb with multiple models.
- use `show_structure_file`

e.g: 
![model](https://cloud.githubusercontent.com/assets/4451957/20060246/4459df50-a4c8-11e6-8028-a3d40c51e42c.png)

**Comment by stefdoerr** [comment]
Yes ok that's what I was doing. It's just that it was causing problems in the viewer if I didn't add TER's between each model. Now it's fine.

**Comment by arose** [comment]
also created a related NGL issue: https://github.com/arose/ngl/issues/231

**Comment by hainm** [comment]
@arose just remind that `nglview` does not use `NGL` Trajectory. The `Structure` coordinates is updated frame by frame.

**Comment by arose** [comment]
> @arose just remind that nglview does not use NGL Trajectory. The Structure coordinates is updated frame by frame.

good point, thanks
