### ISSUE TITLE
nglview changes chains of molecules

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#521]
[test.zip](https://github.com/arose/nglview/files/575346/test.zip)
```python
import nglview
view = nglview.show_structure_file('./test.pdb')  # load "3pqr" from RCSB PDB and display viewer widget
view
```
If you click on one of the ligands it gives chain X instead of chain 1,2,3,4

**Comment by stefdoerr** [comment]
ok so adding a TER between the ligands and the protein fixes this issue

**Comment by stefdoerr** [comment]
[test.zip](https://github.com/arose/nglview/files/575437/test.zip)

**Comment by arose** [comment]
hmm, your test file without TER lines works ok for me at http://arose.github.io/ngldev/
