### ISSUE TITLE
warning about installed widget javascript version isn't very helpful

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#530]
With the master branch I'm getting an error that I've installed the wrong widget version. It would be nice if the message also said what version is currently installed and what version was expected.

**Comment by hainm** [comment]
We have no control with that. That comes from notebook + ipywidgets.

**Comment by hainm** [comment]
the ipywidgets version from conda-force seems work for me

```
conda install ipywidgets -c conda-forge
```

**Comment by hainm** [comment]
so I always got that type of errors and seems annoying. This was what I did 

- remove `widgetsnbextension` package
```bash
rm -rf /path/to/lib/python3.5/site-packages/widgetsnbextension*
```

- Install ipywidgets and notebook from `conda-forge` chanell
```bash
conda install ipywidgets -c conda-forge
conda install notebook -c conda-forge
```

- remove all stuff in 
```bash
rm -rf .local/share/jupyter
```

- reinstall `widgetsnbextension`
```bash
pip install widgetsnbextension
```

(such a pain).

**Comment by kain88-de** [comment]
Hm I thought I had the most recent ipywidgets installed. I'll try your suggestions thanks.

**Comment by hainm** [comment]
probably you install something else that downgrade `ipywidgets`.

**Comment by kain88-de** [comment]
That was actually a new conda environment specifically to test the master branch. But maybe jupyter doesn't like that I use it in a number of different conda environments with different versions.
