### ISSUE TITLE
Nothing rendered, no errors

### ISSUE THREAD

**Issue by scbarton** [arose/nglview#532]
I have the development version installed, and I am unable to render but no errors are shown.  The code I'm running is:
```
import nglview as nv
vpdb = nv.show_pdbid("3pqr")
vpdb
```

I'm using the latest Safari and Mac OS and running Jupyter on localhost. Any suggestions to troubleshoot this?

**Comment by hainm** [comment]
can you post

```python
print(ipywidgets.__version__)
```

and post your notebook screen too? thanks

**Comment by scbarton** [comment]
After your suggestion, I checked my `ipywidgets` version, which was 5.2.2. However I also checked my `nglview` version, which was 5.1. 

After `pip uninstall nglview`, and then reinstalling the development version, the `nglview.__version__` returned `0+unknown` and everything worked- I was able to render the protein.  Thanks!

**Comment by hainm** [comment]
great. We probably should add `ipywidgets` version checking.
