### ISSUE TITLE
images not loading

### ISSUE THREAD

**Issue by evohringer** [arose/nglview#535]
Hi,

I downloaded version 0.5.2 over conda and it is installed with ipywidgets 5.2.2 on Mac OS X. 
Unfortunately the images are not displayed in safari.

Maybe you can help me out.

Thanks,

Esteban

**Comment by hainm** [comment]
hi @evohringer 

`nglview 0.5.2` requires `ipywidgets < 5.0`. So you have three options

- Keep `nglivew 0.5.2` and downgrade `ipywidgets`
- Keep `ipywidgets 5.2.2` and install github version.
- Wait a day until `bioconda` finish [nglview 0.6 build](https://github.com/bioconda/bioconda-recipes/pull/3046)

Please see related issue #532

**Comment by hainm** [comment]
`nglview v0.6.1` is available now. Please check
https://github.com/arose/nglview#released-version

**Comment by hainm** [comment]
it's been 10 days and I assume this issue is resolved. close and cheers.
