### ISSUE TITLE
Representations before viewing are ignored

### ISSUE THREAD

**Issue by stefdoerr** [arose/nglview#537]
in my function I'm doing:
```python
def foo():
        #code here
        view[0].add_cartoon('protein')
        view[0].add_hyperball(':0')
        return view
```

These representations are not shown. 

But if I do them afterwards, they are shown:
```python
view = foo()
view
view[0].add_cartoon('protein')
view[0].add_hyperball(':0')
```

```bash
[sdoerr@loro ~]$ python -c 'import nglview; print(nglview.__version__)'
0.6.1
[sdoerr@loro ~]$ python -c 'import ipywidgets; print(ipywidgets.__version__)'
5.2.2
[sdoerr@loro ~]$ python -c 'import traitlets; print(traitlets.__version__)'
4.3.1
```

**Comment by stefdoerr** [comment]
Example: [test0.zip](https://github.com/arose/nglview/files/611090/test0.zip)

```python
def foo():
    import nglview
    from nglview import NGLWidget, HTMDTrajectory
    view = NGLWidget()
    view.add_trajectory(HTMDTrajectory(Molecule("/tmp/test0.pdb")))
    view[0].add_cartoon('protein', color='sstruc')
    return view
view = foo()
view
```
Doesn't show sstruc colors. If you call the add_cartoon afterwards it does.

**Comment by stefdoerr** [comment]
Apparently it randomly applies the correct color some times. I would say around 5% of the tries.

Tried also with mdtraj to the same effect
```python
def foo():
    import nglview
    from nglview import NGLWidget, HTMDTrajectory
    import mdtraj as md
    a = md.load('/tmp/test0.pdb')
    view = NGLWidget()
    view.add_trajectory(a)
    view[0].add_cartoon('protein', color='sstruc')
    return view
view = foo()
view
```

**Comment by hainm** [comment]
this is very tricky and I don't now how to fix. The point is if you do not display `view`, it would not be created, then actions (add_...) performed on it would never executed correctly. Interally, nglview uses a callback list to store those "actions" and fire them when the view is displayed. Most of the time it works but ...

related issue here: https://github.com/arose/nglview/issues/328

So my suggestion is  
- display the view first
- write a function to change its behaviour and call it after the view is displayed.

I will leave this issue open in case there is a fix for it.

**Comment by hainm** [comment]
e.g

```python
def foo(view):
        view.clear()
        view[0].add_cartoon('protein')
        view[0].add_hyperball(':0')

# display
view

# update view in another cell
foo(view)

**Comment by stefdoerr** [comment]
Quite ugly from a user perspective of our software though :disappointed:  We don't want them to worry about such low-level details and calling another function to change the reps is kind of impractical :/ 
What makes this random though? Sounds like a bug no?

**Comment by hainm** [comment]
you can look at the source code here and make a PR if you can solve this.

https://github.com/arose/nglview/blob/master/nglview/widget.py#L285-L291

**Comment by hainm** [comment]
> What makes this random though?

I don't know.

**Comment by stefdoerr** [comment]
Weird weird stuff. I see 6 callbacks registered so I tried:
```python
[callback(view) for callback in view._ngl_displayed_callbacks]
```
Which for a brief second enables the sstruc colors and then disables them again. But the sstruc callback is actually the last one (I checked). So it should be applied last. Then I split the for loop in separate commands to play around
```python
view._ngl_displayed_callbacks[0](view)
view._ngl_displayed_callbacks[1](view)
view._ngl_displayed_callbacks[2](view)
view._ngl_displayed_callbacks[3](view)
view._ngl_displayed_callbacks[4](view)
view._ngl_displayed_callbacks[5](view)
```
I tried removing callbacks but removing 0-3 still gives wrong color
```python
view._ngl_displayed_callbacks[4](view)
view._ngl_displayed_callbacks[5](view)
```
Removing callback 4 even if I keep the rest gives me the correct coloring! So callback 4 is the evil guy.

So calling 4 before 5 gives wrong colour but calling 5 in a separate jupyter cell works though!!!
```python
# Cell 1 :  Doesn't work
view._ngl_displayed_callbacks[4](view)
view._ngl_displayed_callbacks[5](view)
# Cell 2 :  Works!!!
view._ngl_displayed_callbacks[5](view)
```

So what is going on here? I would assume it has to do with sending commands to the JS viewer. Could it be @arose that the commands are put in some buffer and then executed in a possibly random order?

**Comment by hainm** [comment]
It is good to know what 4 is

Hai Nguyen

**Comment by hainm** [comment]
I see the issue now.

So the 4th is 'loadFile' and the 5th is 'addRepresentation'. Since `loadFile` is async, the 5th action should wait for that but it never waits. It means the 5th will applied to empty view (without any structure). This can be fixable but still need to read the JS code first.

**Comment by hainm** [comment]
my thought is to send `loadFile` to `NGL`, if loaded, then `NGL` sends message back 'ok, fire next command', if `nglview` get that (ok) message, it will execute the next command. This will works for @stefdoerr case.

However, if `view` is already loaded and then 

```python
# those two are in the same cell
view.add_trajectory(...)
view[-1].add_licorice(...)
```
might not work if the `add_trajectory(...)` is not yet finished.

**Comment by hainm** [comment]
@stefdoerr I made a fix in `remote_calls` and it works for your example. However, that branch breaks other things (can not display `view` twice).

**Comment by stefdoerr** [comment]
Thanks for looking into it! I'll be out till next Tuesday. Will check then.

**Comment by hainm** [comment]
I made another PR and merge to master anyway. Check the notebook here:
https://github.com/arose/nglview/blob/master/nglview/tests/notebooks/api/test_callbacks.ipynb

**Comment by arose** [comment]
Thanks @hainm! Waiting for a file to finish loading is crucial.

For representations there is one parameter that may help handling representations: "lazy: only build & update the representation when visible otherwise defer changes until set visible again".

**Comment by hainm** [comment]
you meant
```python
view.add_surface(lazy=True, visible=False)
```

then 
```python
view.update_cartoon(visible=True)
```

**Comment by arose** [comment]
yes

**Comment by hainm** [comment]
ok, so just use `lazy=True` as default.

**Comment by arose** [comment]
that's an option, would be good to test a bit before

**Comment by hainm** [comment]
> that's an option, would be good to test a bit before

yeah.

**Comment by stefdoerr** [comment]
Sorry to bother Hai. Just wanted to ask if this blocking call has been released in the last nglview release you made.

**Comment by hainm** [comment]
Yeap

**Comment by stefdoerr** [comment]
Great! I'll test it next week :)
