### ISSUE TITLE
wrong representation

### ISSUE THREAD

**Issue by hainm** [arose/nglview#54]
Do  you know why?

- nglview

![nglview_wrong](https://cloud.githubusercontent.com/assets/4451957/14367619/fd8d6efe-fce6-11e5-87c0-09aa6390e415.png)

- vmd

![snap](https://cloud.githubusercontent.com/assets/4451957/14367646/2c1b2a2c-fce7-11e5-9f1a-2ba4c0b59285.png)

pdb file: https://github.com/hainm/amber_things/tree/master/things/nglview/issue

**Comment by hainm** [comment]
Please ignore the commands in the notebook (due to copy and paste)

```python
import warnings
warnings.filterwarnings('ignore')
import pytraj as pt
import nglview as nv

traj = pt.load('single.pdb')
view = nv.show_pytraj(traj)
view.add_representation('surface')
view
```

**Comment by arose** [comment]
Looks like an error with the index of the surface mesh. I remember fixing some bugs in the dev branch.

**Comment by arose** [comment]
Looks ok in the ngl dev branch. I was thinking about updating nglview after the next [ngl release](https://github.com/arose/ngl/milestones/0.7)

![screenshot 26](https://cloud.githubusercontent.com/assets/272250/14414008/8b94b18a-ff3f-11e5-8ab6-4bad2fac6144.png)

**Comment by hainm** [comment]
do you have time line for this? 

also, can you tell me how to update from ngl to nglview?

just:

```bash
- cd ngl/build
- ./make.sh
- cp ../js/build/*.js /to/nglview/nglview/html/static
```

**Comment by hainm** [comment]
I asked because I need to visualize 45 proteins *  500-1000 conformations. And the cluster I am using does not allow to use VMD :)).
