### ISSUE TITLE
Parameter setting before viewing (or how to change the default values?)

### ISSUE THREAD

**Issue by yqshao** [arose/nglview#554]
# Discription
Thanks first for the great widget, I tried to integrate it with ASE and it worked quit well.
Here's some feature that I'm not very clear about. 
I tried to customize some settings for the view such as `clipDepth` ,`quality`..., however, setting the parameter only works if I excute it in the following cell, for example, this won't work:
```python 
import ase
import vasp
import nglview
model=ase.io.read('POSCAR')
view=nglview.show_ase(model)
view.clear_representations()
view.add_spacefill(radius_type='vdw',scale=0.7)
view.add_unitcell()
view.displayed=True
view.parameters = {"backgroundColor": "black"}
view
```
Therefore, it seems hard for me to 'generate' a desired widget.
Correct me if I use the widget the wrong way, but is there any way to set a "default parameter" or change it befor a widget is shown?

# Version report
```bash
python -c 'import nglview; print(nglview.__version__)'
0.6.2.1+11.gccbf561
python -c 'import ipywidgets; print(ipywidgets.__version__)'
5.2.2
python -c 'import traitlets; print(traitlets.__version__)'
4.3.1
```

**Comment by hainm** [comment]
hi,

that's limitation of current implementation. We will fix that and ping you later. Thanks.

**Comment by hainm** [comment]
related to https://github.com/arose/nglview/issues/537

**Comment by hainm** [comment]
fixed in #555 

Please give it a try.

![parameters](https://cloud.githubusercontent.com/assets/4451957/21753520/ecf80702-d5bc-11e6-99d4-a3f45fefc97b.png)

**Comment by yqshao** [comment]
![notebook](https://cloud.githubusercontent.com/assets/22888066/21761120/e47e2988-d68b-11e6-9e11-a894d7833d50.png)
Cool, just exited to show how this could help in my workflow,
and thanks again for this fix.

There might be some undesired behavior though,  for example, when I used this combined layout, cell didn't show up in the first row. And the default orientation issue mentioned in #511. But I think the parameter setup is fine now.👍

**Comment by hainm** [comment]
cool. Feel free to make a PR for user example [here](https://github.com/arose/nglview/blob/master/examples/user_examples.md)
