### ISSUE TITLE
Render Image at specific orientation and size

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#559]
I'm writing a notebook to prepare figures for publication. I don't like the image size or orientation that nglview choses by default. Is there a way to set the view orientation and size before it's shown?

Also can I read the current orientation after I set an image the way I like it?

# Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
python -c 'import traitlets; print(traitlets.__version__)'
```
0.6.2.1
5.2.2
4.3.1

# Note:
Please always double-check install guide here: https://github.com/arose/nglview#released-version

**Comment by hainm** [comment]
there is no pleasure way to do that but you can use `orientation` to get and set.

1st cell
```bash
view._set_sync_camera()
```

2nd cell
```bash
view.orientation 
```

![orientation](https://cloud.githubusercontent.com/assets/4451957/21813563/b32508b8-d724-11e6-969d-f3ce551aaee5.png)

**Comment by hainm** [comment]
related to https://github.com/arose/nglview/issues/511

ping @arose

**Comment by kain88-de** [comment]
This seems to answer the question of the zoom. I would also like to change the figure size (width height) automatically. Right now I have to manually change the size of the widget everytime it's drawn.

**Comment by hainm** [comment]
Please check the example in very end of #554

Hai Nguyen

**Comment by kain88-de** [comment]
Ok this fixed everything except for the zoom. But here `center_view()` seems to do the trick
