### ISSUE TITLE
Add button to freeze frame and store current image in NB

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#563]
It would be nice if there was a button to embed the current shown frame in the notebook. Then I can reopen notebooks and still see the image I used last time. This would be similar to `nbagg` backend freezing feature from matplotlib.

# Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
python -c 'import traitlets; print(traitlets.__version__)'
```

0.6.2.1
5.2.2
4.3.1

**Comment by hainm** [comment]
Thanks. We will keep this in mind.

**Comment by hainm** [comment]
uhm, but note that `Widget` is not static. I am not sure if freezing will work for `nglview`. The easiest way is to
set frame `view.frame = something` and `view.orientation=...`.

**Comment by kain88-de** [comment]
Is it not possible to replace the widget with a png dynamically?

**Comment by hainm** [comment]
No it's not, AFAIN.

If possible, that should be done in `ipywidgets`.

**Comment by hainm** [comment]
I close since this really depends on `ipywidgets` and out of our control.
