### ISSUE TITLE
cache coordinates

### ISSUE THREAD

**Issue by hainm** [arose/nglview#58]
I just visited bokeh project and they are still looking solution to send data to JS. 
while waiting solution, I come up with dirty hack: trying to send all coordinates to JS side.

https://github.com/bokeh/bokeh/issues/2204

- first, we dont need to sync 'coordinates' between Python and JS. too slow.

- in Python, call 
```python
view.send({'type': 'coordinatesdict', 'data': view.trajectory.get_coordinate_dict()})
```

- in JS, create `on_msg` function to receive the message.

```javascript
            // get message from Python
       this.coordinatesdict = undefined;
       this.model.on( "msg:custom", function (msg) {
                    this.on_msg( msg );
       }, this);

        on_msg: function(msg){
            if ( msg.type == 'call_method' ){
                 ...
            }else if( msg.type == 'coordinatesdict'){
                this.coordinatesdict = msg.data;
                console.log ( "received coordinatesdict" );
            }
        }
```

if frame changed
```javascript
        frameChanged: function(){
            var frame = this.model.get( "frame" );
            var coordinates = this.coordinatesdict[frame];
            var component = this.structureComponent;
            if( coordinates && component ){
                var coords = new Float32Array( coordinates );
                component.structure.updatePosition( coords );
                component.updateRepresentations( { "position": true } );
            }

        },
```

I have not done benchmark yet but this should be much faster than sending coordinates from Python to JS every time frame changed.

**Comment by hainm** [comment]
Question: Why do we really need to sync `coordinates` originally?

**Comment by hainm** [comment]
a proposed PR here: https://github.com/arose/nglview/pull/59/files

normally implementation by syncing `coordinates`

```python
view = nv.show_pytraj()
view
```

turn cache on
```python
view.caching()
```
--> fast

want to sync `coordinate` again?
```python
view.uncache()
```

**Comment by hainm** [comment]
potential: let user to choose specific frames to cache. This is good for pytraj and MDAnalysis out-of-core trajectory/universe. User only need to load coordinates from disk to JavaScript once when `caching` is called.

**Comment by hainm** [comment]
tried with 13008 atoms (DNA + waters). caching is dramatically faster.

**Comment by hainm** [comment]
New issue: sending 30 MB data from Python to JS via `Widget.send` is really slow, costs me 16 s. ack.

**Comment by hainm** [comment]
so two seperate issue:

- how to send a GB of data from Python to JS within seconds?
- how to use binary data?

for trajectory viewer, non-lagging viewing is important (at least for me).

**Comment by hainm** [comment]
timing: sending `list` and `bytes` via `Widget.send` method

```python
print(traj.xyz.shape, traj.xyz.dtype)

xyz = traj.xyz.flatten()

xyz_list = xyz.tolist()

xyz_bytes = xyz.tobytes()

(100, 5293, 3) float64

%%time
view.send(xyz_list)

CPU times: user 10.2 s, sys: 77 ms, total: 10.3 s
Wall time: 10.3 s

%%time
view.send(xyz_bytes)

CPU times: user 1.73 s, sys: 247 ms, total: 1.98 s
Wall time: 1.95 s
```

sending bytes is 5 times faster than sending list but still slow (1.95 s for 100 frames, 5293 atoms).

**Comment by hainm** [comment]
from my benchmark, sending a dict of base64 data is 100 times faster than sending a Python list.

I am going this way.

**Comment by kain88-de** [comment]
Out of curiosity when you send GB of data from python to js is that data copied?

**Comment by hainm** [comment]
> Out of curiosity when you send GB of data from python to js is that data copied? 

Yes. But this should not be a problem for out-of-core back-end like MDAnalysis. Coordinates are only copied once when 'caching' is called and those are kept in memory (JS) for fast iteration.

But ideally, I just want Python and Javascript can share memory view, just like Python and C/C++.

**Comment by kain88-de** [comment]
You could ask on the jupyter mailing list if they know a method to do that.

**Comment by hainm** [comment]
- bokeh still have an open issue about DataView ans Python/JS stuff. :D 
https://github.com/bokeh/bokeh/issues/2204

So I guess there is not.

**Comment by arose** [comment]
> But ideally, I just want Python and Javascript can share memory view, just like Python and C/C++.

That is not going to happen, ever! At least not between a browser and Python. The browser is a sandbox for security reasons, so there will be no memory sharing.

**Comment by hainm** [comment]
>  That is not going to happen, ever! At least not between a browser and Python. The browser is a sandbox for security reasons, so there will be no memory sharing.

yeah, right. So my work here is still useful. =)) https://github.com/arose/nglview/pull/67

**Comment by hainm** [comment]
@kain88-de  @dotsdl I just update MDA support in my new PR.

Let me know if the view play is reasonably fast or not. 

PR: https://github.com/arose/nglview/pull/67

should check branch: https://github.com/hainm/nglview/tree/on_msg_f32

That branch includes notebook test for MDA too, just run it.

![](https://raw.githubusercontent.com/arose/nglview/28a583ab36bc31793722e130425cbf383c685358/nglview/tests/notebooks/test_mda_analysis.png)

The speed can be still improved (see @arose comment in that PR).

**Comment by hainm** [comment]
note: if using `view.caching()` the viewer play is much smoother.

**Comment by hainm** [comment]
done. Problem left is sending binary data.
