### ISSUE TITLE
"Could not create model" & wrong javascript version

### ISSUE THREAD

**Issue by ctk3b** [arose/nglview#583]
I've been having an issue with the notebook widget recently and google is failing me. Have you seen this particular issue before?

<img width="1102" alt="screen shot 2017-02-26 at 8 25 29 pm" src="https://cloud.githubusercontent.com/assets/3527431/23346683/0deac6a4-fc62-11e6-8f70-d0a251c7efb8.png">

# Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
python -c 'import traitlets; print(traitlets.__version__)'

0.6.2.2
5.2.2
4.3.1
```

**Comment by hainm** [comment]
Hi yes I saw this warning many times. That's the bug in ipywidgets, so we can just live with it. :d

**Comment by hainm** [comment]
Oh wait, I saw the red warning before but have not seen others. Sounds like relating to the notebook too.  Nothing we can do right now.

**Comment by hainm** [comment]
Using the master branch probably gets rid of the proxy error.

**Comment by ctk3b** [comment]
I've tried both with master and the conda install :(

Do you know the root cause? Anything worth reading about/trying to fix or do we just have to wait for some upstream fixes?

**Comment by hainm** [comment]
We just need to wait. :d

**Comment by hainm** [comment]
PlaceProxy stuff was removed in #586 while the "wrong version" is due to `ipywidgets`. 

close now. Do feel free to open others.

thanks.

**Comment by hainm** [comment]
another related issue: https://github.com/ipython/ipywidgets/issues/1211
