### ISSUE TITLE
PlaceProxy removed from ipywidgets

### ISSUE THREAD

**Issue by ctk3b** [arose/nglview#584]
The latest ipywidgets update [removed `PlaceProxy`](https://github.com/ipython/ipywidgets/blob/4d60e08a6b75dab0604ef00f8f3713fb5ee0d4d3/docs/source/changelog.md) which nglview currently still imports.

See https://github.com/arose/nglview/pull/481 and https://github.com/ipython/ipywidgets/commit/4aeb918d6d6852dc0196776146627a52aab6abfd

**Comment by hainm** [comment]
Thx. I will fix it.

**Comment by hainm** [comment]
Ah pr is welcome.

**Comment by hainm** [comment]
done.

**Comment by hainm** [comment]
thanks for reporting @ctk3b

**Comment by hainm** [comment]
related: https://github.com/ipython/ipywidgets/issues/662
