### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by elkfirmanda** [arose/nglview#585]
Hi, I just followed instruction on tutorial `http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_notebook/`, but I get this on display 
<img width="1186" alt="screen shot 2017-03-03 at 00 34 01" src="https://cloud.githubusercontent.com/assets/11868070/23519463/8b95794c-ffa9-11e6-8aba-cfda5f632bb9.png">
can you help me how to solve this ?

**Comment by hainm** [comment]
You need to type

view

to display the viewer first

view = nv.show_pytraj(...)
view

Hai

**Comment by hainm** [comment]
Let's close this but do feel free to reopen if you are still not able to display the image.

**Comment by hl2500** [comment]
Hello, I still cannot show the image when I applied the code from the tutorial.
<img width="1006" alt="Screen Shot 2020-04-01 at 12 14 01 PM" src="https://user-images.githubusercontent.com/49323647/78160707-51460c80-7412-11ea-9494-a7517d6382c4.png">

**Comment by hainm** [comment]
hi @hl2500, it seems you're using `jupyterlab`. 
Please try with traditional notebook first since it's simpler.

Per `lab`, make sure you run additional commands:
(https://github.com/pyiron/pyiron/blob/master/binder/postBuild)
```
# ngl view for jupyter lab
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install nglview-js-widgets
```

**Comment by hl2500** [comment]
Thank you for the reply! I was actually using jupyter notebook which comes with anaconda. I changed the theme style to look more comfortable... Does this have something to do with the image visualization?

**Comment by hainm** [comment]
> Does this have something to do with the image visualization?

I see. No this does not. 

Have you tried this yet? https://github.com/arose/nglview#released-version

> might need: jupyter-nbextension enable nglview --py --sys-prefix

**Comment by hl2500** [comment]
I just tried this command and it says: 
```
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK
```
Then I restarted the notebook, I can visualize the structure now. Thank you!
