### ISSUE TITLE
traitlets declarations should use Integer instead of Int to support Python 2.7 (win)

### ISSUE THREAD

**Issue by marscher** [arose/nglview#587]
nglview:             0.6.2.2-py27_1           omnia
ipywidgets:          5.2.2-py27_1                      
traitlets:           4.3.2-py27_0                  

Python 2.7 distinguishes between long and int. The traitlets library handles this case automatically by the Integer class (rather than Int), eg. https://traitlets.readthedocs.io/en/stable/trait_types.html?highlight=long#traitlets.Integer

Currently the Widget class uses Int, which leads to the following error on Python-2.7 (windows): https://ci.appveyor.com/project/gph82/molpx/build/1.0.38/job/45vglurnjx53oy8p#L1121

**Comment by marscher** [comment]
cc @gph82

**Comment by hainm** [comment]
Can you post the error here? It's hard to see there by phone (and for archiving).

**Comment by marscher** [comment]
TraitError: The 'count' trait of a NGLWidget instance must be an int, but a value of 7L <type 'long'> was specified.

**Comment by hainm** [comment]
Does this only happens on win? 

(We does have test on linux on travis).

**Comment by marscher** [comment]
On 09.03.2017 18:41, Hai Nguyen wrote:
> Does this only happens on win?
>
> (We does have test on linux on travis).
It seems to happen only on windows

**Comment by hainm** [comment]
uhm there is no way I can test it. :(

how many people are using py2 on win? (or if even using win at all).

**Comment by hainm** [comment]
btw, `mdtraj` guys stop supporting py2 on win. Why do you guys still need to support it?
