### ISSUE TITLE
add view.rotate & view.zoom

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#596]
It would be good to have direct access to orientation and zoom to change them. I'm currently aligning a protein with a specific tensor to view and default orientation of the x,y,z axes is really not working for me in that case.

@arose While this is added. How are the rotation and zoom combined to produce the view.orientation matrix?

# Version report
0.6.2.3
5.2.2
4.3.2

**Comment by arose** [comment]
The necessary functionality has only just been added in the NGL development version. See the `stage.viewerControls` documentation: http://arose.github.io/ngldev/api/ViewerControls.html#orient

The orientation matrix is a 4x4 transformation matrix with rotation part used for scene rotation, scale part for scene camera distance and position part for scene translation.

**Comment by hainm** [comment]
@arose is it possible to pass raw array (e.g: python list, ...) to ViewerControls methods? Python does not understand `three` class (so I need to manually write code for it).

ideally we can `_remote_call` method

```
vector = [1, 2, 3]
view._remote_call('center', target='viewerControls',
args = [vector, ])
```

**Comment by arose** [comment]
yeah, I agree, that would be good

**Comment by arose** [comment]
hmm, this will lead to a ton of extra code that needs to be maintained :-(

**Comment by hainm** [comment]
uhm, may be I just add function to convert python list/array to three's Vector, Matrix.

**Comment by hainm** [comment]
But do you promise that `ViewerControls` will be stable? :))

**Comment by arose** [comment]
wait, I found a way

**Comment by arose** [comment]
see https://github.com/arose/ngl/commit/0d383a5701c83d3aa11348989b8740c897769e91

**Comment by hainm** [comment]
Cool. Public 0.10.8-dev soon?

**Comment by hainm** [comment]
Publish (phone is very smart).

**Comment by arose** [comment]
> Publish (phone is very smart).

???

**Comment by hainm** [comment]
My typos: public--> publish 

( phone autocomplete). Sorry for the noise.

**Comment by arose** [comment]
published 0.10.0-dev.8 :)

**Comment by hainm** [comment]
@arose any idea how to convert `OrientationMatrix` to python list-like?

**Comment by hainm** [comment]
@kain88-de you can try now. Dummy example:

```python
    view = nv.demo()
    view

    mat = [11, 12, 13, 14,
           21, 22, 23, 24,
           31, 32, 33, 34,
           41, 42, 43, 44]
 
    vector = [0, 1, 2]

    view.control.align(mat)
    view.control.rotate(mat)
    view.control.translate(vector)
    view.control.apply_matrix(mat)
    view.control.center(vector)
    view.control.orient(mat)
    view.control.zoom(0.3)
    view.control.rotate(mat)
    view.control.spin(vector, 0.1)
```

Note: You can not get `oritentation` with `_set_sync_camera` now. I don't know how to get that with new `NGL` change.

**Comment by kain88-de** [comment]
This isn't usable for me right now. I need to know how you define rotations exactly you define the 4x4 matrix for rotation. My current assumption is that this matrix includes also a translation. That is the only context I'm aware of for rotations to be represented as a 4x4 matrix.

Without information about the definitions it's just hoping to be lucky to convert my rotation matrix into the expected format.

For example to return 90 degrees around the z axes I tried the following code.

```python
mat = mda.lib.transformation(np.pi/2.0, [0, 0, 1]).tolist()
view.control.rotate(mat)
```

In the end I don't see anything in the view widget.

**Comment by hainm** [comment]
:D in the `rotate`, `mat` is a list with len=4.

@arose Please explain.

**Comment by arose** [comment]
`.rotate` accepts a quaternion not a matrix

**Comment by kain88-de** [comment]
@arose please document your quaternion convention, or at least point me to it. Unlike for a vector there isn't an existing standard for quaternions. This can seriously confuse people. Lets say I have a quaternion (s, \vec{v}), where s is the scaler part and \vec{v} the vector part (these are the 3 'imaginary' numbers).

MDAnalysis library returns quaternions with [s, v_x, v_y, v_z].  ngl expects [v_x, v_y, v_z, s] though.

it's possible to find this out by applying some rotations where you know the expected results like (1, \vec{0}). But if people forget that it can lead to confusion.

Also this works now to rotate

**Comment by arose** [comment]
> please document your quaternion convention

When you follow the links in the documentation (http://arose.github.io/ngldev/api/ViewerControls.html) it will send you to the three.js documentation (https://threejs.org/docs/#Reference/Math/Quaternion). Hope that helps.

**Comment by hainm** [comment]
Implemented. Closed.
