### ISSUE TITLE
nglview widget does not appear

### ISSUE THREAD

**Issue by MichaelSluydts** [arose/nglview#599]
Hello,

I can't seem to get the nglview widget to appear, commands and versions attached in screenshot. The server is web-accessible so I could give access to the notebook if need be (but need to deliver the password).

![nglviewproblem](https://cloud.githubusercontent.com/assets/8928724/24254547/796a4532-0fe3-11e7-8c27-2bddbf891158.PNG)

Thanks,

Michael

**Comment by hainm** [comment]
hi

try that in 3 different cells

1st cell: display the view first
```
view
```

2nd cell: 
```python
view.render_image()
```

3rd cell:
```python
view._display_image()
```

**Comment by hainm** [comment]
If you just want to visualize in the notebook:

you don't need to use `view.render_image` and `view._display_image()`. This is for saving to image. (EXPERIMENTAL).

**Comment by hainm** [comment]
close now. Please reopen it if you still get trouble.

**Comment by MichaelSluydts** [comment]
Thanks,

That part was definitely my fault... The pdb visualizes fine without render_image and display_image. When i try to use show_ase however I'm still getting issues. I've managed to get a unit cell to appear but atoms don't seem to show up. Does it need any additional styling options?

I tried first to use my own cif file and then one of the built-in ase methods built on one of the examples in the repo which gave equally unfruitful results.

Mine:
![nglview2](https://cloud.githubusercontent.com/assets/8928724/24305185/5e1a9528-10bc-11e7-8179-b9d064044543.PNG)

Repo: 
https://github.com/arose/nglview/blob/master/examples/users/ase.md

**Comment by hainm** [comment]
>  Does it need any additional styling options?

may be. try adding `view.add_licorice()`. (I guess `nglview` think your system is protein and it uses `cartoon` for repr).

**Comment by MichaelSluydts** [comment]
Thanks,

Using add_spacefill and add_licorice gave me a decent representation, seems I still need to learn to play with the camera (zoom and so on) and other representation settings too, but at least now I know everything is working. 

![nglview3](https://cloud.githubusercontent.com/assets/8928724/24306673/ad28f204-10c1-11e7-8fdf-e8d7afc8bef1.PNG)

Maybe show_ase should have its default representation updated a bit to avoid this? Not that it's that easy to detect the type of system. 

Keep up the good work!

**Comment by hainm** [comment]
> Maybe show_ase should have its default representation updated a bit to avoid this? Not that it's that easy to detect the type of system.

We will try to do that in the future. [NGL code](https://github.com/arose/ngl) is still changing so I myself do not want to add much default stuff in nglview now. cheers.

**Comment by arose** [comment]
It should be handled by the default NGL representation. I assume there is not enough information for NGL to know what to show. Currently the ASE adaptor uses a pdb file to get the data into NGL. Maybe another format is more appropriate here, like `cif`, `mol` or `sdf`.

**Comment by hainm** [comment]
@arose Can  you try current `NGL` with `ala3`? shown nothing (tried with both nglview and ngl)

(and even uploaded local ala3.pdb file (in ngl/data) to http://arose.github.io/ngl/)

**Comment by hainm** [comment]
<img width="1278" alt="screen shot 2017-03-25 at 12 16 59 am" src="https://cloud.githubusercontent.com/assets/4451957/24319373/6914d5b8-10f0-11e7-8bda-c7266f246a1d.png">

**Comment by arose** [comment]
Currently not handled by the defaultRepresentation. For small structures, with less then 4 residues, one idea would be to show ball+stick for all atoms.

**Comment by arose** [comment]
adjusted it, see https://github.com/arose/ngl/commit/0ed428feb37af005685801270786097d868269a3

**Comment by hainm** [comment]
thanks. Do you mind pushing 0.10.0-dev.9 to npm?

**Comment by arose** [comment]
> thanks. Do you mind pushing 0.10.0-dev.9 to npm?

done

**Comment by hainm** [comment]
updated to `nglview`. thanks.
