### ISSUE TITLE
more English please

### ISSUE THREAD

**Issue by hainm** [arose/nglview#6]
from this issue: https://github.com/arose/nglview/issues/4

```python
w = NGLWidget(...)
w.representations = [
    { "type": "cartoon", "params": {
        "sele": "protein", "color": "residueindex"
    } },
    { "type": "ball+stick", "params": {
        "sele": "hetero"
    } }
]
```

Since user need to specify options to change representation, should we use more complete English keyword? For example: does 'sele' mean 'select' or something else?

**Comment by arose** [comment]
`sele` means selection and refers to the NGL selection language http://arose.github.io/ngl/doc/#User_manual/Usage/Selection_language

I found `selection` too long, especially for writing scripts. Maybe a better documentation is enough? We could also allow `selection` additionally.

**Comment by hainm** [comment]
> I found selection too long, especially for writing scripts

too long for typing or too long script? :D

**Comment by arose** [comment]
I guess with `NGLWidget.add_representations(self, repr_type, selection, **kwd)` this is more or less fixed. I will keep it in mind though.
