### ISSUE TITLE
Install nbextensions with package

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#607]
nglview currently installs the nbextensions into `~/.local/share/jupyter/nbextensions`.

The [contrib_extension](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) project configured setuptools to install the nbextensions with the package into `lib/python2.7/site-packages/jupyter_contrib_nbextensions/nbextensions/`.  

That would be really helpful to install a stable and development version of nglview on the same computer.

**Comment by kain88-de** [comment]
Also this is would ensure that nglview works nicely in a global installation of conda. That would be useful for my group where we share a global conda installation (read only).

**Comment by hainm** [comment]
> nglview currently installs the nbextensions into ~/.local/share/jupyter/nbextensions

Its nbextentions are install for both local and global.

global: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/nglview/post-link.sh

`nglview` is iypwidgets-based so there additional step to activate the extension. If you are using conda, above `post-link.sh` is the solution but there is no way to auto-activate for pip user. So we decided to install and activate extension at run time to user' local. 

You should not worry about messing up between release and development version since the extension will be overwrite in your .local.

**Comment by hainm** [comment]
> Also this is would ensure that nglview works nicely in a global installation of conda. 

Does not `nglview` work for your group currently?

**Comment by hainm** [comment]
If you really want to not to install to .local, you can delete those lines in
'nglview.__init__.py

install_nglview_js_widgets()
enable_nglview_js_widgets()

However, you need to explicitly activate the extension by yourself

(Check the post-link.sh).

**Comment by hainm** [comment]
Uhm, and need to delete files in .local too.

**Comment by hainm** [comment]
Close since current behavior is our intention. Might change in the future anyway.

**Comment by kain88-de** [comment]
Sorry for the late answer,

How do you manage to install several versions of nglview on the same machine then? When I install the dev version in a conda environment I break nglview in my root environment. 

A similar thing is true at work. We have several versions of nglview installed in different module files. Your scheme makes it impossible for me to run two different modules in different shells with different versions of nglview.

> If you really want to not to install to .local, you can delete those lines in
'nglview.init.py

changing nglview after the installation to conda seems a good bit hacky at best.

**Comment by hainm** [comment]
Yes, that is the current install limitation of nglview extension. You can only run a version at a time. When you import nglview, the js code will be overwritten at the run time. You can always restore the release version (vs dev) by importing release version,

Or jupyter nbextension install nglview --py --user

Hai

**Comment by hainm** [comment]
I will make change tonight anyway

**Comment by kain88-de** [comment]
Thanks

**Comment by hainm** [comment]
@kain88-de give it a try, new version should be available now.

**Comment by kain88-de** [comment]
Already did it. Works fine
