### ISSUE TITLE
Incorrectly sending a comm message

### ISSUE THREAD

**Issue by jasongrout** [arose/nglview#618]
In https://github.com/arose/nglview/blob/4da7c0236994c84bf65dfcd0d6020b5060de6d4f/js/src/widget_ngl.js#L187, the model.send function is used without supplying necessary callbacks, as mentioned in the `model.send` documentation: https://github.com/jupyter-widgets/ipywidgets/blob/master/jupyter-js-widgets/src/widget.ts#L126

The usual convention is to call the *view* send method (as is done in other places in the code), which automatically supplies the necessary callbacks. So replace the `this.model.send(...` in the line above with `this.send(...`

Not supplying these callbacks means that the pending message counter in the widget is not updated correctly (it is not decremented when this message is finished being processed), which blocks further sync messages from being sent.

This fixes the issue brought up in https://github.com/jupyter-widgets/ipywidgets/issues/1375

**Comment by hainm** [comment]
thanks Jason. Issue is resolved.
