### ISSUE TITLE
Per-frame representations and perframe_hook

### ISSUE THREAD

**Issue by jaimergp** [arose/nglview#620]
Hello,

I am trying to make a movie with NGLView, displaying the binding path of a ligand entering a protein pocket. I want to display residues within a given threshold distance from the ligand, so, as it's moving, the displayed residues will be changing along time.

This is the code I am using:

```python
import mdtraj as md
import nglview as nv

ligand_idx = pltraj.top.select('resname DF1')
neighboring_atoms = md.compute_neighbors(pltraj, 0.4, ligand_idx)
neighboring_residues = []
for neighbors in neighboring_atoms:
    residues = set()
    for i in neighbors:
        atom = pltraj.top.atom(i)
        residues.add(atom.residue.index)
    neighboring_residues.append(residues)

v = nv.show_mdtraj(pltraj)
for frame in xrange(pltraj.n_frames):
    v.clear_representations()
    v.add_cartoon('protein')
    v.add_ball_and_stick('DF1')
    around = ' or '.join((map(str, neighboring_residues[frame])))
    v.add_ball_and_stick(around)
    v.update_representation(repr_index=-1)
    time.sleep(1)
    v.frame = frame
```

While the player does _play_, and the coordinates update, I cannot get the updated residues in the view. The player seems to only display them at the end of the for-loop, or if I force a KeyboardInterrupt during the execution. Am I missing any `update_something` calls? The residues do appear if I do it manually, without a for-loop.

Thanks in advance,
Jaime.

PS: While we are at it, it'd be nice if `nglview.contrib.movie.MovieMaker` could accept a `perframe_call` hook or something similar to run a set of commands in each frame. I'd be happy to submit a PR if that's OK.

**Comment by hainm** [comment]
> PS: While we are at it, it'd be nice if nglview.contrib.movie.MovieMaker could accept a perframe_call hook or something similar to run a set of commands in each frame. I'd be happy to submit a PR if that's OK.

it would be awesome.

I will reply to other later since need to test myself.

**Comment by hainm** [comment]
You need to display the view first

`Cell 1`

```python
import mdtraj as md
import nglview as nv

ligand_idx = pltraj.top.select('resname DF1')
neighboring_atoms = md.compute_neighbors(pltraj, 0.4, ligand_idx)
neighboring_residues = []
for neighbors in neighboring_atoms:
    residues = set()
    for i in neighbors:
        atom = pltraj.top.atom(i)
        residues.add(atom.residue.index)
    neighboring_residues.append(residues)

v = nv.show_mdtraj(pltraj)
v # --> The trick is here
```

`Cell 2`
```python
for frame in xrange(pltraj.n_frames):
    v.clear_representations()
    v.add_cartoon('protein')
    v.add_ball_and_stick('DF1')
    around = ' or '.join((map(str, neighboring_residues[frame])))
    v.add_ball_and_stick(around)
    v.update_representation(repr_index=-1)
    time.sleep(1)
    v.frame = frame
```

**Comment by hainm** [comment]
here is what I tried (pay attention the appear of the extra atoms in one of the frames)



![update](https://cloud.githubusercontent.com/assets/4451957/26476946/15fd664e-4190-11e7-8508-588917276987.gif)

**Comment by jaimergp** [comment]
Well, yes, I forgot to include that line in my snippet, but I do have it in the notebook. I think I'll record a GIF as well to depict what's happening in my case. Thanks for the effort!

PS: Which version are you using? Maybe that's the problem here?

**Comment by jaimergp** [comment]
Nevermind, an update fixed the problem. I was running nglview 0.6.2 out of lazyness (ipywidgets keeps breaking in my system), but after some dependencies struggle I am running 0.6.3 and it works flawlessly.

With respect to the `perframe_hook`, should I open a different issue to discuss the implementation or can we keep this one? Thanks again!

**Comment by hainm** [comment]
It's ok to discuss here. We can change the issue title since the original issue is not an issue.
