### ISSUE TITLE
NGLview with pdb structures export to html

### ISSUE THREAD

**Issue by pgreisen** [arose/nglview#623]
- Question about usage? https://github.com/arose/nglview/issues/589
My problem is that when I try to download as html - a html is downloaded but instead of having the interactive protein structure - I get a line saying 
A Jupyter Widget

I am using chrome for this as safari gives some other isssue displaying the protein - any suggestions? Thanks

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
0.6.3
7.0.0a4
python -c 'import ipywidgets; print(ipywidgets.__version__)'
```

- Please always double-check install guide here: https://github.com/arose/nglview#released-version
(updated frequently)

**Comment by hainm** [comment]
But we can let this issue open to remind us.

**Comment by hainm** [comment]
@pgreisen So I don't foresee if the saved html will work for nglview.

Currently we only support simple serialization via `nglview.write_html`

https://github.com/arose/nglview/pull/687

Close now. Do feel free to open others.
