### ISSUE TITLE
ipywidgets 6 support

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#625]
What is the current reason for nglview to not support ipywidets 6?
Is there a way others could help to make the transition?

**Comment by hainm** [comment]
master branch does support ipywidgets 5, 6 and 7.

However, the ipywidgets 6 has [bug](https://github.com/jupyter-widgets/ipywidgets/issues/1044#issuecomment-276458101) and it doesn't have stable API (some changed in v7).

**Comment by kain88-de** [comment]
Is there any knows when the newest version will be out? It also looks like from the issue discussion as this was a bug in NGL. 

My personal issue is that I'm starting to have to use nglviewer in  a custom conda environment since other common widget packages all depend on ipywidgets6 now.

**Comment by hainm** [comment]
> Is there any knows when the newest version will be out? 

how's about tonight (US time)?

**Comment by kain88-de** [comment]
You mean a new version of nglviewer with conda packages that pin to ipywidgets 6? Sure I'm good with any date for that.

**Comment by hainm** [comment]
The problem is that I don't want to support ipywidgets 6. It's a transition from old API v5 to more stable (new) API v7. 

If you really want to try with `ipywidgets 6`, please use git version of nglview. 
cheers.

**Comment by hainm** [comment]
PS: I myself prefer to have an usable and stable software rather trying to experimenting bleeding-edge with lots of bugs.

**Comment by hainm** [comment]
I just tried nglview master branch with ipywidgets v6 and the below bug still exists

![debug](https://cloud.githubusercontent.com/assets/4451957/22479924/97fcad8a-e7bd-11e6-9d44-df88329f1c29.gif)

Note that we already have a fix for ipw v7:  https://github.com/arose/nglview/issues/618

So for now, no official support for ipywidgets 6.

**Comment by hainm** [comment]
Similar solution from beakerx:

https://github.com/twosigma/beakerx/pull/5486

**Comment by hainm** [comment]
The next release of `nglview` will be compatible with ipywidgets 7. 

https://github.com/arose/nglview/pull/635/files#diff-b4ef698db8ca845e5845c4618278f29aR2
