### ISSUE TITLE
Add text to a view

### ISSUE THREAD

**Issue by hainm** [arose/nglview#626]
cc @kain88-de

**Comment by satary** [comment]
Hello @hainm !
This way works if you want to have "rotatable" text, but what if I need to overlay some text "in front" of the view? Are there any relatively simple ways to do that?

**Comment by hainm** [comment]
@arose: any idea? Thanks.

**Comment by arose** [comment]
To some extent you can use the zOffset parameter. If that is larger than the bounding radius of your models then all text will be rendered in front.

**Comment by hainm** [comment]
and may be `view.shape.add_text` is another option if I understand the issue correctly.
https://github.com/arose/nglview/blob/b15ccc9d49ad191888be3f2ff3921b79ae647020/nglview/shape.py#L114

**Comment by satary** [comment]
@arose Sorry for the late reply.
The idea is not to just place the label in front of the molecule. The idea is to overlay the text onto the widget itself (to add title and legend, for example). 
Something like the atom label at the left corner of this screenshot.
![nglview_screenshot](https://user-images.githubusercontent.com/2101895/53820786-8b2db080-3f7d-11e9-8e72-ce6bacc9629e.png)

Another question is why this atom label (I mean at the left corner of the screenshot) is not rendered if I want to save the image?

**Comment by arose** [comment]
The label is not rendered in screenshots because its is not part of the 3d scene but a simple html element. As far as I know there is no API to add html to the widget but maybe @hainm has an idea.

Btw. Is that structure in the PDB archive? The protein look interestingly symmetric.

**Comment by satary** [comment]
@arose Ok, got it.
That is a part of the nucleosome (1kx5 pdbID) =)

**Comment by hainm** [comment]
There is no API to add  HTML yet, but there's a hacky  way to do it by using `view._execute_js_code`
https://github.com/arose/nglview/pull/768

```python
code = """
$("<div></div>")
            .css("position", "absolute")
            .css("top", "5%")
            .css("left", "3%")
            .css("background-color", "white")
            .css("padding", "2px 5px 2px 5px")
            .css("opacity", "0.7")
            .appendTo(this.$container);
"""
You need to play around with this to add your own text. good luck.

view._execute_js_code(code)
```

**Comment by arose** [comment]
> That is a part of the nucleosome (1kx5 pdbID), its got a two-fold symmetry axis =)

Thank, looks like there is local C2 symmetry, made a snapshot https://molstar.org/viewer/?snapshot-url=https%3A%2F%2Fwebchem.ncbr.muni.cz%2Fmolstar-state%2Fget%2F5de7da28-c560-4dc0-8c31-fce8f383348b

**Comment by hainm** [comment]
<img width="1072" alt="screen shot 2019-03-07 at 12 07 50 am" src="https://user-images.githubusercontent.com/4451957/53933595-146fe080-406d-11e9-9595-e344e28ac148.png">

**Comment by satary** [comment]
@hainm Thanks for the great example!

**Comment by hainm** [comment]
> Any progress on a 'add_title' method? The above did not work for me.

have you tried in the traditional notebook yet?

**Comment by scottwsides** [comment]
I havent... but I'm never going to use the trad notebook. I've drunk the jupyterlab kool-aid ;-)

**Comment by hainm** [comment]
jupyterlab was not pleasure to work with in 2017 when this topic was opened, so we have not revisited the lab yet.

**Comment by scottwsides** [comment]
Understood. But my feeling is that jupyterlab is definitely the weapon of choice for most. Its the logical progression through the years of

python cmd line ---> ipython cmd line ---> jupyter notebook ---> jupyterlab notebook. 

I dont think there's any going back. I'd love NGLView to have better integration because Chemistream leans heavily on your great library.

**Comment by hainm** [comment]
> I dont think there's any going back. I'd love NGLView to have better integration because Chemistream leans heavily on your great library, and Chemistream is exclusively jupyterlab for UI

yeah, I agree with you about jupyterlab. I had more free time when I was a postdocs to work on nglview than nowadays.

**Comment by scottwsides** [comment]
Copy that... I hear ya brother ;-)
