### ISSUE TITLE
Uncaught Error: Script error for "nglview-js-widgets"

### ISSUE THREAD

**Issue by gfudenberg** [arose/nglview#629]
hi, I'm running into trouble trying to run the most basic example:

import nglview
view = nglview.show_pdbid("3pqr")  # load "3pqr" from RCSB PDB and display viewer widget
view

ipython doesn't report any errors (previously had widgets errors, but re-installed ipywidgets==5.2.2, and that fixed those errors), but the following errors show up in the javascript console (i.e. if I press ctrl-shift-I)

:8888/nbextensions/jupyter-js-widgets/extension.js?v=20170518175122:32167 Uncaught Error: Script error for "nglview-js-widgets"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:165)
    at HTMLScriptElement.onScriptError (require.js:1732)

any help appreciated!
Thanks
Geoff

**Comment by hainm** [comment]
I guess you still need to uninstall the `widgetsnbextension` bundled with new ipywidgets version.

If you are using conda, try to create new env

```bash
conda create -n test python=3.6
conda install -c bioconda nglview
```

**Comment by gfudenberg** [comment]
cleaned up all widgetsnbextension(s) that I could find.

getting a new error now:
API request failed (403): Forbidden


thanks!

**Comment by hainm** [comment]
Oops, I meant cleanup and reinstall ipywidgets 5 so the compatible widgetnbextension will be properly installed.

**Comment by gfudenberg** [comment]
back to this error message: 
![image](https://user-images.githubusercontent.com/19657573/27714858-612398fa-5ce8-11e7-9f17-ae350c3759ca.png)

even though nbextension is enabled. I tried conda installs for nglview & ipywidgets=5.2.2, then uninstalled and tried installing via pip. Same error message both ways.

**Comment by hainm** [comment]
Either

1. Try with a fresh conda env
```python
conda create -n test python=3.5 numpy
conda install -c bioconda nglview
```

2. Completely remove

I am not sure how you uninstall your packages, but sometimes I just manually remove folder by
myself

```bash
find . -name widgetsnbextension
find . -type f -name *ipywidgets*
# delete some folders from above search

conda install ipywidgets=5 --force
conda install -c bioconda nglview --force
```

Sorry about this frustration. It's price we need to pay when `ipywidgets` is still evolving rapidly.

**Comment by gfudenberg** [comment]
Thanks, seems to be working now. Must have been some some weird version clash.
Thanks!
Best,

**Comment by hainm** [comment]
cheers
