### ISSUE TITLE
ipywidgets should be required

### ISSUE THREAD

**Issue by jbarnoud** [arose/nglview#632]
`ipywidgets` is declared as an extra requirement in `setup.py`, yet it is not possible to import nglview without it. It should therefore be a plain requirement.

```
import nglview

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f9b21067454f> in <module>()
      6 from matplotlib import pyplot
      7 
----> 8 import nglview

~/Envs/mda3/lib/python3.6/site-packages/nglview/__init__.py in <module>()
     29 # interface
     30 from .config import BACKENDS
---> 31 from .widget import NGLWidget
     32 from .base_adaptor import *
     33 from .adaptor import *

~/Envs/mda3/lib/python3.6/site-packages/nglview/widget.py in <module>()
      7 import numpy as np
      8 from IPython.display import display
----> 9 from ipywidgets import Box, DOMWidget, widget_image
     10 from traitlets import (Unicode, Bool, Dict, List, Int, Integer, observe,
     11                        CaselessStrEnum)

ModuleNotFoundError: No module named 'ipywidgets'
```

Note that the installation instructions do mention that `ipywidget` is required.

- Version report

Tested on nglview 0.6.5. As of d74a8fca983ccfac81f411d3fa8531831f69640c, `setup.py` does not declare `ipywidgets` as a plain requirement.

**Comment by hainm** [comment]
Hi,
it's intention. Originally we put that in setup.py but that will pull a bunch of packages and normally does not work well. e.g: ipywidgets will require notebook, which will require zmq (with c extension).

**Comment by kain88-de** [comment]
I actually don't  see how the package can work without the notebook either. Even the cli seems to require the notebook.

**Comment by hainm** [comment]
Yes indeed. Conda handles binary extension better so we put the requirements there.

**Comment by hainm** [comment]
It is easier to say 'just install ipywidgets' than 'i dont know how to debug zqm compiling issue'

**Comment by kain88-de** [comment]
I'm a bit confused how `pip install ipywidgest` is different then having it in `setup.py` already. It might very well by python packaging doesn't always behave as expected.

**Comment by hainm** [comment]
Because 

pip install ipywigets

does not usually work nicely. As I said earlier, zmq with c extension
will might be installed during that process.

You can try that with a centos 5 docker image.

**Comment by hainm** [comment]
I will add to setup.py requirement once zmq guys create binary like
using manylinux build.

**Comment by hainm** [comment]
pyzmq does have manylinux build now: https://pypi.python.org/pypi/pyzmq

**Comment by hainm** [comment]
uhm currently `nglview` requires `ipywidgets v5.2.2`. Not sure if users who are eager with newer version will be upset if `nglview` downgrades.

**Comment by hainm** [comment]
So I've tried install ipywidgets 7 via pip from a clean centos 5 image (with updated python 2.7).

Still get stuck with `pyzmq` install

```
  bundled/zeromq/src/ip.cpp:54:14: error: ‘SOCK_CLOEXEC’ was not declared in this scope
       type_ |= SOCK_CLOEXEC;
                ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
```

So user need to deal with ipywidgets by themself. Close this issue and thanks @jbarnoud for your suggestion.

**Comment by hainm** [comment]
This is the full log for those interested.

[log.txt](https://github.com/arose/nglview/files/1151304/log.txt)

**Comment by hainm** [comment]
reopen this since `pip install ...` works fine with centos 6. May be it's time to ignore centos 5.
