### ISSUE TITLE
How to show atom label name 

### ISSUE THREAD

**Issue by cuzzo87** [arose/nglview#650]
I was trying to show atom label names. Following another issue #15 I was able to show them but the information of the label are not the ones I would like to show.
The current output of the label are the (resname + resid ). Is there any way to show the ( atom name, atomindex etc. )?

Many thanks  for the help

**Comment by hainm** [comment]
can you post your screenshot? thanks.

**Comment by cuzzo87** [comment]
Here the screenshots. As you it depicts the resname and resid (MOL 1200). What I want is to se for each atoms C1, C2, O1 etc.
If I can I would like to ask you if it is also possible to modify the text size
Thank you for the quick reply

![lig_label](https://user-images.githubusercontent.com/10772443/28467747-25142758-6e31-11e7-948f-7e05af0a63fe.png)

**Comment by hainm** [comment]
Please post your code too. (be best to just capture your notebook screen).

**Comment by hainm** [comment]
cc @arose

**Comment by cuzzo87** [comment]
```
from htmd.ui import *
import nglview
from nglview import HTMDTrajectory

m =Molecule('structure.pdb')
w=nglview.NGLWidget(HTMDTrajectory(m))
selidx = '@' + ','.join(map(str, m.atomselect("resname MOL", indexes=True)))
w.add_representation("licorice", selection=selidx)
w.add_representation('label', selidx, color='black')

w
```

**Comment by hainm** [comment]
I will let @arose reply to you.

**Comment by hainm** [comment]
Ah, please see here

http://nglviewer.org/ngl/api/typedef/index.html#static-typedef-LabelRepresentationParameters

```
view.add_label(your_label, labelType=...)
```

**Comment by hainm** [comment]
@arose does NGL support changing text size yet? I don't see that in above docs.

**Comment by arose** [comment]
the `LabelRepresentation` also inherits `scale`, `radiusType` and `radius`

**Comment by hainm** [comment]
![x](https://user-images.githubusercontent.com/4451957/28651450-f3efcc22-724f-11e7-85bb-709e786c7fb3.png)

close now. Please above example.
