### ISSUE TITLE
nglview 1.0 release?

### ISSUE THREAD

**Issue by kain88-de** [arose/nglview#685]
When is the 1.0 release coming out? I currently have problems running the latest stable release on python 3.6 with conda. (It complains the widget code cannot be found).

**Comment by kain88-de** [comment]
Everything works for me with the pre release version though.

**Comment by hainm** [comment]
1.0 will released once we have a nice implementation of embeding nglview in webpage. Current api is not good.

**Comment by hainm** [comment]
Meanwhile it's ok to use prerelease version, we won't break any stable API.

**Comment by hainm** [comment]
Just discussed with @arose and we are trying to release `ngl` and `nglview` by the end of this month.

**Comment by hainm** [comment]
Open #694 and close this.
