### ISSUE TITLE
Feature Request: add_representation() accepts radius array

### ISSUE THREAD

**Issue by gph82** [arose/nglview#692]
This would be a really neat addition!

**Comment by hainm** [comment]
Cc @arose, should be in NGL.

**Comment by arose** [comment]
like this? https://codepen.io/arose/pen/dzLbaK?editors=0010

**Comment by hainm** [comment]
@gph82  can you confirm if above works for you? thx.

**Comment by gph82** [comment]
It worked, thanks! 

However, the radius gets read from the pdb-file into the MDTrajectory, there's no way of changing it after the fact. I've renamed the issue. What do you think?

**Comment by gph82** [comment]
thanks. Feel free to close this or keep open until the ngl issue gets fixed.

**Comment by hainm** [comment]
@arose may be a good idea to add that to 1.0?

**Comment by arose** [comment]
I prefer to do that in typescript in the v2 branch

**Comment by hainm** [comment]
@arose what's the status of this issue?

**Comment by hainm** [comment]
never heard back from @arose  so I assume this feature won't be supported.
