### ISSUE TITLE
Prepare 1.0 release

### ISSUE THREAD

**Issue by hainm** [arose/nglview#694]
Listing ...

- [x] update NGL 1.0 [beta 4]
- [x] Run all notebooks in nglview/tests/notebooks/api (via `nightwatch` and manually)
- [x] Make sure `nv.write_html` work nicely.
- [x] Write change log.

**Comment by arose** [comment]
doing ngl 1.0 release as well :)

**Comment by hainm** [comment]
Great

**Comment by hainm** [comment]
I will wait for NGL 1.0.

**Comment by arose** [comment]
on it :)

**Comment by hainm** [comment]
sorry, can't wait. I am happy with NGL 1.0.b4 for now.

https://github.com/arose/nglview/releases/tag/v1.0

- [x] pypi 
- [ ] biocoda: https://github.com/bioconda/bioconda-recipes/pull/6553

**Comment by hainm** [comment]
linux builds are available in bioconda channel now, the macOS builds are pending.
https://anaconda.org/bioconda/nglview/files

@kain88-de enjoy, sorry for the long delay.

**Comment by kain88-de** [comment]
Don’t worry. Glad you finished it so soon :-)
