### ISSUE TITLE
add_component 404 GET error. local filename? 

### ISSUE THREAD

**Issue by gph82** [arose/nglview#697]
nglview 1.02b
ipywidgets 7.0.1

```python
iwd = nglview.show_structure_file(os.path.abs('file1.pdb'))
iwd
```
works, however:
```python
iwd.add_component(os.path.abspath('file1.pdb'))
iwd
```
will just produce the already instantiated widget, but without the second structure. In the console, it 
will complain with:
```
Error: NetworkStreamer._read: status code 404
```
which, in the terminal is more verbose, telling me that it's trying to read the file  /notebooks/file1.pdb. However, it is elsewhere. show_structure() seems to be able to deal with it, but not add_component()
```
[W 15:41:00.523 NotebookApp] 404 GET /notebooks/file1.pdb (::1) 1.22ms referer=http://localhost:8888/notebooks/Figure_summary.ipynb
```

**Comment by hainm** [comment]
Thanks, sounds like a bug. Will investigate tonight.

**Comment by hainm** [comment]
Can you post your notebook version too?

**Comment by hainm** [comment]
Can you post your notebook version too?

**Comment by gph82** [comment]
5.0.0

**Comment by hainm** [comment]
And if you does not use abspath, will that work?

**Comment by gph82** [comment]
no no, it does not work either. I just added it because I did not want to obscure things

**Comment by gph82** [comment]
Seems to me that somewhere an os.path.basame is being done on the filename

**Comment by gph82** [comment]
I'll work around it in the meantime with ad-hoc symlinks. I'm forced to use add_structure instead of add_component because I still parse read bfactors/radius-arrays to the worm representation

**Comment by gph82** [comment]
where would the /notebooks/ folder be in my FS?

**Comment by hainm** [comment]
So here is the logic:
There are two ways to send data to NGL, sending text blob (using file handler) or let NGL read the file path directly. The latter is much faster but it requires your file is in subfolder of your current working path.

I am not sure about your case, need to teat myself first.

**Comment by gph82** [comment]
ok. I just updated the original issue, there was some inconsistencies in the issue

**Comment by hainm** [comment]
The show_structure_file works because it always read your file content first (python) then send that to ngl (JavaScript).

**Comment by hainm** [comment]
uhm, I can not reproduce yours.

<img width="1159" alt="screen shot 2017-09-29 at 11 12 18 pm" src="https://user-images.githubusercontent.com/4451957/31041946-acaf6eae-a56b-11e7-93db-f01ec3c7ae7d.png">

**Comment by hainm** [comment]
<img width="1165" alt="screen shot 2017-09-29 at 11 15 28 pm" src="https://user-images.githubusercontent.com/4451957/31041970-1cb2d43e-a56c-11e7-9d7a-f5bc664cf326.png">

**Comment by hainm** [comment]
@gph82 any response on this? thanks.

**Comment by gph82** [comment]
Hi @hainm . Not really sure your example reproduces mine....
![screenshot_20171004_163202](https://user-images.githubusercontent.com/7518004/31181428-93b5f7ba-a921-11e7-9e69-e896dd492113.png)

**Comment by gph82** [comment]
Meanwhile, on the terminal...
```
[W 16:30:04.845 NotebookApp] 404 GET /notebooks/1U19.pdb (::1): No such file or directory: 1U19.pdb
```
but the file exists on the home directory for sure

**Comment by hainm** [comment]
how can you get two structures in that display?

Can you just try one?

**Comment by hainm** [comment]
what's the output of

```
!pwd

os.path.abspath("1U19.pdb")
```

**Comment by gph82** [comment]
Okay i'll make a more comprehensive notebook, I think we're talking past each other

**Comment by hainm** [comment]
would be great. If possible, please share your troublesome files too.
thanks.

**Comment by gph82** [comment]
Here we go
[3CAP.zip](https://github.com/arose/nglview/files/1356278/3CAP.zip)
[1U19.zip](https://github.com/arose/nglview/files/1356279/1U19.zip)
[Untitled.zip](https://github.com/arose/nglview/files/1356285/Untitled.zip)

**Comment by hainm** [comment]
work fine to me after editing.

<img width="1160" alt="screen shot 2017-10-04 at 10 11 57 pm" src="https://user-images.githubusercontent.com/4451957/31208206-16de4e38-a951-11e7-99a1-e7346c7bcd0c.png">

PS: Your command is not correct

```
file2 = '1U19.pdb'
print(os.path.exists(file2), os.path.abspath(file2))
geom2 = md.load(file2)
iwd = nglview.show_mdtraj(geom1)
iwd = iwd.add_trajectory(geom2) # why overwrite `iwd`?
iwd
```

**Comment by hainm** [comment]
I don't get any 404 error:

<img width="1280" alt="screen shot 2017-10-04 at 10 13 54 pm" src="https://user-images.githubusercontent.com/4451957/31208238-6531aea4-a951-11e7-9e76-9a5b843cf5e9.png">

**Comment by hainm** [comment]
oops, by the way, I am testing with nglview 1.0.b4

**Comment by hainm** [comment]
fine with 1.0.b2 too.

@arose can you try again? Here is the updated notebook that correct the command.
(change .txt to .ipynb)

[Untitled.txt](https://github.com/arose/nglview/files/1357863/Untitled.txt)

**Comment by hainm** [comment]
@gph82  I guess you need to play around with realpath and abspath in this code:
https://github.com/arose/nglview/blob/master/nglview/utils/py_utils.py#L196-L197

May be try to change:
```
return os.path.relpath(self.src)
```

to 

```
return os.path.relpath(os.path.realpath(self.src))
```

or print out to see what happens.

**Comment by gph82** [comment]
Thanks for pointing out that one mistake. That was a "typo" of writing up the example notebook quickly (see attached updated version). 

In any case, the FileManager class was calling the  
```
 self._remote_call(
           "loadFile", target='Stage', args=args, kwargs=kwargs2)
```
with the filename-string instead of the already parsed string with the actual structure. Was that intended? You can try running the updated notebook with this branch (or just copy the "for debugging" to yours):
https://github.com/arose/nglview/compare/master...gph82:abs_path_file_obj_reading?expand=1

I'm trying to play around with it but still no luck

**Comment by hainm** [comment]
> Was that intended?

Yes, I explained here: https://github.com/arose/nglview/issues/697#issuecomment-333134655

In the worse case, use FileStructure

```
fs = nv.FileStructure('your.pdb')
view.add_component(fs)
```

I think this should work :D

**Comment by gph82** [comment]
I'll try that, thanks. Regarding your https://github.com/arose/nglview/issues/697#issuecomment-333134655 I understood that, but even if the abspath is parsed to the server, it fails...
![screenshot_20171005_144343](https://user-images.githubusercontent.com/7518004/31227834-9e8ab4b8-a9db-11e7-9d2d-e913e69df85a.png)

**Comment by hainm** [comment]
yes, absolute path will be failed, that's the way WWW works for security reason.

**Comment by hainm** [comment]
uhm, I am afraid that you need to figure out by yourself in this case since I can not reproduce your issue. :( good luck, man.

**Comment by gph82** [comment]
I understand. Thanks a lot, man. Your workaround worked, BTW! Keep up the good work!

**Comment by hainm** [comment]
> Your workaround worked,

In this case, just FYI: https://github.com/arose/nglview#notes
