### ISSUE TITLE
Mouse selection/picking broken in Safari

### ISSUE THREAD

**Issue by lenhsherr** [arose/nglview#698]
Hi,
Is there anyway to enable mouse control, such as show pointed or selected component information?

**Comment by lenhsherr** [comment]
Nevermind, it only seems to stop working in safari, Firefox works fine

**Comment by arose** [comment]
Can reproduce, not working in Safari :(

**Comment by hainm** [comment]
"ngl": "0.10.5-22"

**Comment by arose** [comment]
should be fixed with latest ngl release

**Comment by hainm** [comment]
@lenhsherr that fix is in v1.0.b5 nglview. Let us know if you still get the issue. thanks.

**Comment by lenhsherr** [comment]
Thanks a lot! Just tested, now working in safari.

Feel free to close the issue.

**Comment by hainm** [comment]
thanks to confirm.
