### ISSUE TITLE
new syntax for adding representations

### ISSUE THREAD

**Issue by hainm** [arose/nglview#7]
(I am not sure about this issue's title, might update later).

What do you think about this syntax

```python
import nglview as nv
w= nv.NGLWidget(...)

# new syntax
w.select('protein').representation('cartoon', **kwd)
w.select('hetero').representation('ball+stick', **kwd)
```

or

``` python
# new syntax
w.select('protein', representation='cartoon', **kwd)
w.select('hetero', representation='ball+stick', **kwd)
```
which is equal to
```python
w.representations = [
    { "type": "cartoon", "params": {
        "sele": "protein", "color": "residueindex"
    } },
    { "type": "ball+stick", "params": {
        "sele": "hetero"
    } }
]
```

of course, we can still massively update representation via `w.representations  = ...`

**Comment by hainm** [comment]
I am trying in this branch:

https://github.com/hainm/nglview/tree/simple_api_with_notebook

syntax
```python
tv.representations = []
tv._add_representation('*', type='line')
tv._add_representation('*', type='ball+stick')
tv._add_representation('*', type='cartoon')
# selection = 'resname ASN'
selection = 'calpha'
tv._add_representation(selection, type='rope', color='red')
```

**Comment by arose** [comment]
Hi, I like the implementation you have in your master branch. I would be super if you could do a pull request for that! Thank you!

**Comment by hainm** [comment]
I added and changed a lot, so I am not sure which implementation you refer (the representation or TrajecotoryViewer? or something else).

**Comment by arose** [comment]
Sorry, I wasn't clear. I meant specifically the `add_representation` method.

**Comment by hainm** [comment]
ok. I will make a PR about add_representation
