### ISSUE TITLE
very slow if display view again if view has surface

### ISSUE THREAD

**Issue by hainm** [arose/nglview#702]
```
# 1st cell
import nglview as nv

view = nv.show_file('../ngl/data/1crn_apbs_pot.dx.gz')
view

# 2nd cell
view
```

The current implementation is to store a series of commands in view, if display 2nd times, those commands (e.g: loadFile) will be executed again for 2nd view.

@arose any idea solution? Clearly that I don't understand much about MVC model.

**Comment by arose** [comment]
In the view in the second cell, all ngl related things are executed again. In principal you could just do the rendering on a new canvas but that is not implemented in ngl.

**Comment by hainm** [comment]
is that something you would do in the future?

**Comment by arose** [comment]
no specific plans, keep in mind when creating a separate renderer module

**Comment by hainm** [comment]
thanks, close now.
