### ISSUE TITLE
suggestion: get secondary structure from pyrosetta pose and load into NGL

### ISSUE THREAD

**Issue by thrakar9** [arose/nglview#707]
Hello,
I was wondering whether it is possible to use the DSSP predicted secondary structure information from a PyRosetta Pose, when loading the pose to the NGL viewer, so that it is correctly displayed. 

In other words, the idea is that the following lines should produce an NGL visualization with the complete secondary structure (currently only alpha helices are displayed correctly). 

```python
import pyrosetta
import nglview
from pyrosetta.toolbox import get_secstruct, pose_from_rcsb
pyrosetta.init()
pose = pose_from_rcsb('4un3')
get_secstruct(pose)
#pose.secstruct() displays the DSSP predicted secondary structure
view = nglview.show_rosetta(pose)
view.update_cartoon(select='protein', color='sstruc')
view
```

**Comment by hainm** [comment]
hi,

I am not sure if that's doable in nglview. Ping @arose here (please check attached pdb too).

<img width="607" alt="screen shot 2017-10-11 at 8 26 52 pm" src="https://user-images.githubusercontent.com/4451957/31473450-9c96c138-aec2-11e7-97c7-3509a72f9d10.png">

[pose.txt](https://github.com/arose/nglview/files/1377588/pose.txt)

**Comment by arose** [comment]
currently the pdb file loaded into ngl needs to include the sec struc info, so one would need to include the info from rosetta into the pdb

**Comment by hainm** [comment]
For now, please follow @arose's suggestion.

**Comment by matteoferla** [comment]
As a Google search brought this up top for pyrosetta and SS, I am adding a note for others:

`pose.secstruct()` is filled only when calculated or SS read in the header. To calculate it:

```python
pose: pyrosetta.Pose = ...
# option 1:
pyrosetta.rosetta.core.scoring.dssp.Dssp(pose).get_dssp_secstruct()
# option 2:
pyrosetta.rosetta.protocols.moves.DsspMover().apply(pose)
```
DSSP relies on 3D protein, while the one that does not is in `Bio.SeqUtils.ProtParam`.

(Regarding the original Q, generating and pre-pending the PDB block's HELIX and SHEET entries is the solution.
Given that the PDB block is extracted like this:

```python
buffer = pyrosetta.rosetta.std.stringbuf()
pose.dump_pdb(pyrosetta.rosetta.std.ostream(buffer))
pdb_block = buffer.str()
```
Then one simply annotates. I do not have a snippet, but here is one using PyMol [(copied from here)](https://github.com/matteoferla/MichelaNGLo-transpiler/blob/master/michelanglo_transpiler/transpiler_io_mixin.py#L115), the only annoying part is the incremental SHEET numbering:

```python
if ss_last == 'H':  # previous was the other type
                self.ss.append('{typos}  {ss_count: >3} {ss_count: >3} {resn_start} {chain} {resi_start: >4}  {resn_end} {chain} {resi_end: >4} {h_class: >2}                                  {length: >2}'.format(
                    typos='HELIX',
                    ss_count=ss_count[ss_last],
                    resn_start=resn_start,
                    resi_start=resi_start,
                    resn_end=resn_last,
                    resi_end=resi_last,
                    chain=chain,
                    h_class=1,
                    length=int(resi_last) - int(resi_start) # already polished
                ))
                ss_count[ss_last] += 1
            elif ss_last == 'S':  # previous was the other type
                self.ss.append('{typos}  {ss_count: >3} {ss_count: >2}S 1 {resn_start} {chain}{resi_start: >4}  {resn_end} {chain}{resi_end: >4}  0'.format(
                    typos='SHEET',
                    ss_count=ss_count[ss_last],
                    resn_start=resn_start,
                    resi_start=resi_start,
                    resn_end=resn_last,
                    resi_end=resi_last,
                    chain=chain,
                    h_class=0,
                    length=resi_last - resi_start
                ))
                ss_count[ss_last] += 1
```

**Comment by hainm** [comment]
Thanks @matteoferla
