### ISSUE TITLE
widgetsnbextension is installed to user, but nglview is installed to sys-prefix

### ISSUE THREAD

**Issue by tdaff** [arose/nglview#710]
I noticed the widgetsnbextension was getting installed to a home directory but nglview is installed in the prefix, so it wouldn't work for other users. 

I think the following line would need `user=False, sys_prefix=True` added, but I've not tested it:

https://github.com/arose/nglview/blob/6febf481803f45c605217c5dde1e08f22d61f946/setup.py#L48

**Comment by hainm** [comment]
thanks. fixed in #711
