### ISSUE TITLE
initial repr param is ignored

### ISSUE THREAD

**Issue by hainm** [arose/nglview#712]
from @gph82  https://github.com/arose/nglview/issues/589#issuecomment-338734823

![image](https://user-images.githubusercontent.com/4451957/31919080-20c7875c-b82e-11e7-85ff-a8e0f014f5ae.png)

**Comment by gph82** [comment]
I'm sorry, but the initial repr (and the _set_size, BTW) keep being ignored:
![screenshot_20171025_105752](https://user-images.githubusercontent.com/7518004/31989764-880d94c4-b973-11e7-8624-4033d90f0780.png)

**Comment by hainm** [comment]
hi, nglview won't work that way yet (technical issue). You need to pass a Trajectory derived class to NGLWidget.

```python
view = nv.NGLWidget(nv.MDTrajTrajectory(geom[0]), representations=...)
view
```

Try to reproduce mine first
```python
import nglview as nv

s = nv.FileStructure(nv.datafiles.ALA3)
view = nv.NGLWidget(s, represetations=...)
view
```

![image](https://user-images.githubusercontent.com/4451957/32000006-3c901a90-b963-11e7-908b-c3a7f5d277de.png)

PS1: Per `_set_size` issue,  I am not sure why. Investigate later.
PS2: try to replace "Licorice" by "licorice"

**Comment by gph82** [comment]
Got it. The "licorice" thing did not work. Will report back. Thanks!

**Comment by hainm** [comment]
`_set_size` is fine too.

<img width="1154" alt="screen shot 2017-10-25 at 9 49 04 pm" src="https://user-images.githubusercontent.com/4451957/32031325-78c1a234-b9ce-11e7-821d-97293d720f8e.png">

**Comment by hainm** [comment]
@gph82 any update?

**Comment by gph82** [comment]
Sorry guys, willrepor t soon, now I cant

**Comment by gph82** [comment]
I'm sorry @hainm but still no joy
![screenshot-2017-11-9 untitled](https://user-images.githubusercontent.com/7518004/32611524-39c8701e-c566-11e7-92c1-249094181cd8.png)

**Comment by gph82** [comment]
Which is weird, because the argument has to be "representation" (and not "representations") for it to even work. In the docu https://github.com/arose/nglview#representations

**Comment by hainm** [comment]
thanks for checking out. I think it works as expected. You can not pass representations to an empty widget (due to technical issue).

**Comment by hainm** [comment]
For the 'representations", and "representation": Yeah, my English :D

**Comment by gph82** [comment]
;) off-topic: can we get a conda-forge release for version 1.0?

**Comment by hainm** [comment]
no, we are using bioconda

```
conda install nglview=1.0 -c bioconda
```

**Comment by marscher** [comment]
the problem which arises here is that we can not build molPX on conda-forge, because it depends on a newer version of nglview. I'm not aware of any method to temporarily add bioconda during the build process. Even if it is possible I don't think it is recommended.

**Comment by hainm** [comment]
that's you guys issue, not nglview. I not sure why very strict about not using "bioconda".  It always makes sense to have a bio-related package like nglview go to bioconda.

What's the deal about simply adding '-c bioconda' to your command?

**Comment by marscher** [comment]
The build process on conda-forge adds only conda-forge and defaults as channels to get its dependencies from. If we would starting mixing other channels during build-time, we can not guarantee that we would also mess up other dependencies than nglview. If I remember correctly there was a problem with bioconda build pipeline checking if the package version is already available on cf and denied to build it "again". So if we would update the existing nglview package on cf right after you have done it on bioconda, we would not interfere with you, right?

**Comment by hainm** [comment]
> So if we would update the existing nglview package on cf right after you have done it on bioconda, we would not interfere with you, right?

Yes, go ahead building thing in conda-forge once we have nglview in bioconda. thanks.

**Comment by marscher** [comment]
alright, problem solved, thank you!
