### ISSUE TITLE
Custom coloring of residues

### ISSUE THREAD

**Issue by surgebiswas** [arose/nglview#714]
I'm trying to color each residue in a structure according to a list of colors. I am trying to replicate the demo in issue #492 . I copied and pasted the code, but the demo structure remains blue.

I've installed nglview using `pip install nglview==1.0.b2`.

**Comment by hainm** [comment]
Can you post your notebook screen? Thx

**Comment by hainm** [comment]
never mind, I can reproduce this issue.

<img width="1276" alt="screen shot 2017-10-26 at 7 40 24 pm" src="https://user-images.githubusercontent.com/4451957/32081816-8fb98ab2-ba85-11e7-83ef-1c93e383952b.png">

**Comment by hainm** [comment]
@arose  oh boy, `ColorMakerRegistry` was renamed to `ColormakerRegistry`

I should add a notebook test for this. (uhm, actually it's intention not to test private (experimental) method)).

**Comment by arose** [comment]
sorry, things like that will be caught by the type checker once typescript is used throughout...

**Comment by hainm** [comment]
Can you confirm ngl expose that now? I change Maker to maker but does not seem to work.

**Comment by hainm** [comment]
never mind again. Make it work. 

<img width="782" alt="screen shot 2017-10-26 at 8 24 58 pm" src="https://user-images.githubusercontent.com/4451957/32082748-c328a436-ba8b-11e7-912e-b54cb2f73d24.png">

**Comment by surgebiswas** [comment]
What should I do then at this point to make it work? Or should I wait for an update from you? Thanks for the quick responses.

**Comment by hainm** [comment]
yeah, just wait for me. will try to commit code today.

**Comment by hainm** [comment]
should be available in 1.0.b7 now. Please try it again. Note that this is private function and subjected to change. Feel free to reopen this issue if you get trouble again. thanks.

**Comment by surgebiswas** [comment]
Looks like its working now. Great work and again, thanks for the quick responses!

**Comment by jbloom** [comment]
I'm just curious about the `_set_color_by_residue` method. Since it begins with an underscore does that mean we should not use this method, or is it something you plan to maintain for the foreseeable future?

**Comment by hainm** [comment]
hi @jbloom, yeah, it's subjected to change in the future. Please treat it as a sandbox.

**Comment by jbloom** [comment]
Hi @hainm, thanks. One other question: is there a straightforward way to map the residue numbers as they appear into the PDB (and as they function in commands such as `add_spacefill`) to the residue **indices** that are used in `_set_color_by_residue`?

**Comment by hainm** [comment]
> is there a straightforward way to map the residue numbers as they appear into the PDB

@jbloom  unfortunately, there's not.

**Comment by hainm** [comment]
@jbloom  oh, you can use the private (yeah, not public yet) class `_ColorScheme` for basically any custom color.

https://github.com/arose/nglview/pull/755


<img width="1171" alt="screen shot 2018-10-27 at 1 01 21 pm" src="https://user-images.githubusercontent.com/4451957/47607032-f91f0580-d9e8-11e8-8962-ffbdfb277c85.png">

**Comment by jbloom** [comment]
@hainm: This `_ColorScheme` is perfect for my needs, thanks!
