### ISSUE TITLE
nglview from  Julia Notebook

### ISSUE THREAD

**Issue by cortner** [arose/nglview#716]
This is not an issue as such but I am asking for advise. I found [this issue](https://github.com/jupyter-widgets/ipywidgets/issues/541) where an `nglview` developer asked about the `Widget Javascript not detected` error message, which I am getting when trying to call `nglview` from Julia.

I am trying the following:
```julia
@pyimport nglview as nv
@pyimport IPython.display as ipydisp
ipydisp.display(nv.show_ase(si)).  # `si` lives is Python and is an ASE Atoms object
```
this gives the error message
```
Widget Javascript not detected.  It may not be installed or enabled properly.
```

I appreciate this is not an `nglview` issue, but I was hoping you can give me a pointer what the problem might be.
  
- Version report

```
Fuji:~ ortner$ python -c 'import nglview; print(nglview.__version__)'
0.6.5
Fuji:~ ortner$ python -c 'import ipywidgets; print(ipywidgets.__version__)'
6.0.0
```

**Comment by hainm** [comment]
hi, this is the ipywidgets in Julia lang issue and I think you should open this in their repo. https://github.com/jupyter-widgets/ipywidgets

good luck.

**Comment by hainm** [comment]
The issue here is that I am not sure ipywidgets in Julia supports 3rd party widget like nglview.

**Comment by cortner** [comment]
Thanks, I'll do that.
