### ISSUE TITLE
smoothing trajectory

### ISSUE THREAD

**Issue by hainm** [arose/nglview#72]
does NGL have it yet?

**Comment by hainm** [comment]
NGL does but only for its trajectory.

**Comment by arose** [comment]
Indeed, eventually it would be good to reuse the Trajectory class from NGL instead of rebuilding its functionality. It needs some thinking on how to approach it. Maybe it just works be creating a NglviewDatasource (like MdsrvDatasource) that sits between ngl and the widget.

**Comment by hainm** [comment]
yeah, `reuse` is right approach. I will try to read NGL code if you're busy to work on other stuff.

**Comment by arose** [comment]
Just a DataSource wont work, a subclass of Trajectory is needed, see for example https://github.com/arose/ngl/blob/dev/js/ngl/trajectory.js#L968

**Comment by arose** [comment]
I will keep it in mind, maybe I find time

**Comment by hainm** [comment]
Done now.
