### ISSUE TITLE
Regarding MDAnalysis usage

### ISSUE THREAD

**Issue by cy16f01** [arose/nglview#721]
Hello,
I have installed MDAnalysis, through the guidelines given in the tutorials/manual. But how do i call MDAnalysis, and then work in it..??
1] Every time should i open the terminal containing the specific folder and then type 'Jupyternotebook' to operate on MDAnalysis..?? which opens through internet only...
2] I have installed Sublime text 2 also. but here if i call it as 'import MDAnalysis', the MDAnalysis library is not being executable.
How can i resolve this issue?
Kindly help me out since i am a newbie here...

Thank you.

**Comment by hainm** [comment]
it's more like MDAnalysis issue rather nglview. cc @kain88-de

**Comment by kain88-de** [comment]
@cy16f01 We have an MDAnalysis mailing list where you can ask about using MDAnalysis

https://groups.google.com/forum/#!forum/mdnalysis-discussion

please not that MDAnalysis is a library and not an executable like `ls` or `grep`. You can either use it in an interactive session (e.g. jupyter notebook) or write your own small program that is using MDAnalysis. 

But please ask those questions on our mailing list as this is not related to nglview.

@hainm the issue can be closed
