### ISSUE TITLE
update getting image data from NGL

### ISSUE THREAD

**Issue by hainm** [arose/nglview#729]
issue: https://github.com/ipython/ipython/issues/10982

**Comment by marscher** [comment]
Is this the causing the widget not show the structure any more? I can see kernel activities (blinking icon next to kernel name) during mouse over events, but the structure is invisible.

The browser console gives a 404 error for a generated png.

cc @gph82, @nsplattner

**Comment by hainm** [comment]
no, it's different issue. You might need to downgrade your ipykernel.

https://github.com/arose/nglview/issues/726#issuecomment-356990959

**Comment by hainm** [comment]
(I am assuming you are using release version. It's ok with master branch).

**Comment by marscher** [comment]
thanks for the xref and fixing this!
