### ISSUE TITLE
try jupyterlab official release

### ISSUE THREAD

**Issue by hainm** [arose/nglview#732]
https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906

**Comment by kain88-de** [comment]
I'm having problems using the recent version of nglview from conda-forge with jupyterlab.   The widget is not showing at all. The same notebook works when I use the original notebook server.

The only related message I can find in the js log is:
`Error: Object 'jupyter.widget' not found in registry
default.js:1443`

**Comment by hainm** [comment]
Hi, I dont think you can use nglview with lab out of the box for now. Lab requires to build the extension from scratch (at least with v 0.27)

A script is here: https://github.com/arose/nglview/blob/master/devtools/nglview-jupyterlab.sh

**Comment by hainm** [comment]
I think we will publish the nglview lab extension (require npm to build).

**Comment by kain88-de** [comment]
installing the extension by hand with `jupyter labextension install ./jslab` didn't help.

**Comment by hainm** [comment]
I am not sure ipywidgets 7 is compatible with lab 1.0 or not.

The script I posted explicitly specify the versions.

**Comment by kain88-de** [comment]
I forgot to run `$ jupyter labextension install @jupyter-widgets/jupyterlab-manager`. Now the error has changed.

```
Error: Canceled
future.js:155
Could not instantiate widget
manager-base.js:272
Error: Could not create a model.
Stack trace:
r@http://localhost:8888/lab/static/main.9f1bdae72fc1ec2c6c4a.js:1:4577335
utils.js:119
uncaught exception: Module nglview-js-widgets, semver range 0.5.4-dev.27 is not registered as a widget module
Error displaying widget
renderer.js:84
Module nglview-js-widgets, semver range 0.5.4-dev.27 is not registered as a widget module
```

I installed version 0.5.4-dev30 though. This was the newest available on npm. I had to make an explicit choice because the package in the repository requested 0.5.4-dev31.

I have some time tomorrow to test everything in a explicit environment. I currently was a bit daring and setup everything in my main environment. There is a chance this has messed things up as well.

**Comment by hainm** [comment]
good luck with your trying. I've spent lot of times to make nglview work
with specific ipywidgets and jab version (wanna cry when I got that work
:D).

**Comment by kain88-de** [comment]
Yeah I will first try with bgplot. This should have a higher chance of working.

**Comment by hainm** [comment]
@kain88-de this is the recipe that works for me. Hopefully that works for you too

```
conda create -n lab python=3.6 jupyterlab=0.31.12 -y
source activate lab
pip install nglview==1.1.2
nglview enable # might need this to enable nglview-js-widgets extension for notebook
conda install ipywidgets=7.1.2 -c conda-forge
jupyter-labextension install @jupyter-widgets/jupyterlab-manager@0.33.2
jupyter-labextension install nglview-js-widgets@1.1.2
```

**Comment by hainm** [comment]
https://github.com/arose/nglview/tree/4a5e86b2519861d53238739bd402d33599f0e0b9/docs/nglview-jupyterlab

**Comment by kain88-de** [comment]
workds thanks
