### ISSUE TITLE
NGLWidget initial representation is ignored

### ISSUE THREAD

**Issue by pwrose** [arose/nglview#734]
The initial representation parameter is ignored.
<img width="601" alt="screen shot 2018-03-26 at 4 48 37 pm" src="https://user-images.githubusercontent.com/3911696/37939266-bb7e053a-3116-11e8-8a9f-7cc476fced42.png">

**Comment by hainm** [comment]
thanks. This is a known bug.

**Comment by marscher** [comment]
And is it hard to fix?

**Comment by hainm** [comment]
I don't think it's hard. Just because I am having little time for nglview now.

**Comment by hainm** [comment]
hi @pwrose, there is a work around below
```
import nglview as nv

s = nv.adaptor.FileStructure(nv.datafiles.PDB)

initial_repr = [
    {"type": "line", "params": {
        "sele": "protein", "color": "residueindex"
    }}
]

v = nv.NGLWidget(s)
v.representations = initial_repr
v
```

<img width="1145" alt="screen shot 2018-07-22 at 2 49 55 pm" src="https://user-images.githubusercontent.com/4451957/43048995-862a0730-8dbe-11e8-8f1e-5f7c712c21fa.png">

**Comment by hainm** [comment]
> And is it hard to fix?

@marscher 

I've checked the code and "yes, it's not easy to fix".

PS: Kind of funny since

```python
v = nv.NGLWidget(s)
v.representations = initial_repr
```

 works fine while

```python
v = nv.NGLWidget(s, representations=initial_repr)
```

does not. The difference here is that in the former case, the Widget is already initialized and we can update the representations.

**Comment by hainm** [comment]
uhm, I found that `representations` should be plural in this case. 
In @pwrose post, it's `representation`: https://github.com/arose/nglview/issues/734#issue-308775245

So it's not an issue here. (This is a known limitation in the design of nglview where we allow `kwargs` in `NGLWidget.__init__`

The example below works as expected with `nglview v1.1.9` if using `representations` (plural).

<img width="1145" alt="screen shot 2019-03-03 at 5 31 57 pm" src="https://user-images.githubusercontent.com/4451957/53702946-43baef00-3dda-11e9-832c-667a62c5dfa7.png">
