### ISSUE TITLE
Problem rendering PDB 4ZWE

### ISSUE THREAD

**Issue by pwrose** [arose/nglview#735]
The display for 4ZWE is blank. This structure has multiple biological assemblies. Perhaps the issue is related to that?
<img width="430" alt="screen shot 2018-03-26 at 5 17 20 pm" src="https://user-images.githubusercontent.com/3911696/37939814-e043ddb0-3119-11e8-81e2-672d0a90fe06.png">

**Comment by hainm** [comment]
I think it's fixed in nglview 1.1.2

<img width="1177" alt="screen shot 2018-03-26 at 8 43 22 pm" src="https://user-images.githubusercontent.com/4451957/37940388-5c729856-3136-11e8-9e00-9bd04771833a.png">

**Comment by pwrose** [comment]
This issue is related to the iopub data rate (see below). It works if I
set:

-NotebookApp.iopub_data_rate_limit=10000000

W 18:35:05.359 NotebookApp] 404 GET
/notebooks/a4c733ec4baef9ad3896d4e34a8a5448.png (::1) 9.25ms referer=
http://localhost:8888/notebooks/ChainSelectionIssue.ipynb

[W 18:35:05.529 NotebookApp] IOPub data rate exceeded.

    The notebook server will temporarily stop sending output

    to the client in order to avoid crashing it.

    To change this limit, set the config variable

    `--NotebookApp.iopub_data_rate_limit`.

**Comment by hainm** [comment]
I see. It's notebook thing so there's nothing we can do. cheers.
