### ISSUE TITLE
Consider using the upstream play widget?

### ISSUE THREAD

**Issue by SylvainCorlay** [arose/nglview#739]
Did you consider using the upstream `play` widget instead of reimplementing on in nglview?

Or is there a feature that you are missing in a combination of the play widget and a slider?

**Comment by hainm** [comment]
hi,

We are currently using play widget from jquery-ui and it was done long time before the upstream `play` exists. Since thing just work so we hesitate to switch over. 

There are several features that I like the play widget in jquery-ui
- It attaches to NGL widget in full screen mode. I was able archive the same thing with ipywidget's Player in the past with Proxy widget but it (Proxy) does not exist anymore.
- I get used to Play/Paused in the same button but it's just a habit, no big issue here.

**Comment by hainm** [comment]
But I think I will give the upstream `play` a try someday. It would be great if people are using the same widget and make suggestion/improvement.

**Comment by hainm** [comment]
oh, I want to stress that making ipywidgets working in full screen mode is a big win for nglview.
I mentioned this a while ago. https://github.com/jupyter-widgets/ipywidgets/pull/979#issuecomment-300601761

**Comment by hainm** [comment]
> It attaches to NGL widget in full screen mode. I was able archive the same thing with ipywidget's Player in the past with Proxy widget but it (Proxy) does not exist anymore.

Another solution:

<img width="783" alt="Screen Shot 2019-06-08 at 12 08 16 AM" src="https://user-images.githubusercontent.com/4451957/59141830-d6db6600-8981-11e9-9343-856d17e3d7e6.png">

Code


```python
from ipywidgets import *
import nglview as nv
import pytraj as pt

traj = pt.load(nv.datafiles.XTC, nv.datafiles.PDB)
view = nv.show_pytraj(traj)
view
```


    NGLWidget(count=51)



```python
player = Play(max=view.count-1, interval=100)
slider = IntSlider(max=view.count-1)
jslink((player, 'value'), (slider, 'value'))
jslink((player, 'value'), (view, 'frame'))

box = HBox([player, slider])
```


```python
def on_display(w):
    c = """

    var pe = document.getElementsByClassName('what')[0]

    pe.style.position = 'absolute'
    pe.style.zIndex = 100
    pe.style.top = '10%'
    pe.style.left = '10%'
    this.$container.append($(pe))
    this.$player.hide();
    """
    view._execute_js_code(c)
```


```python
box.add_class('what')
box.on_displayed(on_display)
box
```


    HBox(children=(Play(value=0, max=50), IntSlider(value=0, max=50)), _dom_classes=('what',))

**Comment by hainm** [comment]
should be done in https://github.com/arose/nglview/pull/828

thanks @SylvainCorlay  for your suggestion. I understand more about ipywidgets's frontend code and am very happy to make this change.
