### ISSUE TITLE
add hide/remove reps

### ISSUE THREAD

**Issue by hainm** [arose/nglview#74]
nice to have

**Comment by hainm** [comment]
Need to use uuid?

**Comment by arose** [comment]
Using uuid is a good id, I haven't documented that yet, but that should become party of the public api.

**Comment by arose** [comment]
you mean component.uuid, right?

**Comment by hainm** [comment]
> you mean component.uuid, right?

yeah.

**Comment by hainm** [comment]
proposed syntax

```python
view.remove_cartoon(component=0)
view.component_0.remove_cartoon()
```

**Comment by hainm** [comment]
did it. closed now. phew.
