### ISSUE TITLE
cannot run npm install

### ISSUE THREAD

**Issue by yseif** [arose/nglview#741]
I just downloaded nglview using the git clone command and have gone through the steps outlined in the installation section.

I tried to run npm install (also just installed npm) and got the following error:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nglview-js-widgets@1.1.2 prepublish: `webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nglview-js-widgets@1.1.2 prepublish script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nglview-js-widgets package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nglview-js-widgets
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nglview-js-widgets
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yara/nglview/js/npm-debug.log

Also, if I try to use nglviewer on jupyter notebook no structural images appear.

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)' --> 1.1.1
python -c 'import ipywidgets; print(ipywidgets.__version__)'--> [7.0.0]
```

**Comment by hainm** [comment]
hi, do you need to change the files in js/ folder? If not, you don't need "npm install"; just `python setup.py install` is sufficient.

**Comment by yseif** [comment]
I already ran this but when I run:

import nglview
import ipywidgets
view = nglview.show_pdbid("3pqr")
view

I can't see any structure.

**Comment by yseif** [comment]
Just to clear things up, I ran on the bash the following commands:

 git clone https://github.com/arose/nglview
    cd nglview
    python setup.py install
 And they worked just fine.

I exited the terminal and restarted my ipython notebook and then ran 

import nglview
import ipywidgets
view = nglview.show_pdbid("3pqr")
view

and could still not see any structure

**Comment by yseif** [comment]
Oh and I also ran:

python -m ipykernel install --sys-prefix
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix nglview

but had to do them on sudo.

**Comment by hainm** [comment]
What does the browser console say?

**Comment by yseif** [comment]
Enabling notebook extension nglview-js-widgets/extension...
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 386, in _set_nbextension_state_python
    for nbext in nbexts]
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 351, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/usr/local/lib/python2.7/dist-packages/notebook/config_manager.py", line 108, in update
    self.set(section_name, data)
  File "/usr/local/lib/python2.7/dist-packages/notebook/config_manager.py", line 97, in set
    f = open(filename, 'wb')
IOError: [Errno 13] Permission denied: u'/usr/etc/jupyter/nbconfig/notebook.json'

**Comment by hainm** [comment]
You mentioned that you needed to use sudo. Does that help?

Another unfavorable way is to use `--user` to install the extension in your
home folder. But this would cause much trouble if you want to install newer
nglview version.

**Comment by hainm** [comment]
What does the web browser console say? (in chrome: right click -> Inspect).

**Comment by yseif** [comment]
<div classs? "codMirror-cursors" style = 'visibility: hidden;" > == S0

**Comment by yseif** [comment]
Here you go!

**Comment by hainm** [comment]
I don't see anything. Please upload the image directly to github page, not
from the email.

**Comment by hainm** [comment]
@yseif what's the status of this issue?

**Comment by hainm** [comment]
ok, so I go ahead closing this issue. Do feel free to reopen it.

**Comment by hainm** [comment]
Hi, I think it's typical error if you have outdated and newer nglview version.
https://github.com/arose/nglview/issues/726#issuecomment-365341198
https://github.com/arose/nglview/blob/master/docs/FAQ.md

> A friend in lab managed to get it to work for him but he had to use sudo to log into his jupyter notebook and run nglviewer. I was wondering if there is a way to avoid that.

You should never need to use sudo to make nglview work. Please see the FAQ above for solution. In short, try to find any old nglview-js-widgets folder and delete it, then install nglview again.
