### ISSUE TITLE
rotation around z-axis

### ISSUE THREAD

**Issue by ArtVoro** [arose/nglview#743]
python 2.7
nglview 1.1.3 

I can't rotate around z-axis in the viewer. Tested many key kombinations. A look on a web version (http://nglviewer.org/ngl/gallery/index.html) shows that Ctrl+Right Mouse Button rotate around z-axis. However this does not work for me when running in jupyter.

**Comment by arose** [comment]
I suppose the ngl version in the nglview widget needs to be updated. Right @hainm ?

**Comment by hainm** [comment]
@arose  the latest version: "ngl": "^2.0.0-dev.28"
Is this ok?

**Comment by arose** [comment]
I added the z rotation in dev.31

**Comment by hainm** [comment]
ok I will make a new release. thanks.

**Comment by hainm** [comment]
@arose: Have you published the dev.31 yet? I've tried and got below

```
$ npm install ngl@ts2
+ ngl@2.0.0-dev.28
updated 1 package in 1.054s
```

**Comment by arose** [comment]
try npm install ngl@next

**Comment by hainm** [comment]
Done. thanks.

@ArtVoro  Please try nglview v.1.5 via `pip install nglview`, you might need also "nglview install && nglview enable" to upgrade the JS stuff. Let me know if that helps your issue. Cheers.

<img width="1173" alt="screen shot 2018-07-21 at 3 04 29 pm" src="https://user-images.githubusercontent.com/4451957/43039248-654ecbd0-8cf7-11e8-8bd7-7280ade9a2f4.png">

**Comment by ArtVoro** [comment]
did the upgrade and can rotate around the z-axis with Ctrl+Right Mouse Button now. Thanks!!!
