### ISSUE TITLE
disable (some) bonds in representation

### ISSUE THREAD

**Issue by ArtVoro** [arose/nglview#744]
@arose 

some representations (e.g. ball and stick, licorice) show connections (labeled as bonds) as thick lines. is it possible to disable some specific bonds in the representation?

![picture](https://user-images.githubusercontent.com/39726533/42938732-9642979e-8b53-11e8-9caf-13a5de55110a.png)

**Comment by hainm** [comment]
can you please post structure + code example? thanks.

**Comment by arose** [comment]
If you defined them as CONNECT in pdb or struct_conn in mmcif then they are bonds and NGL will display them as such. There is no way to not show them if they are in the file.

**Comment by ArtVoro** [comment]
ok i just deleted them from the topology.
