### ISSUE TITLE
access trajectory slider widget

### ISSUE THREAD

**Issue by ArtVoro** [arose/nglview#745]
is the trajectory slider (next to the 'play/pause' button) a widget like from pywidgets? how can i access it?

**Comment by hainm** [comment]
sorry you can't. 

nglview is use jquerry-ui
https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L495

what do you have in mind?

**Comment by ArtVoro** [comment]
i want to see the current frame & time, which is displayed in the viewer.
atm i have a button which gets the frame from <...>.frame. after that it looks up the corresponding time and updates the frame and time on a widget. i want to get rid of this clicking and make it so it auto-updates in a convenient way.

**Comment by hainm** [comment]
how's about `view.frame = something`?

**Comment by ArtVoro** [comment]
thats how you set the frame

**Comment by hainm** [comment]
what's the difference between frame and time in your case? saying your trajectory have 100 frames, so just compute time based on the frame index.

**Comment by ArtVoro** [comment]
yes there is no deal with time or frame. however, as posted above, i already can get the values for frame and time, but i have to click a button right now (i want to see this information when i see the trajectory).
if the slider was a pywidget i would have solved my 'problem' already. but now i have to figure out a convenient way to update the display of frame/time without pressing buttons.

**Comment by hainm** [comment]
Did you try to use `view.frame = something` (replace something by your desired frame/time).

**Comment by hainm** [comment]
![test](https://user-images.githubusercontent.com/4451957/43342260-1b9f15fe-91b0-11e8-881b-6968d26f27d8.png)

**Comment by ArtVoro** [comment]
i think you dont understand what i try to do :) i want sth like: 
```python
display(view, FRAME , TIME)
```
where view is the player from nglview, FRAME is a widget (e.g. textwidget from pywigets) showing the current frame of the player and TIME a widget showing the corresponding time.  Now when i either press the play button or jump around in the trajectory with the slider or via view.frame= something i want that FRAME and TIME are updated automatically.

**Comment by hainm** [comment]
uhm, why didn't you just say that from the beginning. :)

Try 
```python
from traitlets import link

link((view, 'frame'), (your_own_widge, 'your_attribute'))
```

Search `link` in this file to see example: https://github.com/arose/nglview/blob/master/nglview/player.py

**Comment by ArtVoro** [comment]
i really tried to explain it but after a long day you cant think clear anymore i guess :D
thank you for your suggestion, i will take a look tomorrow :)
