### ISSUE TITLE
ViewerEditor cannot be accessed with amber18

### ISSUE THREAD

**Issue by ushaviswana** [arose/nglview#747]
The ViewerEditor is working with amber16 and not with amber18. The structure of the files for the pdb4amber is different in both versions (visualizer.py inside sandbox folder in amber18).

**Comment by hainm** [comment]
hi, yeah. That's intention to NOT over-complicate pdb4amber. I will try to make another package for it. Thanks for your interest in this (thought no one bothers trying :D).

**Comment by ushaviswana** [comment]
I am working on a project with Prof. Case and Prof. Schafmeister. I was trying to understand how to use nglview with jupyter notebook and was going through the examples and came across this. I asked Prof. Case and he showed me that you can be notified by raising an Issue here. Thanks for getting back. Looking forward to exploring more.

**Comment by hainm** [comment]
hi @ushaviswana, I've wrapped up a toy repo here: https://github.com/hainm/moledit

The notebooks in https://github.com/hainm/moledit/tree/master/notebooks should work with ambertools 18. This is absolutely a sandbox. Cheers.
