### ISSUE TITLE
nglview.widget.__frontend_version__ incorrectly set

### ISSUE THREAD

**Issue by milos-popovic** [arose/nglview#750]
In current (1.1.6) pip and conda releases, the nglview.widget.\_\_frontend_version\_\_ is incorrectly set to '1.1.5', resulting in an error when trying to load the extension in the JupyterLab. When I change this to '1.1.6' the JupyterLab widgets starts working without problems.

Master branch already has this change included, however it's not deployed to either pip or conda. Updating the release packages would help everyone using JupyterLab.

**Comment by hainm** [comment]
thanks for reporting. We will make a release soon. cheers.

**Comment by hainm** [comment]
@milos-popovic  please try pip version 1.1.7 and let us know if that helps.

**Comment by milos-popovic** [comment]
Tested 1.1.7 from pip and it works with JupyterLab without problems.

**Comment by milos-popovic** [comment]
PS: Thanks!
