### ISSUE TITLE
NGL widget does not appear. 

### ISSUE THREAD

**Issue by sperezconesa** [arose/nglview#752]
Hello,
I cannot see the nglwindow in the jupyter notebook. I have tried the wiki suggestions and installed it from scratch but nothing... The screenshot might be also helpfull.
![screenshot_20181015_162235](https://user-images.githubusercontent.com/27727343/46956947-d1e64100-d096-11e8-8edc-76b587d063b8.png)

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)' 
1.1.6
python -c 'import ipywidgets; print(ipywidgets.__version__)' 
7.4.2
```

**Comment by hainm** [comment]
hi,

can you also report below
- ngl version
```
view._ngl_version
```

- In JS console, expand the `Viewer` tab, `Error` tab.

**Comment by sperezconesa** [comment]
If I do 
```
view._ngl_version
output:
''
```
I don't know where the JS console is or how to reach those tabs. On web stuff I am a nearly absolute ignorant.

**Comment by hainm** [comment]
> I don't know where the JS console is or how to reach those tabs. On web stuff I am a nearly absolute ignorant.

That's the right section (RED color) in your screenshot.

**Comment by sperezconesa** [comment]
Ah got it! hahaha
![screenshot_20181015_165212](https://user-images.githubusercontent.com/27727343/46958835-04923880-d09b-11e8-85fd-acde727f06a1.png)
![screenshot_20181015_165302](https://user-images.githubusercontent.com/27727343/46958837-052acf00-d09b-11e8-90b6-0a9a69f4ece6.png)

**Comment by sperezconesa** [comment]
In case it is relevant. The jupyter server is installed in a computation cluster which has no GPU or things like that. It is a anaconda instalation.

**Comment by hainm** [comment]
can you try to activate nglview? 

```
nglview --enable
```

**Comment by sperezconesa** [comment]
Just in the bash terminal? I get:
usage: nglview [-h] [-c CRD] [--browser BROWSER] [-j JEXE]
               [--notebook-name NOTEBOOK_NAME] [--port PORT] [--remote]
               [--clean] [--auto] [--symlink]
               [command] [traj]
nglview: error: unrecognized arguments: --enable

I had previously done during the installation: 
jupyter-nbextension enable nglview --py --sys-prefix

**Comment by hainm** [comment]
my bad, should be `nglview enable`, but this should be equal to what you did with `jupyter-nbextension enable nglview --py --sys-prefix`.

I have never seen your issue before so It might take times.

**Comment by sperezconesa** [comment]
I am happy to be helped at your convinience :)

I have rerun the 
```print(view._ngl_version)
2.0.0-dev.33
```
I don't understand why the dev version has been installed I just used: 
```
  conda config --add channels conda-forge 
  conda install nglview -c bioconda
```

**Comment by sperezconesa** [comment]
Hello,
Ok. Now it is working!!
Thanks a ton! :)
Sergio

**Comment by hainm** [comment]
kool.

**Comment by dafwb** [comment]
![Screenshot_20200716_101330](https://user-images.githubusercontent.com/55759194/87645026-34c5aa00-c74d-11ea-89b2-9174cb795275.png)
Somehow I have the same error, but don't understand the solution. 

Versions:
python -c 'import nglview; print(nglview.__version__)' 
1.1.7
python -c 'import ipywidgets; print(ipywidgets.__version__)' 
7.5.1

Do you have an idea how to fix this?
