### ISSUE TITLE
Empty view on javascript show()

### ISSUE THREAD

**Issue by 2005ai** [arose/nglview#754]
Hi All!
I'm sorry if this is a newbie question, but I would appreciate any guidance.
I use ngl.js to show a protein structure inside a div, and it works perfectly if I load it together with the entire page:

    <head>
        <script src="ngl.js"></script>
        <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
    </head>
    <body>
          <div id="viewport" style="height:300px; width:300px;">
            <label>It should be some structure here</label>
          </div>
          <script>
            var stage = new NGL.Stage( "viewport" );
				stage.loadFile("rcsb://3DCY").then(function (o) {
				o.addRepresentation("cartoon", {colorScheme: "residueindex"});
				o.autoView();
                });
          </script>
    </body>

However, if I want to show it on click using $("#viewport").show() and style="display:none" it does not work:

    <head>
        <script src="ngl.js"></script>
        <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
        <script>
            $( function() {          
                $("#showit").click(function(){
                    $("#viewport").show();
                });
            });
        </script>
    </head>
    <body>
          <a href="#" id="showit">Show It!</a>
          <div id="viewport" style="height:300px; width:300px;display:none;">
            <label>It should be some structure here</label>
          </div>
          <script>
            var stage = new NGL.Stage( "viewport" );
				stage.loadFile("rcsb://3DCY").then(function (o) {
				o.addRepresentation("cartoon", {colorScheme: "residueindex"});
				o.autoView();
                });
          </script>
    </body>

I guess it's related to resizing of viewport, so I tried to use stage.handleResize():

            var stage = new NGL.Stage( "viewport" );
				stage.loadFile("rcsb://3DCY").then(function (o) {
				o.addRepresentation("cartoon", {colorScheme: "residueindex"});
				o.autoView();
                });
            window.addEventListener( "resize", function( event ){
                stage.handleResize();
            }, false );

but it did not help.

I would appreciate if someone could advise or direct me to related docs.

**Comment by hainm** [comment]
cc @arose, this is a NGL case, not nglview.

**Comment by arose** [comment]
@2005ai I suspect that you have to call `stage.handleResize()` after `$("#viewport").show()`.

**Comment by 2005ai** [comment]
Thank you so much, arose! It works!
