### ISSUE TITLE
nglview.show_file does not work in jupyterlab 0.34.12

### ISSUE THREAD

**Issue by hainm** [arose/nglview#762]
Structure is not shown if showing a file in current folder (using file path rather buffer).

<img width="929" alt="screen shot 2018-11-27 at 10 31 49 pm" src="https://user-images.githubusercontent.com/4451957/49127169-4f0af580-f294-11e8-911a-9b103d5ff761.png">
<img width="408" alt="screen shot 2018-11-27 at 10 32 12 pm" src="https://user-images.githubusercontent.com/4451957/49127171-4f0af580-f294-11e8-832a-7b3ad942a1b8.png">

**Comment by hainm** [comment]
Notebook is ok.

**Comment by jan-janssen** [comment]
@hainm - Is this fixed in 1.1.9 as well?

**Comment by hainm** [comment]
Hi I am not sure. I don’t think it’s nglview issue. Can you try? Thanks.

**Comment by jan-janssen** [comment]
I am using 0.35.4 and there it works just fine with 1.1.9

**Comment by hainm** [comment]
thanks. We're good now.
