### ISSUE TITLE
show_asetraj is broken if we add_unitcell()

### ISSUE THREAD

**Issue by jan-janssen** [arose/nglview#771]
I have the following issue with nglview 1.1.7 and ipywidgets 7.4.2

```
import nglview
from ase.lattice.cubic import FaceCenteredCubic

# Set up a crystal
atoms = FaceCenteredCubic(directions=[[1, 0, 0], [0, 1, 0], [0, 0, 1]],
                          symbol='Cu',
                          pbc=True)

def move_atom_step(atoms, step): 
    atoms.positions[0] = [(step+1)/11 * 1.805, 0., 0.]
    return atoms.copy()

traj = [move_atom_step(atoms=atoms, step=i) for i in range(10)]

nglobj = nglview.show_asetraj(traj)
# nglobj.add_unitcell()
nglobj
```

The animation of the trajectory works fine, but when I add a unit cell `nglobj.add_unitcell()` the atoms are no longer moving. So to me it seems like adding the unit cell breaks the animation.

**Comment by hainm** [comment]
please upgrade to 1.1.8 version. We fixed the issue. Thanks.

Related: https://github.com/arose/nglview/issues/742

**Comment by jan-janssen** [comment]
I tired to enable the same on Jupyterlab - created the corresponding pull request https://github.com/arose/nglview/pull/772 

But somehow on Jupyterlab the issue seems to remain even though it is working fine in the jupyter notebooks.

**Comment by hainm** [comment]
@jan-janssen  can you please doublecheck the ngl version?

```
view._ngl_version
``` should be `2.0.0-dev0.34`

**Comment by jan-janssen** [comment]
When I run: 
`jupyter labextension install ~/nglview/js`
then the resulting version always includes ngl 2.0.0 - is it possible that node.js does not support the `-dev0.34` format?  I see the 'index.js' in static is build with `2.0.0-dev0.34` but it seems it is not build automatically.

**Comment by hainm** [comment]
> For future version you might like to use the `next` tag in the `package.json`, but for now I prefer a fixed version.

I prefer the fixed version since I know what's going on. Thanks for the detail explanation above.
