### ISSUE TITLE
2 different representiations not showing when importing from MDAnalysis

### ISSUE THREAD

**Issue by martinsiron** [arose/nglview#775]
![image](https://user-images.githubusercontent.com/31899330/53531765-03413580-3aa9-11e9-8886-837775954093.png)

However my two representations aren't showing up in two different colors.

**Comment by hainm** [comment]
I am not sure if `type 1` is a legit selection in NGL.

**Comment by hainm** [comment]
Please check here: http://nglviewer.org/ngl/api/manual/selection-language.html

**Comment by martinsiron** [comment]
> I am not sure if `type 1` is a legit selection in NGL.

I tried using the AtomGroup hydrogen, and palladium as well, and just "1" and "2" and neither worked.

How could I go about displaying two different AtomGroups in 2 different colors?

**Comment by martinsiron** [comment]
> Please check here: http://nglviewer.org/ngl/api/manual/selection-language.html

Thank you! That worked - I just did it by atom ID using the "@1,2,etc" keyword..
