### ISSUE TITLE
axes representation around non-contiguous residues

### ISSUE THREAD

**Issue by cgoliver** [arose/nglview#779]
- Question about usage? Please search your issue here first: https://github.com/arose/nglview/issues/589

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)' #1.1.9
python -c 'import ipywidgets; print(ipywidgets.__version__)' #7.2.1
```
I'd like to draw a box around a selection of residues using the jupyter modules:

```
view.add_representation(repr_type='axes', selection="3,11,34", showBox=True, showAxes=False)
```
Also like [here](https://codepen.io/pen?&editable=true&editors=001)

However, it seems that when the residues are not consecutive, I only get a box around the first residue in the selection.

I was wondering if this is expected behaviour or if I should be passing the selection differently.

While the selected residues are non consecutive in the chain, they are close in space so containing them in a box would still make sense.

Thanks!

**Comment by hainm** [comment]
I think something's wrong with NGL's residue selection.
This  `selection="3,11,34"` only select 1st residue but `selection="3 or 11 or 34"` will do the trick.
@cgoliver: can you please try with `or` above.

@arose is this a bug in NGL?

**Comment by hainm** [comment]
uhm, there should be space between the number
`selection="3, 11, 34" `

**Comment by hainm** [comment]
![1](https://user-images.githubusercontent.com/4451957/55510980-70f2fb00-562d-11e9-98e5-5d3324ecd2aa.png)

**Comment by cgoliver** [comment]
the spaces does it! sorry, since I saw in the manual `residue number range: 3-40 (Note that around the dash - no spaces are allowed)` for a range, I assumed there would be no spaces for the individual residues.
