### ISSUE TITLE
save png

### ISSUE THREAD

**Issue by euhruska** [arose/nglview#781]
Is it possible to save the output of the view as png? I see https://github.com/arose/nglview/issues/12, but don't see any documentation or similar.
I also saw view.render_image(), but no saving options

**Comment by hainm** [comment]
using `view.download_image`?

**Comment by JaimeCarracedo** [comment]
Hi,

I'm trying to save images from jupyter notebook. I need to run it several times (with a loop). The problem is that I can't save mages without display it. Is there a way to save the images without displaying them?

**Comment by hainm** [comment]
hi @JaimeCarracedo there is no way to do that. But you can play with `view.on_display` to introduce the callback after the view is displayed. 

By the way, this post might be helpful to you: https://github.com/nglviewer/nglview/issues/901#issuecomment-697923782
