### ISSUE TITLE
show_mdtraj not showing anything

### ISSUE THREAD

**Issue by euhruska** [arose/nglview#782]
I tried the https://github.com/arose/nglview/blob/master/examples/mdtraj.md example, but nothing is visible.
nglview  1.1.7
ipywidgets 7.4.2
python 3.7.2 | packaged by conda-forge

display image displays a error
![errornglview](https://user-images.githubusercontent.com/9983894/55844954-5e813180-5b05-11e9-9a50-a38bf7b46d4e.PNG)

**Comment by hainm** [comment]
hi, you need to execute each command in different cells. It's asynchronous.
