### ISSUE TITLE
add_component results in 404 error in jupyterlab

### ISSUE THREAD

**Issue by satary** [arose/nglview#783]
While jupyter notebook works just fine, in jupyterlab add_component fails with `VM118:1 GET somepathhere 404 (Not Found)`
It looks like it always looks for the file in the root dir.
![](https://user-images.githubusercontent.com/2101895/56287102-3193d680-6124-11e9-8340-2d32beadfee9.png)

**Comment by satary** [comment]
Update.
But it works just fine with FileStructure object
```
view=nv.show_structure_file('init_charges.pdb')
fs = nv.FileStructure('resources/pot.dx')
view.add_component(fs)
view
```
Weird!

**Comment by hainm** [comment]
Hi, i saw the issue sometimes. Which lab version you are using? Have you tried with latest version yet?

**Comment by satary** [comment]
We are using 0.35.4 (latest in conda-forge). We a running both lab and notebooks via jupyterhub, if it is relevant/

**Comment by hainm** [comment]
> But it works just fine with FileStructure object

here is the context: If user pass a file path in current or subfolder, nglview (backend) is trying to reuse that filepath and pass it to NGL frontend. If the file path is in different folder (e.g: ../), nglview needs to read the file content and send a blob of text/binary to NGL; absolute file path is not accepted in Javascript world. 

So, the `FileStructure` works because nglview always send a blob of text to NGL: https://github.com/arose/nglview/blob/master/nglview/adaptor.py#L44

I am still not clear why using a subfolder (e.g: 'resources/pot.dx') does not work in jupyterlab. weird.

**Comment by satary** [comment]
Thanks for the explanation!
I've moved the file from subfolder to the workdir, but still no luck.
And in the error itself, `VM118:1 GET https://newton.bioeng.ru/jupyter/user/armeev/pot.dx 404 (Not Found)` the path is quite weird, though I have little idea about what it is supposed to be.

**Comment by hainm** [comment]
I don't know either. :( 
Let me do some digging.

**Comment by hainm** [comment]
@satary I've opened an issue in jupyterlab here: https://github.com/jupyterlab/jupyterlab/issues/6218

**Comment by hainm** [comment]
A hacky fix is adding "files/" to filepath in JS.
Basically, change this line
https://github.com/arose/nglview/blob/7f2d56b7069217c18ba49f24f301f2ad46a3485a/js/src/widget_ngl.js#L955

to
```javascript
return this.stage.loadFile("files/" + msg.args[0].data, msg.kwargs) 
```
(From my comment in jupyterlab issue: https://github.com/jupyterlab/jupyterlab/issues/6218#issuecomment-484691884)

**Comment by hainm** [comment]
@satary  Please try the 1.2.0 via pip install and let me know if that fixes your issue. cheers.

<img width="1271" alt="Screen Shot 2019-04-20 at 1 54 28 AM" src="https://user-images.githubusercontent.com/4451957/56453565-446bfe00-6312-11e9-975c-aec730082f5d.png">

**Comment by hainm** [comment]
ah, you need `jupyter-labextension install nglview-js-widgets@1.2.0` too.

**Comment by hainm** [comment]
Just in case you don't know, jupyter-lab has pretty nice feature "Create New View for Output"

<img width="1271" alt="Screen Shot 2019-04-20 at 2 23 09 AM" src="https://user-images.githubusercontent.com/4451957/56453638-5306e500-6313-11e9-8210-3944911895c8.png">
