### ISSUE TITLE
add_component does not display in jupyter-notebook

### ISSUE THREAD

**Issue by njbruce** [arose/nglview#786]
I am seeing a similar but different issue to that reported in  #783 

In my case, I am running in jupyter notebook and nglview.NGLWidget.add_component fails to find files in subdirectories, and always looks in the jupyter root directory. For an example, see here:

https://github.com/njbruce/BugTestNGL/blob/master/failAddComponentNGL.ipynb

nglview.show_structure_file works fine for files in subdirectories.

I am using nglview==1.2.0 and notebook==5.7.8. Both via pip in python 3.7.3

**Comment by hainm** [comment]
thanks. My bad to introduce another bug while fixing the existing one. I can reproduce your error.
Please use nglview==1.1.9 for now. cheers.

**Comment by hainm** [comment]
uhm, v1.1.9 does not help either. That's weird.

**Comment by hainm** [comment]
I know why now: It's because you're changing the initial working path.

```python
# Dowload new file here
fileUrl='http://www.rcsb.org/pdb/files/1hel.pdb'
wget.download(fileUrl, newDir)

os.chdir(jupyterRoot) # update from hainm
print("CURRENT", os.getcwd())
# Try to view file using add component and absolute path - it fails
view1 = nglview.NGLWidget()
component1 = view1.add_component(os.path.join(newDir, '1hel.pdb'))
view1
```

**Comment by hainm** [comment]
So here is the long reason why `nglview` works that way: When you launch the notebook, the javasript code is only allowed to read file in sub directories of your launch folder, not from the ones in your current folder (for security reason).

**Comment by hainm** [comment]
If you still want to change your path, you can use `nglview.FileStructure`

```
component1 = view1.add_component(nglview.FileStructure(os.path.join(newDir, '1hel.pdb')))
```

**Comment by njbruce** [comment]
Thanks for the help and the explanation. It's working correctly now. 

That chdir wasn't necessary in the simple example, but is in the real code, so it's lucky I left it in.

Thanks again!
