### ISSUE TITLE
White canvas with show_mdtraj

### ISSUE THREAD

**Issue by dprada** [arose/nglview#791]
Could anyone please check if show_mdtraj() is working?

For instance, after doing:
```
wget https://files.rcsb.org/view/2LAO.pdb
```

This works to me:
```
import nglview as nv
nv.show_file('2LAO.pdb')
```

But this returns a white canvas:
```
import mdtraj as md
import nglview as nv
md_system = md.load('2LAO.pdb')
nv.show_mdtraj(md_system)
```

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
1.2.0
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.4.2
python -c 'import mdtraj; print(mdtraj.version.full_version)'
1.9.2
```

**Comment by hainm** [comment]
which Linux distribution you're using? 1.1.2 works fine for me in my Mac but it doesn't with my centos-6.

Can you please try the master branch that has the fix https://github.com/arose/nglview/pull/787

**Comment by dprada** [comment]
Thanks!
Ubuntu 18.04.2 LTS. I have a machine Centos-7 to try it also.
I'll report here the result in a while.

**Comment by dprada** [comment]
Great! It works.

Your branch `decode` was deleted. I did not try to implement your modifications in my adaptor.py file to be sure that what I see is the effect of #787... I just tried with today's `arose:master` and it works perfectly.

I am going to close this issue to add a comment in #787.

**Comment by hainm** [comment]
I've release v.1.2.1 on pypi for the fix. It should be available on conda-forge soon. Thanks for testing.
