### ISSUE TITLE
Jupyterlab compatibility 

### ISSUE THREAD

**Issue by jan-janssen** [arose/nglview#801]
I am a bit confused about the newly released version 1.2.2. 

- `js/package.json` still points to 1.2.0 
- as well as in `nglview/widget.py`, `nglview/static/index.js` and `nglview/static/index.js.map`

I tried to keep these settings consistent twice: 

- https://github.com/arose/nglview/pull/773
- https://github.com/arose/nglview/pull/746

So before I open another pull request I wanted to ask if there is a specific reason for this inconsistency?

**Comment by jan-janssen** [comment]
I have to correct myself, it is working this way - even with jupyterlab - but it is still confusing for me as a user why there are different versions for the different parts of nglview.

**Comment by hainm** [comment]
It’s because the js/ code doesn’t change in 1.2.2. And that’s why I forgot to update the version. Anyway to help to remember this? May be add checking to unittest (how?)?

Cheers.

**Comment by hainm** [comment]
But i agree that making the same version for all parts is ideal.

**Comment by hainm** [comment]
Adding `release.py` to check for version mismatch before releasing. Hopefully this issue will be resolved in v2.0. https://github.com/arose/nglview/commit/9d709111f6be1292050bfbf33ee2d59f01d63af3

**Comment by jaimergp** [comment]
I was about to open an issue about this, but I see you are discussing about it here.

Basically, what are the recommended steps to enable NGLView in Jupyter Lab?

I have tried:

```
conda install -c conda-forge nglview
jupyter labextension install nglview-js-widgets
```

It is installed correctly, but then the Widget does not appear. I see that [`nglview-jupyterlab`](https://www.npmjs.com/package/nglview-jupyterlab) also exists. This, however, fails during the installation.

**Comment by hainm** [comment]
Hi

We have an example that might work for you:

https://github.com/arose/nglview/blob/master/devtools/nglview-jupyterlab.sh

**Comment by jan-janssen** [comment]
I use the environment in 
https://github.com/pyiron/pyiron/blob/master/binder/environment.yml
And afterwards I run:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install nglview-js-widgets@1.2.0
```

commonly people forget to install nodejs then the installation of the extension fails.

**Comment by jaimergp** [comment]
@hainm, @jan-janssen, thanks! I was missing `jupyterlab-manager`. With that one I got it to work! This is my current setup:

```
!python -V
!echo 'Node' $(node --version)
!echo 'NPM' $(npm --version)
!jupyter-labextension list
---
Python 3.7.3
Node v12.2.0
NPM 6.9.0
JupyterLab v0.35.6
Known labextensions:
   app dir: /home/user/.local/anaconda/envs/testenv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        nglview-js-widgets v1.2.0  enabled  OK
---
>>> import nglview as nv
>>> nv.__version__
'1.2.2'
```

**Comment by hainm** [comment]
should be ok in v2.0.0. Thanks @jan-janssen  for always checking lab.
