### ISSUE TITLE
coloring lost with `write_html`

### ISSUE THREAD

**Issue by jbloom** [arose/nglview#802]
I am using `nglview` version 1.2.2.

When I try to embed a structure in HTML (as here: https://github.com/arose/nglview/pull/687) any custom coloring I have added is not retained; the molecule is just black.

**Comment by hainm** [comment]
Can you please make a public example and  attach

- htlm file
- code + public structure

so I can reproduce. (i have trier few days ago and worked fine on my Mac).

**Comment by hainm** [comment]
My test on centos 6 + chrome

![1](https://user-images.githubusercontent.com/4451957/57706924-b0e9cc80-7634-11e9-8339-860e7aa15364.png)

![2](https://user-images.githubusercontent.com/4451957/57706932-b515ea00-7634-11e9-9667-f2733b044cdf.png)

**Comment by jbloom** [comment]
I have done this. In the process, I think I figured out what triggers the problem (although now how to fix it). Your example works for me, but it fails if I try to use a custom colorscheme.

I have attached my Jupyter notebook and the two created HTML files.
[color_test.zip](https://github.com/arose/nglview/files/3178623/color_test.zip)

**Comment by hainm** [comment]
> but it fails if I try to use a custom colorscheme.

@jbloom  it makes sense now. I need to investigate further to see if this is a issue from `nglview` or from the frontend [NGL](https://github.com/arose/ngl).

PS: I've looked at your `v2._ngl_repr_dict` and I saw

```
'colorScheme': '0c0a0b70-8b6f-4974-9498-9c6b415d6a50|'
``` 

which is the scheme ID of your customized scheme (that does not exist in serialized code in html file).
This is a technical issue.

**Comment by jbloom** [comment]
Great, thanks for looking into this.

**Comment by hainm** [comment]
@jbloom I have a fix for this issue in #803 but I have not cut a new release yet.
So if you're interested in this, can you please help to confirm if that works for you. Here are the steps

- Install master branch code
- Regenerate your html file with updated code
- Copy the nglview/static/index.js to the same folder having html file and rename it to `nglview-js-widgets.js` to force your html to use the local build.
https://github.com/arose/nglview/tree/master/nglview/static

Here is my test:
<img width="1023" alt="Screen Shot 2019-05-15 at 12 42 36 AM" src="https://user-images.githubusercontent.com/4451957/57749024-60ad5180-76aa-11e9-85ee-1d82f5906ff9.png">

Note:
- You have to provide a `label` (unique scheme name) for your color scheme.
- Treat the color scheme as our playground, otherwise you have to specify a specific nglview version in your production code.

cheers and enjoy.

**Comment by jbloom** [comment]
Perfect, that fixes the color scheme problem. Thanks so much.

One aside that I still don't understand. The PDB that I am using (4o5n) shows one hetero-monomer of a hetero-trimer. The PDB appears to indicate the transformations that need to be applied to this monomer to create the full trimer (https://files.rcsb.org/view/4O5N.pdb).

To my surprise, when I render the PDB with `nglview`, it shows the hetero-trimer (this is actually great). But when I write the html with `write_html`, it just shows the hetero-monomer actually in the PDB file.

This isn't really a problem or a bug; I can deal with it by manipulating the PDB file.

But I was just trying to understand the behavior. Do you know why it works this way: the trimer is rendered in the notebook, but only the monomer is written to HTML?

**Comment by hainm** [comment]
> the trimer is rendered in the notebook, but only the monomer is written to HTML?

I could reproduce this issue. Let me do some digging.

**Comment by hainm** [comment]
@jbloom  Per the monomer issue, I think there is something going on the implementation of the frontend NGL.

Basically, if you print out the `view._ngl_repr_dict`, you will see something like

```
   'assembly': 'default',
   'defaultAssembly': 'BU1',
```

For unknown reason, the `defaultAssembly` is not passed correctly to NGL (or NGL does not respect this input variable).

So for the time being, the reliable approach is to explicitly set the `assembly` value to `BU1`.
Below code should work (tested):

```python
import nglview as nv

v = nv.show_pdbid('4O5N', default_representation=False)
v.add_cartoon('protein', assembly='BU1')
v.add_licorice('not protein', assembly='BU1')
v.center()
v
```

**Comment by hainm** [comment]
The fix is in v2.0 release.

**Comment by jbloom** [comment]
I have one very minor request / question regarding `write_html`. Right now the orientation isn't saved when these are created. I know this is a pretty insignificant issue, but I was hoping to save HTML rendering of the widgets that I could then embed in presentations. Obviously, they can be rotated within the presentations, but it would be super nice if I could just save them in the desired orientation to begin with.

The problem is most clearly illustrated here.

I open the notebook on `mybinder` here and run it to the bottom:
https://mybinder.org/v2/gh/jbloomlab/dms_struct/master?filepath=notebooks/struct_widget.ipynb

I then generate the HTML rendering by adding the following cell at the bottom:
```
import nglview
nglview.write_html('temp.html', [w_surface])
```

This does create the HTML, and I can re-open the HTML in the Jupyter notebook by then adding and running the next cell:
```
from IPython.display import HTML
display(HTML('temp.html'))
```

But note how the orientation is lost.

**Comment by hainm** [comment]
Hi

Does that work if you manually rotate a bit and write html?

**Comment by hainm** [comment]
uhm, not sure why you got the issue. I have not tried your example but here is mine (with a simple notebook).

default
![1](https://user-images.githubusercontent.com/4451957/58264037-25b2ba00-7d4b-11e9-977a-46de065d63ba.png)

after updating camera and write html file
![2](https://user-images.githubusercontent.com/4451957/58264060-306d4f00-7d4b-11e9-96f5-3e33c35a0dc9.png)

* notebook: 
[camera_serialize.ipynb.txt](https://github.com/arose/nglview/files/3212881/camera_serialize.ipynb.txt)

**Comment by hainm** [comment]
A quick fix is explicitly update `_camera_orientation` so it will go to html file.
```
w_surface._camera_orientation = [113.5, 44.09, 180.08, 0,
       -185.38, 23.99, 110.97, 0,
       2.63, -211.51, 50.12, 0,
       -34.66, 25.44, 46.9, 1]
```

Normally, the frontend will send a message for backend to update that.

![4](https://user-images.githubusercontent.com/4451957/58265491-c86c3800-7d4d-11e9-8dc6-4be8a3b46551.png)

**Comment by hainm** [comment]
> Normally, the frontend will send a message for backend to update that.

The code is here: https://github.com/arose/nglview/blob/c3feb91d28d7ad7872634d604d5e02074079f796/js/src/widget_ngl.js#L232
