### ISSUE TITLE
MARTINI visualization

### ISSUE THREAD

**Issue by namitc** [arose/nglview#818]
Is there a way to visualize coarse grained structures using nglview? Right now all I see are spheres  with no bonds.

**Comment by hainm** [comment]
cc @arose

**Comment by arose** [comment]
There is some bond detection for coarse grained structures see http://nglviewer.org/ngl/?script=component/structure-coarseGrained. Did you add a ball&stick representation?

**Comment by hainm** [comment]
thanks @arose
