### ISSUE TITLE
rendering issue for jupyter notebook with remote access

### ISSUE THREAD

**Issue by weiHelloWorld** [arose/nglview#819]
Hi,

I set up a jupyter notebook on a server and access it remotely with a browser.  When I try to render molecular image with nglview it seems to be not working and shows following icon:

<img width="237" alt="Capture" src="https://user-images.githubusercontent.com/6883429/59471272-7d46c180-8def-11e9-9eb3-d33030d0899c.PNG">

I wonder if it is because nglview does not support remote access?

The package versions are:

nglview: 2.1.0
ipywidgets: 7.4.2

Thank you!

**Comment by hainm** [comment]
hi @weiHelloWorld 
you have  to display the view first.

```
# cell 1
view = nv.show_mdtraj(my_traj)
view

# cell 2
view.render_image()
```

PS: is `render_image` is what you want (to get a static image) or do you want to interact with the `view`?

**Comment by hainm** [comment]
e.g:


![tada](https://github.com/arose/nglview/raw/master/examples/images/membrane.gif)

**Comment by weiHelloWorld** [comment]
@hainm Thanks for your reply!  I tried both but neither worked.

**Comment by hainm** [comment]
@weiHelloWorld  may be try this? https://github.com/arose/nglview/issues/785#issuecomment-497091816

**Comment by weiHelloWorld** [comment]
@hainm  That works great!  Thank you so much!
