### ISSUE TITLE
nglview breaks bokeh in JupyterLab

### ISSUE THREAD

**Issue by mcs07** [arose/nglview#825]
When nglview is installed, I have found that bokeh stops working in jupyterlab.

```
from bokeh.io import output_notebook, show
output_notebook()
Loading BokehJS ...
Javascript Error: require is not defined
```
In the console I see:

    Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing

Could this be related to #813? Uninstalling nglview fixes the problem.

Versions:

- nglview 2.1.0 (and previous)
- ipywidgets 7.4.2
- jupyterlab 0.35.6
- bokeh 1.2.0

Installed by:

    conda install nglview=2.1.0 bokeh=1.2.0
    jupyter-labextension install nglview-js-widgets@2.1.0
    jupyter labextension install jupyterlab_bokeh@0.6.3

**Comment by hainm** [comment]
hi, may be because of #813. We will resolve the issue in the next release. thanks.

**Comment by hainm** [comment]
should be fixed in #826 

<img width="1212" alt="Screen Shot 2019-06-21 at 10 13 48 PM" src="https://user-images.githubusercontent.com/4451957/59958272-e2df2180-9471-11e9-804e-35bb6869c4ea.png">

**Comment by hainm** [comment]
@mcs07 please try v2.2.0. Thanks.

**Comment by mcs07** [comment]
Works great, thanks!
