### ISSUE TITLE
Mislabelled Hydrogen Bond

### ISSUE THREAD

**Issue by tonyyzy** [arose/nglview#835]
- Version report
```bash
python -c 'import nglview; print(nglview.__version__)'
2.5.2
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.4.2
```
<img width="636" alt="Screen Shot 2019-07-15 at 13 32 32" src="https://user-images.githubusercontent.com/38984697/61216375-1590d880-a705-11e9-9aa6-e60bcf3ed4f8.png">

As shown above, a hydrogen bond is labeled between nitrogen and oxygen. Not sure if it's the best to report the issue here or NGL.

Edit: I realised this happens commonly in NGL. Is it intentional to display hydrogen bond as between the heavy atoms? I will close this once someone confirms that this is a feature rather than a bug :)

**Comment by hainm** [comment]
Hi Tony, would you mind openning this again jn NGL repo? There are many experts there. Thanks.

**Comment by hainm** [comment]
close this now.
