### ISSUE TITLE
BUG: nglview disables scroll in html emebed

### ISSUE THREAD

**Issue by hainm** [arose/nglview#840]
https://nbviewer.jupyter.org/github/arose/nglview/blob/644fa66a8461b52c01a5e4df4d2a99486b690fea/notebooks/custom_color.ipynb

**Comment by hainm** [comment]
uhm, happens from v2.5.0 (v2.2.0 is fine), where the NGL's GUI is introduced.

**Comment by hainm** [comment]
@arose Any idea why?
It seems that if importing `https://github.com/arose/ngl/blob/master/examples/css/main.css`, the webpage can not be scrolled (Please check the notebook link above). thanks.

**Comment by hainm** [comment]
In `nglview`'s context, whenever a view is created, `nglview-js-widgets` will be required in browser and the `main.css` will be loaded (https://github.com/arose/nglview/blob/9e25a50c8f1438f596b2971ec1dbb30e79a05a68/js/src/widget_ngl.js#L20)

**Comment by dwhswenson** [comment]
I reproduce this bug if using `nbconvert` locally, but interestingly, it doesn't seem to happen when I use `nbsphinx`. (However, I did have to sort out a CSS clash with the syntax highlighting.)

You can try it yourself by checking out dwhswenson/contact_map#62 and running `make html` from the `docs/` directory. Under the examples, it's the notebook on plotting drug binding hotspots.

I haven't looked to debug the difference -- my main goal was to have NGLView running in our sphinx docs, and now it does!

**Comment by hainm** [comment]
thanks, I've tried. 

> my main goal was to have NGLView running in our sphinx docs, and now it does!

yay, cool enough.

**Comment by hainm** [comment]
likely due to this line: https://github.com/arose/nglview/blob/9e25a50c8f1438f596b2971ec1dbb30e79a05a68/js/src/css/main.css#L39

(https://stackoverflow.com/questions/20038673/my-html-page-is-not-scrolling-in-browsers)

**Comment by hainm** [comment]
should be fixed in v2.6.8
