### ISSUE TITLE
nglview example does not show any image

### ISSUE THREAD

**Issue by alex4200** [arose/nglview#846]
Using `nglview` 2.7.1 the simple example is not working for me. Instead of seeing a 3D graphics I just see an output `NGLWidget()`:

![Screenshot 2019-09-06 at 08 51 18](https://user-images.githubusercontent.com/12729291/64406991-87412f00-d083-11e9-9dc0-1d0ec02ae65c.png)

How can this be fixed or further investigated?

**Comment by hainm** [comment]
hi, can you open JS console (In Chrome: Right click -> Inspect -> Console) and what's error message in the console?

**Comment by hainm** [comment]
may be try: `jupyter-nbextension enable nglview --py --sys-prefix` first.

**Comment by alex4200** [comment]
In the console I see errors like the following: 

```
WrappedError {stack: "Error: Couldn't create a model.↵    at new Wrapped…s-widgets/extension.js?v=20190905210228:32031:30)", message: "Couldn't create a model.", error_stack: Array(3)}
error_stack: Array(3)
0: Error: Class undefined not found in registry at https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:31997:25 at new Promise (<anonymous>) at Object.loadClass (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:31958:13) at WidgetManager.ManagerBase.new_model (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:32336:32) at WidgetManager.ManagerBase.handle_comm_open (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:32221:18) at https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/static/notebook/js/main.min.js?v=6a166b31c5a20f809e44ec2d50e40412:23222:36
1: Error: Couldn't create model at new WrappedError (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:31924:22) at https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:32352:34
2: Error: Couldn't create a model. at new WrappedError (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:31924:22) at promiseRejection (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:32031:30)
length: 3
__proto__: Array(0)
message: "Couldn't create a model."
stack: "Error: Couldn't create a model.↵    at new WrappedError (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:31924:22)↵    at promiseRejection (https://jupyterhub.humanbrainproject.org/jupyterhub/user/305933/nbextensions/jupyter-js-widgets/extension.js?v=20190905210228:32031:30)"
__proto__: Error
```

**Comment by hainm** [comment]
Does ipywidgets work at all?

```
from ipywidgets import Text
Text("Hello")
```

**Comment by alex4200** [comment]
1. I have reloaded the notebook, but the error in the console is the same
2. The output from the `ipywidgets` command is: `Text(value='Hello')` (not sure if that is the expected output)

**Comment by hainm** [comment]
No, it’s not expected output. There’s something wrong with your ipywidgets.

Please try this also:
jupyter nbextension enable --py widgetsnbextension

Close your notebook and reload so the JavaScript code will be correctly loaded.

**Comment by alex4200** [comment]
Even with that, reloading the browser page, and executing the `Text("Hello")` command again, I still get the same output.

**Comment by hainm** [comment]
I suggest to try with your personal computer first. 

When you said “reload”, did you kill the kernel and it was reload the browser?

**Comment by alex4200** [comment]
I did restart the kernel and reload the page. But still the same result. 

On a local computer with a fresh environment the example is working.

**Comment by hainm** [comment]
so I guess this is an issue with your `https://jupyterhub.humanbrainproject.org` or `ipywidgets`.
I would open an issue in their repo for debugging: https://github.com/jupyter-widgets/ipywidgets/issues

**Comment by alex4200** [comment]
Ok, thanks

**Comment by hainm** [comment]
close this since it's not a nglview's issue.

**Comment by muammar** [comment]
What worked for me was this: 

```
rm $PATH_TO/share/jupyter/nbextensions/nglview-js-widgets/
jupyter labextension install nglview-js-widgets
```
