### ISSUE TITLE
selection of residues with indices > 100 doesn't work 

### ISSUE THREAD

**Issue by gnik2018** [arose/nglview#855]
I seem to have a problem with residue selections. I'm working in a jupyter notebook inside Firefox on Windows 10. Everything is pip installed.  Selections containing only residues with indices > 100 seem to default to the whole protein as demonstrated below. Colour scheme: blue for the entire protein, red for the selection. PDB ID is 2z8x. 
![2z8x_sel_1](https://user-images.githubusercontent.com/56831705/67211200-44a89b80-f412-11e9-92d7-32fd9517a0c3.png)
now with residue 100 added:
![2z8x_sel2](https://user-images.githubusercontent.com/56831705/67211258-5a1dc580-f412-11e9-9b4b-8918b000238c.png)
now with residue 99 added - how the selection should actually look
![2z8x_sel_3](https://user-images.githubusercontent.com/56831705/67211303-67d34b00-f412-11e9-8f1e-53d23020918a.png)

**Comment by hainm** [comment]
> selection of residues with indices > 100 doesn't work 

@arose  can you confirm 

@gnik2018  thanks for your report. A workaround is to add cartoon twice with different selection.

**Comment by hainm** [comment]
wait, hold on. Your selection seems wrong.

```
In [1]: '%s' % [99,121,3]
Out[1]: '[99, 121, 3]'
```

should be
`99,121,...` (no space, no `[` and no `]`

**Comment by gnik2018** [comment]
ok, tried again with no space:
![2z8x_no_space](https://user-images.githubusercontent.com/56831705/67216233-c270a500-f41a-11e9-8ffd-4e74d9f43fff.png)
no space and no brackets:
![2z8x_no_space_no_brackets](https://user-images.githubusercontent.com/56831705/67216275-d3b9b180-f41a-11e9-941d-238bb93763be.png)
no space, no brackets, and selection is inside quotes:
![2z8x_no_space_no_brackets_inside_quotes](https://user-images.githubusercontent.com/56831705/67216313-e16f3700-f41a-11e9-805d-9fef3b530509.png)
still doesn't do the trick unfortunately

**Comment by hainm** [comment]
can you please paste your reproducible code here? make sure to include the `structure_id`. thanks.

**Comment by gnik2018** [comment]
can just replace `structure_id` with `"2z8x"`
Code (with residue index 99 added to selection):
`import nglview as nv`
`print(structure_id)`
`view = nv.show_pdbid(structure_id, default=False)`
`view.add_cartoon(selection="protein", color='blue')`
`view.center()`
`view.add_cartoon(selection = "%s" % [99,121,139,141,238,239,257,258,259,282,284,285,286,287,288,289,290,337,339,340,341,342,343,344,345,368,369,370,371,372,373,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,452,453,471,472,489,490,491,492,493,495,496,497,498,499,500,501,502,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,551,552,553,554,555,556,557,558,562,563,564,565,566,567,568,569], color='red')`
`#view.add_surface(selection="protein", opacity=0.3)`
`view`
output:
![output](https://user-images.githubusercontent.com/56831705/67217569-d74e3800-f41c-11e9-8a08-4b7e9c6026fc.png)

**Comment by hainm** [comment]
@gnik2018 Please try with this code. I was wrong, the selection should be string with space, e.g: `99, 100, 101`). Your selection is fragmented, so there're several residues that are not displayed with `cartoon`. It's ok with `licorice`.

```
import nglview as nv
view = nv.show_pdbid("2z8x", default=False)
selection=", ".join(
    map(str, [99,121,139,141,238,239,257,258,259,282,284,285,286,287,288,289,290,
              337,339,340,341,342,343,344,345,368,369,370,371,372,373,375,376,377,
              378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,
              395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,
              412,413,414,415,416,417,452,453,471,472,489,490,491,492,493,495,496,497,
              498,499,500,501,502,504,505,506,507,508,509,510,511,512,513,514,515,516,
              517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,
              535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,551,552,553,
              554,555,556,557,558,562,563,564,565,566,567,568,569]))
view.add_licorice(selection=selection, color='red')
view.center(selection)
view
```

![cartoon](https://user-images.githubusercontent.com/4451957/67218693-ce497080-f3f4-11e9-801c-137163251099.png)

**Comment by gnik2018** [comment]
@hainm 
Ok, it works now! Thank you!

**Comment by hainm** [comment]
glad to help.
