### ISSUE TITLE
Spin state not saved when calling nglview.write_html

### ISSUE THREAD

**Issue by ostrokach** [arose/nglview#856]
Is there any way to save the spin state of a molecule when calling `nglview.write_html`?

For example, I can create a spinning molecule in my Jupyter notebook:

```python
import nglview

view = nglview.show_pdbid('1tsu')
view._set_spin([1, 0, 0], 0.1)
view
```

However, if I try to export that view to an html file using `nglview.write_html('demo.html', [view])` and open the produced file in my browser, the resulting molecule does not rotate.

I know that in NGL the spinning state can be accomplished using `stage.setSpin(true);`. Is there any way to do this with the exported HTML file?

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.1
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```

**Comment by hainm** [comment]
You can try this
```
view._remote_call("setSpin", target='Stage', args=[True], fire_embed=True)
```

**Comment by ostrokach** [comment]
That works, thank you!!
