### ISSUE TITLE
view._display_image() doesn't show strucutre 

### ISSUE THREAD

**Issue by davidRFB** [arose/nglview#858]
![Captura de pantalla de 2019-11-04 17-15-21](https://user-images.githubusercontent.com/28023319/68162757-c1fe0100-ff26-11e9-8a6c-5af4555ab68f.png)
Hi, I am trying to follow the tutorial but I have this problem, any idea? 

thank you

**Comment by hainm** [comment]
hi @davidRFB, please try the solution in this link: https://github.com/arose/nglview/blob/master/docs/FAQ.md#widget-not-shown

**Comment by davidRFB** [comment]
Hi @hainm, the problem is solved! thank you.

**Comment by hainm** [comment]
great, cheers.
