### ISSUE TITLE
Bad Render when XYZ is shifted

### ISSUE THREAD

**Issue by dgasmith** [arose/nglview#859]
**Describe the bug**
A benzene molecule is rendered incorrectly in Jupyter. 
![image](https://user-images.githubusercontent.com/1508995/68235360-1958ab80-ffd1-11e9-81b1-ecd1f1eaa452.png)

**To Reproduce**
nglview-sdf string:
```
"""
QCElemental

 12 12  0  0  0  0  0  0  0  0  0
   -36.7161    41.9528   -36.0171 C   0  0     0  0  0  0  0  0
   -36.0692    41.9257   -34.7771 C   0  0     0  0  0  0  0  0
   -36.8074    41.7153   -33.6075 C   0  0     0  0  0  0  0  0
   -38.1924    41.5319   -33.6781 C   0  0     0  0  0  0  0  0
   -38.8393    41.5589   -34.9181 C   0  0     0  0  0  0  0  0
   -38.1012    41.7694   -36.0877 C   0  0     0  0  0  0  0  0
   -36.1398    42.1171   -36.9301 H   0  0     0  0  0  0  0  0
   -34.9879    42.0689   -34.7220 H   0  0     0  0  0  0  0  0
   -36.3024    41.6941   -32.6394 H   0  0     0  0  0  0  0  0
   -38.7687    41.3675   -32.7651 H   0  0     0  0  0  0  0  0
   -39.9206    41.4158   -34.9732 H   0  0     0  0  0  0  0  0
   -38.6062    41.7906   -37.0558 H   0  0     0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  6  1  0  0  0  0
  1  7  1  0  0  0  0
  2  3  1  0  0  0  0
  2  8  1  0  0  0  0
  3  4  1  0  0  0  0
  3  9  1  0  0  0  0
  4  5  1  0  0  0  0
  4 10  1  0  0  0  0
  5  6  1  0  0  0  0
  5 11  1  0  0  0  0
  6 12  1  0  0  0  0
"""
```

**Additional context**
- qcelemental version 0.11.1
- nglview version 2.7.1

As a note if this SDF is centered on the origin (or close to it, everything is fine).

https://github.com/MolSSI/QCElemental/issues/161

**Comment by hainm** [comment]
hi @dgasmith, there's something wrong with the cooridnates, py3Dmol can not show it correctly too.
<img width="1166" alt="Screen Shot 2019-11-07 at 9 01 23 PM" src="https://user-images.githubusercontent.com/4451957/68443448-dc8fde80-01a1-11ea-951c-50a53d9bf090.png">


Code
```
import py3Dmol
xyz = """
QCElemental

 12 12  0  0  0  0  0  0  0  0  0
   -36.7161    41.9528   -36.0171 C   0  0     0  0  0  0  0  0
   -36.0692    41.9257   -34.7771 C   0  0     0  0  0  0  0  0
   -36.8074    41.7153   -33.6075 C   0  0     0  0  0  0  0  0
   -38.1924    41.5319   -33.6781 C   0  0     0  0  0  0  0  0
   -38.8393    41.5589   -34.9181 C   0  0     0  0  0  0  0  0
   -38.1012    41.7694   -36.0877 C   0  0     0  0  0  0  0  0
   -36.1398    42.1171   -36.9301 H   0  0     0  0  0  0  0  0
   -34.9879    42.0689   -34.7220 H   0  0     0  0  0  0  0  0
   -36.3024    41.6941   -32.6394 H   0  0     0  0  0  0  0  0
   -38.7687    41.3675   -32.7651 H   0  0     0  0  0  0  0  0
   -39.9206    41.4158   -34.9732 H   0  0     0  0  0  0  0  0
   -38.6062    41.7906   -37.0558 H   0  0     0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  6  1  0  0  0  0
  1  7  1  0  0  0  0
  2  3  1  0  0  0  0
  2  8  1  0  0  0  0
  3  4  1  0  0  0  0
  3  9  1  0  0  0  0
  4  5  1  0  0  0  0
  4 10  1  0  0  0  0
  5  6  1  0  0  0  0
  5 11  1  0  0  0  0
  6 12  1  0  0  0  0
"""
xyzview = py3Dmol.view(width=400,height=400)
xyzview.addModel(xyz,'sdf',{'vibrate': {'frames':10,'amplitude':1}})
xyzview.setStyle({'stick':{}})
xyzview.setBackgroundColor('0xeeeeee')
xyzview.animate({'loop': 'backAndForth'})
xyzview.zoomTo()
xyzview.show()
```

**Comment by dgasmith** [comment]
If you shift the coordinates uniformly to be closer to the origin, everything is fine:

```
mol2 = mol.copy(deep=True)
mol2.geometry[:, 0]  += 70 # Geometry is in Bohr, while SDF is in Angstrom
mol2.geometry[:, 1]  -= 78
mol2.to_string("nglview-sdf")
```

```
QCElemental

 12 12  0  0  0  0  0  0  0  0  0
    0.3263    0.6770   -36.0171 C   0  0     0  0  0  0  0  0
    0.9732    0.6499   -34.7771 C   0  0     0  0  0  0  0  0
    0.2350    0.4395   -33.6075 C   0  0     0  0  0  0  0  0
   -1.1500    0.2561   -33.6781 C   0  0     0  0  0  0  0  0
   -1.7969    0.2831   -34.9181 C   0  0     0  0  0  0  0  0
   -1.0588    0.4936   -36.0877 C   0  0     0  0  0  0  0  0
    0.9026    0.8413   -36.9301 H   0  0     0  0  0  0  0  0
    2.0545    0.7931   -34.7220 H   0  0     0  0  0  0  0  0
    0.7400    0.4183   -32.6394 H   0  0     0  0  0  0  0  0
   -1.7263    0.0917   -32.7651 H   0  0     0  0  0  0  0  0
   -2.8782    0.1400   -34.9732 H   0  0     0  0  0  0  0  0
   -1.5638    0.5148   -37.0558 H   0  0     0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  6  1  0  0  0  0
  1  7  1  0  0  0  0
  2  3  1  0  0  0  0
  2  8  1  0  0  0  0
  3  4  1  0  0  0  0
  3  9  1  0  0  0  0
  4  5  1  0  0  0  0
  4 10  1  0  0  0  0
  5  6  1  0  0  0  0
  5 11  1  0  0  0  0
  6 12  1  0  0  0  0
```

**Comment by dgasmith** [comment]
It looks like a white space issue, the following renders fine:
```
QCElemental

 12 12  0  0  0  0  0  0  0  0  0
  -36.7161   41.9528   -36.0171 C   0  0     0  0  0  0  0  0
  -36.0692   41.9257   -34.7771 C   0  0     0  0  0  0  0  0
  -36.8074   41.7153   -33.6075 C   0  0     0  0  0  0  0  0
  -38.1924   41.5319   -33.6781 C   0  0     0  0  0  0  0  0
  -38.8393   41.5589   -34.9181 C   0  0     0  0  0  0  0  0
  -38.1012   41.7694   -36.0877 C   0  0     0  0  0  0  0  0
  -36.1398   42.1171   -36.9301 H   0  0     0  0  0  0  0  0
  -34.9879   42.0689   -34.7220 H   0  0     0  0  0  0  0  0
  -36.3024   41.6941   -32.6394 H   0  0     0  0  0  0  0  0
  -38.7687   41.3675   -32.7651 H   0  0     0  0  0  0  0  0
  -39.9206   41.4158   -34.9732 H   0  0     0  0  0  0  0  0
  -38.6062   41.7906   -37.0558 H   0  0     0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  6  1  0  0  0  0
  1  7  1  0  0  0  0
  2  3  1  0  0  0  0
  2  8  1  0  0  0  0
  3  4  1  0  0  0  0
  3  9  1  0  0  0  0
  4  5  1  0  0  0  0
  4 10  1  0  0  0  0
  5  6  1  0  0  0  0
  5 11  1  0  0  0  0
  6 12  1  0  0  0  0
```

Is there any way to ship you JSON? Guessing at an SDF spec has been less than ideal.

**Comment by hainm** [comment]
> Is there any way to ship you JSON? 

Unfortunately no, `NGL` does not JSON format like 3Dmol. Please see the supported formats here: https://github.com/arose/ngl#features

By the way, does the original `nglview.show_qcelemental` work (via converting `QCElemental`'s molecule to `xyz` format then using `ase` to convert to pdb format?) https://github.com/arose/nglview/pull/860/files#diff-4ce3d182381685f532cba27b6562ff66L145

**Comment by dgasmith** [comment]
No it would not work originally. The new version just centers the molecule so that the width issues are less prevalent. Can you provide the lines to the SDF parser in JS? I might reproduce directly from that.

**Comment by hainm** [comment]
>  Can you provide the lines to the SDF parser in JS? 

It's done in `NGL` repo (if the new code is introduced there, @arose needs to publish its package and `nglview` will rebuild its JS extension. Kind of complicated): https://github.com/arose/ngl/blob/master/src/parser/sdf-parser.ts

But does the original sdf string follow SDF's standard format? (I am not familiar with this format).
Both 3Dmol and NGL have trouble reading it. :D

**Comment by dgasmith** [comment]
I think this is the needed blob:
```
          const x = parseFloat(line.substr(0, 10))
          const y = parseFloat(line.substr(10, 10))
          const z = parseFloat(line.substr(20, 10))
```

I couldn't find this in any of the SDF specs thats I read through. I can correct our SDF parser based on this. A JSON format would be really awesome, all of this string conversion is pretty fragile.

**Comment by hainm** [comment]
@arose  any comment?

**Comment by arose** [comment]
Is there a generally used JSON format for such small molecules? I am happy to look at a PR for a parser for that.

As far as I know, SDF is a fixed column format but if there is a commonly used variable column variant I am also happy to look at PRs for that.

**Comment by dgasmith** [comment]
It was easy to fix on our side once I knew the widths. My ready of SDF on the web could have easily led me astray :)

For a JSON spec you could use the MolSSI QCSchema spec. For this it would be `symbols (n-array)`, `geometry (n * 3 - array)`, `connectivity (array of [atom1, atom2, bond_order])`.

I could try brushing up on my TS, but it may be a bit.

**Comment by hainm** [comment]
We can close this now. Thanks.
