### ISSUE TITLE
Can only see default repr

### ISSUE THREAD

**Issue by sperezconesa** [arose/nglview#862]
Hello,
I am using this cell in jupyter-lab. When I run it I see only the default representation. It's as if the add spacefill is not being added
```python
ref = MDA.Universe("NPT-res/charmmgui1_ions_cleaned_wat.psf","opt/5VK6_charmm_gui1_ions_cleaned_wat.pdb")
view = nv.show_mdanalysis(ref, default=True)
view.add_spacefill(selection=".CA", color='green')
view
```
Thanks a lot!
Sergio

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.1

python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.0
```

**Comment by hainm** [comment]
hi, does that work in traditional notebook? And please try my example below.

![green](https://user-images.githubusercontent.com/4451957/68957598-5b83a900-0798-11ea-9d6d-af49b8632003.png)

**Comment by sperezconesa** [comment]
This works perfectly. The problem seems to be in the .psf, which works fine in vmd... I get these warnings:
```text
/data/sperez/bin2/anaconda3/envs/lab_working/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:902: UserWarning: Found no information for attr: 'altLocs' Using default value of ' '
  "".format(attrname, default))
/data/sperez/bin2/anaconda3/envs/lab_working/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:902: UserWarning: Found no information for attr: 'icodes' Using default value of ' '
  "".format(attrname, default))
/data/sperez/bin2/anaconda3/envs/lab_working/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:902: UserWarning: Found no information for attr: 'occupancies' Using default value of '1.0'
  "".format(attrname, default))
/data/sperez/bin2/anaconda3/envs/lab_working/lib/python3.7/site-packages/MDAnalysis/coordinates/PDB.py:902: UserWarning: Found no information for attr: 'tempfactors' Using default value of '0.0'
  "".format(attrname, default))
```
Any clues why the psf can be a problem. It also fails with the licorice representation.

**Comment by hainm** [comment]
@sperezconesa do you mind sharing the files (1 frame)?

**Comment by sperezconesa** [comment]
Sure.
[files.tar.gz](https://github.com/arose/nglview/files/3857528/files.tar.gz)

**Comment by hainm** [comment]
@sperezconesa what's the format of the `5VK6_charmm_gui1_ions_cleaned_wat.pdb`?

**Comment by hainm** [comment]
Please make sure the files work in your machine. thanks.

**Comment by sperezconesa** [comment]
Sorry. This should be OK
[files.tar.gz](https://github.com/arose/nglview/files/3863685/files.tar.gz)

**Comment by hainm** [comment]
thanks @sperezconesa. It seems like if you execute the `view.add_spacefill` in different cell, the repr should work. This might due to the asynchronous between JS and python backend.

![ca](https://user-images.githubusercontent.com/4451957/69163142-b4ff1700-0abb-11ea-8b9a-75cbea48b098.png)

**Comment by sperezconesa** [comment]
Great! Thanks a lot!
Sergio

**Comment by hainm** [comment]
@sperezconesa  Just curious, how did you get the `5VK6_charmm_gui1_ions_cleaned_wat.pdb`? Some programs like pytraj or parmed can not read it (but MDAnalysis and mdtraj can).

**Comment by sperezconesa** [comment]
From charmm-gui. Plus editing by hand and vmd. So its kind of complicated origin.

**Comment by hainm** [comment]
thanks. We can close this case now. The issue `This might due to the asynchronous between JS and python backend.` is hard to fix and we can live without for now. :D
