### ISSUE TITLE
visualize multiple molecules 

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [arose/nglview#864]
I would like to visually explore many molecules. For example, plot many molecule structures together (like 10*10 matplotlib subplots) and visualize them. 

Nglview can only visualize one molecule each time. I am thinking about export the view for different molecules as images and then combine them but I didn't find a good way to do so. view.download_image() doesn't seem to work for python script. (I can call view.download_image() but I will have to save each view manually.)

Would you like to make some suggestions? Thank you very much!

**Comment by hainm** [comment]
Please see `add_component`or `adf_trajecyory method.

**Comment by Chen-Cai-OSU** [comment]
Thank you. I looked at those methods but my molecules are coming from pymatgen. from pymatgen 

```
import MPRester
mpr = MPRester('VSPmxZVFOIhZh7U3iep')
struc = mpr.get_structure_by_material_id('mp-21440') # structure object    
print(type(struc))
print(struc)
view = nglview.show_pymatgen(struc)
view
```
The above code works but I would like to visualize different mp-ids. I tried the two methods you mentioned but it does not work. struc here is an instance of pymatgen.core.structure.Structure.

**Comment by hainm** [comment]
hi @Chen-Cai-OSU, 

can you please try below? 

```python
from pymatgen.io.ase import AseAtomsAdaptor
ngl_struc = nglview.ASEStructure(AseAtomsAdaptor().get_atoms(struc))
view.add_structure(ngl_struc)
```

The key concept is to convert pymatgen's struc to ASE object and then wrap it with `nglview` interface class. Let me know if that works.

**Comment by Chen-Cai-OSU** [comment]
Hello,

Thanks a lot for the help! The following is working now.

```
view = nglview.NGLWidget()

for idx in [1,2,3, 4]:
    mp = mps[idx]
    struc = mpr.get_structure_by_material_id(mp) # pymatgen.core.structure.Structure
    
    from pymatgen.io.ase import AseAtomsAdaptor
    ngl_struc = nglview.ASEStructure(AseAtomsAdaptor().get_atoms(struc))
    view.add_component(ngl_struc)

view
```

But right now different molecules are not lay out nicely. 

<img width="353" alt="Screen Shot 2019-12-27 at 12 35 31 PM" src="https://user-images.githubusercontent.com/47577816/71526567-88ea6900-28a5-11ea-88e9-dc947755876a.png">

How to make it look like this?
<img width="600" alt="Screen Shot 2019-12-27 at 12 35 52 PM" src="https://user-images.githubusercontent.com/47577816/71526568-88ea6900-28a5-11ea-9a5b-db1eda0540f0.png">

**Comment by hainm** [comment]
hi @Chen-Cai-OSU, I misunderstood your question (was reading on my phone).
Please see this example and let me know if that helps. https://github.com/arose/nglview/blob/master/examples/users/ase.md

**Comment by hainm** [comment]
> I am thinking about export the view for different molecules as images and then combine them but I didn't find a good way to do so. view.download_image() doesn't seem to work for python script. (I can call view.download_image() but I will have to save each view manually.)

You can call `image = view.render_image(); print(image.value)` but it's a bit tricky to make it work nicely (please see this thread: https://github.com/arose/nglview/issues/785#issuecomment-564693910).

**Comment by Chen-Cai-OSU** [comment]
> hi @Chen-Cai-OSU, I misunderstood your question (was reading on my phone).
> Please see this example and let me know if that helps. https://github.com/arose/nglview/blob/master/examples/users/ase.md

Hi, after modify the example you gave, I got it almost working. RIght now the problem is that, for small 3 by 3 grid, it's working fine but for 5*5 grid, there are no images. I guess there are some parameters I need to manually set up.

<img width="824" alt="Screen Shot 2019-12-28 at 1 16 20 PM" src="https://user-images.githubusercontent.com/47577816/71547940-ae927380-2974-11ea-99b3-238095a7c734.png">
<img width="845" alt="Screen Shot 2019-12-28 at 1 17 09 PM" src="https://user-images.githubusercontent.com/47577816/71547941-ae927380-2974-11ea-9fa3-18d6e6af788c.png">

**Comment by hainm** [comment]
Hi it’s a known limitation and I dont know how to fix it.

**Comment by Chen-Cai-OSU** [comment]
Then do you have any suggestions on visualizing multiple structures?
