### ISSUE TITLE
A question regarding to the "widget-cookiecutter" for the JupyterLab 

### ISSUE THREAD

**Issue by dou-du** [arose/nglview#866]
Hi,

I have made some custom widgets by using the "widget-cookiecutter". They are working for Jupyter notebook. However, when I try to install for JupyterLab, none of them are working with JupyterLab. 

To my surprise, the Nglview which used the "widget-cookiecutter" can be successfully installed on JupyterLab. I am wondering that did the developers make some modifications for the "widget-cookiecutter". Could you give some suggestions ? Thanks.

**Comment by hainm** [comment]
hi, I don't recall "how", but you can start from here: https://github.com/arose/nglview/blob/master/js/src/jupyterlab-plugin.js

May be "git grep jupyterlab" in nglview repo for reference?
