### ISSUE TITLE
nbsphinx HTML header?

### ISSUE THREAD

**Issue by jbloom** [arose/nglview#869]
I'm trying to render Jupyter notebooks with `nglview` widgets using `nbsphinx`.

If I just convert a Jupyter notebook with `nbsphinx`, the widgets do **not** render. But if I also write a widget a HTML file with `nglview.write_html` and then include that HTML in the Jupyter notebook that is rendered with `nbsphinx`, then all the widgets render correctly.

I assume that this is because there is some HTML header or code that is needed to be embedded in the HTML for the widgets to render, and this is automatically included by `nglview.write_html` but not by `nbsphinx`. My question is what is this HTML header / code so I can just add that rather than having to include an entire HTML written by `nglview.write_html`?

**Comment by hainm** [comment]
Hi @jbloom:  have you tried to save the widget states first? 

If not, from the notebook options, choose "Save Notebook Widget State" to store the iywidgets's widgets (e.g: nglview) in notebook's output data.

**Comment by hainm** [comment]
I have not tried with `nbsphinx` yet but it's fine with `jupyter-nbconvert`

- In the notebook (saying 'my.ipynb'): "Save Notebook Widget State"
- In the terminal
```
jupyter-nbconvert my.ipynb --to=html
open my.html # you can see the live widget
```

**Comment by hainm** [comment]
Resolved.
