### ISSUE TITLE
download image

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [arose/nglview#870]
Hello,
I would like to use nglview in a python script without using jupyter notebook. One reason is that  I didn't find a good way to visualize multiple molecules in a grid, as mentioned in https://github.com/arose/nglview/issues/864. 

So I am thinking of saving the visualization of each molecule and then stitch many images together. (It's quite some overhead but I don't know if there is an easier way). However, I am having trouble saving a single visualization. I am able to run the following example but I didn't see any png files saved. Do you know where is the error? Thanks a lot!

```
import pymatgen as mg
import nglview as nv

lattice = mg.Lattice.cubic(4.2)
structure = mg.Structure(lattice, ["Cs", "Cl"],
                         [[0, 0, 0], [0.5, 0.5, 0.5]])
view = nv.show_pymatgen(structure)
view
view.download_image(filename='./ngl.png')
```

**Comment by hainm** [comment]
> I would like to use nglview in a python script without using jupyter notebook. O

Hi, `nglview` is notebook-based application. You have to run the commands in the notebook. 
Please see here for some tricks: https://github.com/arose/nglview/issues/785#issuecomment-564693910

**Comment by Chen-Cai-OSU** [comment]
Hello, 

I tried my example but run into some error. Would you take a look at it? All I need is to visualize and save a cif file in python script. It would be greatly appreciated if you can provide a working example. Thank you so much. 

<img width="567" alt="Screen Shot 2020-02-09 at 11 20 28 PM" src="https://user-images.githubusercontent.com/47577816/74120901-40f07e80-4b93-11ea-825d-8351c863e313.png">

**Comment by hainm** [comment]
@Chen-Cai-OSU do you have the files in your disk (`1tsu.pdb`, `2koc.pdb`)?
