### ISSUE TITLE
Disable right click in Jupyter lab

### ISSUE THREAD

**Issue by hadim** [arose/nglview#872]
Right-clicking on a nglview is useful to select an atom for example. In JLab it also shows up the context menu.

This context menu should be disabled IMO.

**Comment by hainm** [comment]
yeah agree. I still don't know how to do that :(.

**Comment by hadim** [comment]
https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_dev.rst#context-menus
