### ISSUE TITLE
`nglview.show_pdbid("3pqr")` not work in Python 3.7 

### ISSUE THREAD

**Issue by alvarosf** [arose/nglview#875]
- Question about usage? 
`nglview.show_pdbid("3pqr")` not work in Python 3.7 
- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
```
![imagen](https://user-images.githubusercontent.com/60842367/76161031-b1a59f00-612f-11ea-86b9-4c207d8c5c5c.png)
Would youmind helping me to solve this problem

!python --version
!jupyter --version 
!jupyter-notebook --version

import nglview
import ipywidgets
import notebook
print(nglview.__version__)
print (ipywidgets.__version__)
print (notebook.__version__)

nglview.demo()
view = nglview.show_pdbid("3pqr")
view

view.clear()
view.render_image()
view._display_image()

**Comment by hainm** [comment]
hi @alvarosf, have to tried this step yet? `jupyter-nbextension enable nglview --py --sys-prefix`

**Comment by hainm** [comment]
related: https://github.com/arose/nglview/issues/752

**Comment by gVallverdu** [comment]
Hi
I got the same issue. Maybe you should add this step in the installation instructions on the README ?
After I have enabled the extension in works fine on jupyter notebook but not on jupyter lab.

I got the following message on the terminal :
```[W 23:00:52.919 LabApp] Could not determine jupyterlab build status without nodejs```

This is my jupyter and python versions:

```Python 3.7.4
jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
6.0.3

nglview: 2.7.1
ipywidgets: 7.5.1
notebook: 6.0.3```

**Comment by hainm** [comment]
> Maybe you should add this step in the installation instructions on the README ?

Have you checked README yet? It’s already there. 

Per lab issue, please try v2.7.5

**Comment by hainm** [comment]
Ah you have to install nodejs (conda-forge) to install lab extension. That’s the way lab works.

**Comment by gVallverdu** [comment]
Oh, I am really sorry, I did not read the comments after the conda install for standard notebooks and jupyter lab.
