### ISSUE TITLE
Compatibility with JLab >=2

### ISSUE THREAD

**Issue by hadim** [arose/nglview#876]
On my setup, the JLab nglview extension does not work using Jlab >=2. The JS error is:

```js
Module nglview-js-widgets, semver range ^2.7.4 is not registered as a widget module
```

**Comment by hadim** [comment]
Maybe replacing `"@jupyter-widgets/base": "^1.1 || ^2"` by `"@jupyter-widgets/base": "^1.1 || ^2 || ^3"` in https://github.com/arose/nglview/blob/master/js/package.json will do the job?

**Comment by hainm** [comment]
Have you tried that yet?

**Comment by hadim** [comment]
Yup but it doesn't work...

**Comment by hadim** [comment]
See https://github.com/arose/nglview/pull/877
