### ISSUE TITLE
Uncaught (in promise) Class NGLModel not found in module nglview-js-widgets

### ISSUE THREAD

**Issue by LynaLuoLab** [arose/nglview#879]
Tried three different versions of nglview (2.7.5, 2.7.1 and 1.2.2), got the same error message and no structure showed up. 
Uncaught (in promise) Class NGLModel not found in module nglview-js-widgets
It's strange that on another macOS in my lab, same version works fine:
<img width="1712" alt="Screen Shot 2020-03-17 at 3 01 45 PM" src="https://user-images.githubusercontent.com/27087377/76905981-46ab4500-6860-11ea-952f-559bfc8698c3.png">

**Comment by LynaLuoLab** [comment]
> jupyter-nbextension enable nglview --py --sys-prefix
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK
> jupyter-nbextension enable widgetsnbextension --py --sys-prefix
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

**Comment by hainm** [comment]
@LynaLuoLab Please see the solution here: https://github.com/arose/nglview/issues/718#issuecomment-346041897

and here: https://github.com/arose/nglview/blob/master/docs/FAQ.md#widget-not-shown
Once you completely clean the v1.x version, you should be fine.

cheers

**Comment by LynaLuoLab** [comment]
I followed the "Extensive debug experience from users", it worked. Thank you!
