### ISSUE TITLE
jupyter nbextension enable --py widgetsnbextension

### ISSUE THREAD

**Issue by hainm** [arose/nglview#88]
this is required with new ipywidget version. If not, getting 

[Widget Javascript not detected](https://github.com/ipython/ipywidgets/issues/541)

**Comment by hainm** [comment]
may be just add system call when calling 'install'.

**Comment by arose** [comment]
Seems like the user needs to `jupyter nbextension enable --py widgetsnbextension` themselves. We need to add that to the documentation.

**Comment by hainm** [comment]
pain: https://github.com/ipython/ipywidgets/issues/586

**Comment by kain88-de** [comment]
@hainm you are not the only one. But I hear the JS side is supposed the become more stable once the infamous version  5.0 is released.

**Comment by hainm** [comment]
I hope so. :D

**Comment by hainm** [comment]
close since this related to #220
