### ISSUE TITLE
view.n_components (and others?) are lagging

### ISSUE THREAD

**Issue by vhorvath** [arose/nglview#883]
Could the `view.n_components` become dynamic property, like the `component.id` ? It is an observable for Jupyter, but it only gets updated when a cell is executed. So fore example the output is 0, 2 when you do:

```
view = nv.NGLWidget()
widget.add_component('6urh.pdb')
widget.add_component('6urh.pdb')
print(view.n_components, len(view._ngl_component_ids))
```

Even the one below outputs 0, 2:
```
# Cell # 1
view = nv.NGLWidget()
widget.add_component('6urh.pdb')
widget.add_component('6urh.pdb')

# Cell # 2
print(view.n_components, len(view._ngl_component_ids))
```

Synchronization only happens when Jupyter has the chance to display the cell.
```
# Cell # 1
view = nv.NGLWidget()
widget.add_component('6urh.pdb')
widget.add_component('6urh.pdb')
display(widget)

# Cell # 2
print(view.n_components, len(view._ngl_component_ids))
```

In other words, `n_components` is lagging behind the actual count. However, I see that it is being used in the code as a read-only dynamic property in the Python code. Which may explain some of the inconsistencies in the Widget's behavior.

This lag is not at all obvious, and it may cause a lot of confusion for users wanting to use it in more advanced code that does not traverse cells.

Switching it to a dynamic property may have breaking consequences, as `n_components` is being observed. In the NGLWidget code itself there is one instance, but that could be switched out to observe `_ngl_component_ids` and taking the length of it instead. What I don't know if users rely on observing `n_components`.

Given the discrepancy between `len(view._ngl_component_ids)` and `view.n_components` I would not think it is widely used.

Also, I think some other properties, like `_view_height` and `_view_width`, etc have the same problem. Jupyter provides us with this great facility to sync between Javascript and Python, but when the underlying logic is only called if ** (1) the widget is displayed and (2) a cell enter/exit occurs**. I could accept first requirement, but the second is not acceptable for most applications. 

I think it would be beneficial to review which properties are part of the expected UI interactions: which are the ones that could be taken care of Jupyter, and which ones belong to the Python/JS synchronization that might require immediate updates via custom logic. In my opinion any low level and private property would qualify for this. These properties would require a direct query line between the JS and the Python side as this usage pattern is not quite like the MVC Jupyter intends us to use.

I created a new [branch](https://github.com/vhorvath/nglview/tree/sync-testing) to test this idea with `view.n_components` and possibly `view._view_width` and `view._view_height`. My goal is to establish immediate queries / updates for the Python side leveraging the existing messaging system.

**Comment by hainm** [comment]
hi,

it's intentional to keep `view.n_components` that way. It must be updated from JS code to trigger those code:

https://github.com/arose/nglview/blob/b2b24c8daf18e7fd03505933ee045807550aaf3b/nglview/widget.py#L392-L424

**Comment by hainm** [comment]
However, `n_components` is mainly used for handle the old style GUI
```
import nglview as nv

v = nv.demo()
v.display(gui=True, style='ipywidgets')
```

Currently I would prefer user to use the new one:
```
import nglview as nv

v = nv.demo()
v.display(gui=True, style='ngl')
```

**Comment by hainm** [comment]
> I created a new branch to test this idea with view.n_components and possibly view._view_width and view._view_height. My goal is to establish immediate queries / updates for the Python side leveraging the existing messaging system.

thanks. Feel free to play around and I really appreciate.

**Comment by hainm** [comment]
```
import nglview as nv

v = nv.demo()
v.display(gui=True, style='ngl')
``` 
With the new GUI (using NGL's GUI), user can add/delete component from the GUI, which is in JS side. This will cause the discrepancy between `len(view. _ngl_component_ids)` and the real number of components.

**Comment by hainm** [comment]
Another technical issue is that:

```
view.add_component("A") # successfully loaded
view.add_componet("B") # NOT successfully loaded due to the wrong format
```

in this case, the `len(view. _ngl_component_ids) ` is 2 but the `view.n_components` is actually 1.

**Comment by vhorvath** [comment]
Yeah, this is one more reason why it would be better to have a single source of truth: ask the NGL JS app for properties that require (double) bookkeeping...

I have been looking at this issue for quite a while now. I did not know much about the messaging system in Jupyter when I started, but I've been reading up on it.

It seems to me that the problem is that the Jupyter messaging system is completely async (by necessity and because the two event queues are async), whereas what we must do is actually a blocking sync query/reply, which should be simpler...

One obvious way around is to do something like the await directive for Promises in Javascript. However, when the main Python kernel process is held down, event processing is on pause.

Now, I see that replies from the JS side are being handled via threads, but those are just making sure that the messages do get processed when they do arrive. However, for example the NGLWidget._load_data() method calls out and returns immediately, leaving the main thread running, so that pattern would not work.

Now, I am exploring ways to (1) take care of the messages while the main event loop is stuck  or to (2) run a custom event loop that is in a separate thread. This would require setting this up on both sides manually, plus maybe something in the Notebook server.

I think, at least one of these ideas should be possible, because the components are part of the standard Jupyter Notebooks.

What I find a bit annoying is that the Widget traitlet system is designed for solving the fundamental problem: keeping the two sides in sync. However, the timing seems to be tied to the same constraints: messages are only processed after the kernel has done processing the content of a cell.

I have tested the underlying `IPython.Comm` class based communication which is the base of the Jupyter traitlet system and seen the same behavior. This is why I think custom message processing might be the way to go.

But I am also open to ideas and pointers... I did not find much out there on this specific issue.

**Comment by hainm** [comment]
@vhorvath FYI this package just in case you want to play around with `Comm` stuff.

**Comment by hainm** [comment]
https://github.com/kafonek/ipython_blocking

**Comment by vhorvath** [comment]
That's a very interesting project! It uses an interesting trick: eaves dropping on the shell handlers. I first thought that this could work for establishing the comm link.

However, it appears to have the same limits apply as the rest of the high level message management APIs: when the main kernel process is busy the messages are not moving. The simple reason for this is that the the kernel runs the entire code segment of a given cell at once, and callbacks only happen when that job is done, so messages are stuck in buffers (?). I am yet to find out is the place where they are waiting.

I setup a Comm object according to the description in the official [Jupyter docs](https://jupyter-notebook.readthedocs.io/en/stable/comms.html). I see that each Comm object communicates with the front end via the kernel's io_pub/io_thread objects, which employ ZeroMQ sockets.

An older [Jupyter architecture description](https://jupyter.readthedocs.io/en/latest/architecture/how_jupyter_ipython_work.html#notebooks) suggests that it is indeed a ZeroMQ socket that I am after:

![Jupyter Notebook Comm Diagram](https://jupyter.readthedocs.io/en/latest/_images/notebook_components.png)

However, so far I could not tap into the ZeroMQ communication lines, but there is still hope... I need to get my hands messy with ZeroMQ to better understand, poking around did not get me far.

**Comment by vhorvath** [comment]
I managed to tap into the ZeroMQ message lines and created a blocking query that allows for immediate retrieval of properties from the JS side without the need of syncing via the Widget subsystem.

I created a property accessor that can pull up to date data from the JS side (`wiget._get_remote_prop()`). I used that to change the default `widget._load_data()` function to be blocking, finally I created a property to retrieve component count as a property as well. This is just an illustration of how this method could enhance the NGLViewer.

I committed it to my [VHorvath/nglview/blocking-queries](https://github.com/vhorvath/nglview/tree/blocking-queries) branch, there is a notebook called `new_comm_routines.ipynb` to demonstrate the functionality. There are some rough edges, e.g. there is still some timing related issue with one of the cells, but I think part of it is that there are systems that are out of sync. I did not review the entire JS code to make sure it is completely bug free. So, I don't intend this for immediate PR. More work needs to be done, but maybe thinking about directions is also a good idea.

I think that this approach could open up new directions for the NGLViewer, even a high level of API compatibility with JS NGL. It is not uncommon to have Python packages as compatibility layers for libraries written in other languages. I use RDKit and OpenEye in Python, the beauty in them is that they are very similar to their C++ counterparts, but they are much more productive. Maybe this could be a way forward for NGLViwer with some semi-automatic code and documentation generation that is tied to the JS development.

I would not want to steer this project in any directions, as the current user base probably prefers it the way it is. Maybe as an experiment this other way could be tried. The basic idea is that Python merely consults the JS NGL library, and replicates its API (plus any additional logic required), no double bookkeeping. I wanted to open up a conversation and also offer some help if there is interest in pursuing this direction.

**Comment by hainm** [comment]
> I would not want to steer this project in any directions, as the current user base probably prefers it the way it is. Maybe as an experiment this other way could be tried. The basic idea is that Python merely consults the JS NGL library, and replicates its API (plus any additional logic required), no double bookkeeping. I wanted to open up a conversation and also offer some help if there is interest in pursuing this direction.

Thanks. Let your imagination run wild if you would like to explore. It might be helpful for `nglview` or other jupyter-based projects. Thanks.

**Comment by hainm** [comment]
Your approach might help the case that if user open `NGL`'s native GUI and delete/add component, the `view. _ngl_component_ids` is not updated.

**Comment by vhorvath** [comment]
My approach certainly could help with that. I see that there are several locations where that private variable is being updated in order to remain in sync with the JS side, those could be eliminated.

In fact, any of the public/private variables could use this method to stay in sync with the JS side without having to "manually" update them. For the private variables which do not have sync=True set, and which are not being observed, I think it could be safely be used. But that assumes that no other user observes those variables, which might not be true, since they are traitlets, so whenever you assign values to them they can trigger events which my approach would not allow to do. I know private variables are not supposed to be used, but we do hacks like this. Another question is whether the need for observing these variables is not a byproduct of having to use the Widget system and async on the first place...

The primary reason why I did not go ahead changing variables like `view._ngl_component_ids` is because I do not want to make wide spread modifications without discussing it. I understand that `nglview` is an opensource project, and anyone can take the initiative to fork and modify it as they see fit. On the other hand, I honor the efforts of you and the original contributors, and I want you to be on board with the changes I propose before I make them. I would prefer not having to discard hours of work because they never get merged.

The second reason is that I do not know this project inside out yet. Luckily there are tests so I can check if I break something. However, I still need to setup test suites, so that I don't have to wait for Travis CI to find out that I broke something (as it happened in my previous PR with the tabs)...

**Comment by hainm** [comment]
I have been trying your notebook and I like it. 

- However, my concern is that we are hacking the non-API from ZMQ.

- Additionally, below code will freeze the cell.

```
# NGL initialization
view = nv.NGLWidget()
# Loading components
view.add_component('6urh.pdb')
print(view._get_remote_prop('stage.compList.length'))
view.add_component('6pcm.pdb')
print(view._get_remote_prop('stage.compList.length'))
view
```
<img width="1169" alt="Screen Shot 2020-03-27 at 5 31 35 PM" src="https://user-images.githubusercontent.com/4451957/77802259-dd41e800-7050-11ea-8978-d3f919933e52.png">

- If the feature is ever added to `nglview`, I think we can use a feature flag to activate it so experience users can try it if they really want programmatically play with `nglview`.

**Comment by hainm** [comment]
> The second reason is that I do not know this project inside out yet. Luckily there are tests so I can check if I break something. However, I still need to setup test suites, so that I don't have to wait for Travis CI to find out that I broke something (as it happened in my previous PR with the tabs)...

Besides running the unittest test, you should also run the notebook tests manually ( :D )
https://github.com/arose/nglview/tree/master/nglview/tests/notebooks

**Comment by vhorvath** [comment]
So, the reason why it freezes is exactly due to the fact that the Widget subsystem is communicating only after a cell has been submitted.

I am aware of the freezing. The view must first be initialized (`display()` called on it), before you can use any blocking calls. As I remember, the `NGLView.on_msg()` is not getting called, but we got stuck waiting for a message. It is just how the Jupyter Widgets work. This could easily be overcome by a custom comm channel, that only talks to the blocking calls, and avoids the whole Jupyter Widget subsystem. I don't see it as a show stopper. I just wanted keep it simple for now.

Regarding ZMQ, there is not too much to worry about. I copy-pasted the function that the messaging system uses, and the two modifications are really minor: message request is now blocking (we don't end up running the while loop a million times), and the handler now returns the message after forwarding it to the callback handlers. Otherwise, the handler is the same exact code as it is in the package and message handling is done the same way as before. Also, this function is only being activated when we do a blocking call. All the rest is intended to be done the way it normally is done. I don't even hold back the messages that the blocking-query handlers will process. It does need more formal definitions, checks and fall backs, and of course more testing.

**Comment by vhorvath** [comment]
Okay, this appears not to be a good idea after all. I realized that I am running into a fundamental design conflict by trying what I wanted.

While there is one Python `DOMWidget` class instance, there may be multiple instances of the companion `DOMWidgetView` instances on the JS side. This is why there must be double bookkeeping. The JS side is not supposed to hold any information about its state, it merely supposed to render according to the state of the Python side. There really is no way around it, because every `display()` call generates a new `DOMWidgetView` instance which must be (re)configured according to the state `DOMWidget` holds. This is exactly what the current `NGLView` code is doing.

If there were a way to pickle a the underlying `NGL` Javascript instance with all of its state variables it could be possible to employ my method: probing the state of the JS instance. That would simplify the `NGLView` widget. However, I think this issue is beyond the scope of this project, and indeed it might be simpler just keeping things the way they are: replaying the relevant actions to the new `NGL` instance so that it resembles the previous one. Even though is inefficient at keeping things in sync, it is effective because it guarantees that newly displayed instances are identical in look without having to preserve all the state variables from the JS `NGL` instance.

I think we can close this issue for now, but maybe a "best practices" or "gotchas" section in the Wiki would be helpful for the casual user. It is not at all obvious that some actions need cell boundaries between them.

**Comment by hainm** [comment]
Thanks @vhorvath. I really appreciate your effort (It's really fun to dig deeper to jupyter world).

**Comment by hainm** [comment]
> I think we can close this issue for now, but maybe a "best practices" or "gotchas" section in the Wiki would be helpful for the casual user. It is not at all obvious that some actions need cell boundaries between them.

yeah agree. For now, we will direct user to this discussion.
