### ISSUE TITLE
How to draw vector and plane with Nglview ?

### ISSUE THREAD

**Issue by dou-du** [arose/nglview#884]
I want to draw the (111) surface with Nglview as shown below:

![image](https://user-images.githubusercontent.com/56022756/77486934-4c40f600-6e31-11ea-9d6b-5661d725433b.png)

Is it possible to draw vector and plane with Nglview ? Thanks for helping.

**Comment by hainm** [comment]
> Is it possible to draw vector

Please use `view.shape.add_arrow`: https://github.com/arose/nglview/blob/master/nglview/tests/notebooks/api/test_add_shape.ipynb

> and plane with Nglview 

@arose Any idea?

**Comment by dou-du** [comment]
Thanks a lot. The add_arrow is working.
