### ISSUE TITLE
Viewing 2 Biopython structures at once

### ISSUE THREAD

**Issue by j0kaso** [arose/nglview#885]
Hey!

How can I load 2 Biopython structures into the same widget?

Or is there another way to load biopython structures than `nv.show_biopython(structure)`?

Thanks for the help!

**Comment by hainm** [comment]
hey @j0kaso 

see below example:
```
view = nv.NGLWidget()
view.add_structure(BiopythonStructure(first))
view.add_structure(BiopythonStructure(second))
```

https://github.com/arose/nglview/blob/e181b16a762eeabc8d6f2964d55a1986af7657bc/nglview/show.py#L436-L452

**Comment by j0kaso** [comment]
Many thanks, works like a charm!
