### ISSUE TITLE
show_file(path) not working in jupyterlab 2.0.1 "uncaught exception: error loading file: 'Not Found'"

### ISSUE THREAD

**Issue by ThibaultLacharme** [arose/nglview#886]
While trying to display a SDF file using nglview, I ran into this error when using show_file:
**uncaught exception: error loading file: 'Not Found'**

![jupyter_lab_error](https://user-images.githubusercontent.com/44061738/77637447-fe71de00-6f55-11ea-9a5c-0b636beaf7cb.png)

![js_console_error](https://user-images.githubusercontent.com/44061738/77637492-0cbffa00-6f56-11ea-8bc7-f55a719e7db1.png)

Yet there is no such issue when running the same command in jupyter notebook

![jupyter_notebook](https://user-images.githubusercontent.com/44061738/77637534-1a757f80-6f56-11ea-99b7-8271291c6ce4.png)

I didn't see anyone having the same problem recently, I can show you my dependencies if necessary.

I can't say if it's a problem on jupyterlab itself, didn't see any similar issue with that particular error when looking up for it and in case you ran into this problem before I wanted to see with you first.

Thank you

**Comment by hainm** [comment]
hi @ThibaultLacharme 
This issue is not new and I thought it was already fixed, I guess jupyterlab changes its behaviour again. Please follow this topic to see if you can have a workaround: https://github.com/arose/nglview/issues/783

cheers

**Comment by ThibaultLacharme** [comment]
Thanks, I'll check it out! 

I saw that jupyterlab gave you some trouble from version to version, I hope I can find a workaround, else I'll go back to the notebook I guess if it's too cumbersome.

**Comment by ThibaultLacharme** [comment]
Quick question though as I don't usually modify the source code of the libraries I'm using. 

In order to modify nglview's source code,  do I need to set up my conda environment in develop mode to be able to access the code in JS and modify the _get_loadFile_promise function ?

**Comment by ThibaultLacharme** [comment]
Seems like it works when using show_structure_file instead of show_file, as I don't have a huge background in computer science I can't really say where's the difference. I'll check some documentation for my personal knowledge and will go with that in the meantime, thanks!
