### ISSUE TITLE
Is it possible to call three.js commands in nglview ?

### ISSUE THREAD

**Issue by dou-du** [arose/nglview#890]
As I know, the nglview is using the three.js library. I am wondering that
is it possible to call three.js commands from nglview. As my previous posted
issue, I want to draw a plane with nglview. If it is possible to call three.js 
commands, I can easily draw the plane. Could you give some suggestions ? 
Thanks.

**Comment by hainm** [comment]
cc @arose

**Comment by arose** [comment]
not supported, but re the plane: while there is no addPlane method in the shape class there is a generic addMesh (https://github.com/arose/ngl/blob/master/src/geometry/shape.ts#L124-L148)

**Comment by dou-du** [comment]
Thanks a lot. The addPlane works fine to create the plane.
