### ISSUE TITLE
How to set colors of atoms by index ?

### ISSUE THREAD

**Issue by gVallverdu** [arose/nglview#892]
Hello

I have a molecule that I load from a PDB file and I would like to set the color of atoms from their index.

Thank you for your help

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.1
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```

**Comment by hainm** [comment]
may be
```view.add_licorice(color='atomindex')```? 

Or do you want customized colors?

**Comment by gVallverdu** [comment]
I did this but it does not work

```py
view = nv.show_file("D3-2.pdb")
view.add_representation('licorice', selection=idx_C1, color='red')
view.add_representation('licorice', selection=idx_C2, color='blue')
view.add_representation('licorice', selection=idx_C2, color='green')
view
```

where `idx_Ci` are numpy array. I tried list but it does not work.

And yes, what I would like to do is to be able to give the color according to a give quantity (charge, spin ...)

Thanks

**Comment by hainm** [comment]
I am not sure about your system. It works fine like below:

<img width="1098" alt="Screen Shot 2020-04-01 at 5 02 52 PM" src="https://user-images.githubusercontent.com/4451957/78186401-ad248b80-743a-11ea-8dc1-3f43ebada718.png">

**Comment by hainm** [comment]
@gVallverdu  I can reproduce your issue with your code + file.

**Comment by gVallverdu** [comment]
I also reproduce your code and it works.
I created the pdb file by hands from an xyz file. Maybe I miss something ?

**Comment by hainm** [comment]
ah, you did not clear the default representation (for some reasons), this default color overlaps with your new ones.

<img width="1038" alt="Screen Shot 2020-04-01 at 5 11 51 PM" src="https://user-images.githubusercontent.com/4451957/78187136-e6113000-743b-11ea-983d-f251e5db6a41.png">

Try this:
```
import nglview as nv
import numpy as np

idx_C1 = np.array([  0,   1,   2,   5,   6,   7,   8,   9,  11,  13,  14,  23,  24,
    28,  37,  38,  39,  40,  45,  46,  47,  50,  51,  52,  53,  54,
    56,  58,  59,  68,  69,  73,  83,  84,  85,  86,  91,  92,  93,
    96,  97,  98,  99, 100, 102, 104, 105, 114, 115, 119, 129, 130,
    131, 132])
idx_C2 = np.array([  3,   4,  12,  15,  22,  27,  33,  34,  48,  49,  57,  60,  67,
    72,  79,  80,  94,  95, 103, 106, 113, 118, 125, 126])
idx_C3 = np.array([ 10,  29,  32,  55,  74,  77,  78, 101, 120, 123, 124, 137])

view = nv.show_file("D3-2.pdb", default=False)
view.center()
view.add_representation('line', selection=idx_C1, color='red')
view.add_representation('line', selection=idx_C2, color='blue')
view.add_representation('line', selection=idx_C3, color='green')
view
```

**Comment by gVallverdu** [comment]
Ok, it works, but it is quite strange. Sometimes I have to execute the cell several times to get the widget to render the view.

![image](https://user-images.githubusercontent.com/5417018/78187876-87fe4000-746f-11ea-9375-255191f58ee1.png)
 
Here is the code I used:
```py
import nglview as nv
import numpy as np

idx_C1 = np.array([  0,   1,   2,   5,   6,   7,   8,   9,  11,  13,  14,  23,  24,
    28,  37,  38,  39,  40,  45,  46,  47,  50,  51,  52,  53,  54,
    56,  58,  59,  68,  69,  73,  83,  84,  85,  86,  91,  92,  93,
    96,  97,  98,  99, 100, 102, 104, 105, 114, 115, 119, 129, 130,
    131, 132])
idx_C2 = np.array([  3,   4,  12,  15,  22,  27,  33,  34,  48,  49,  57,  60,  67,
    72,  79,  80,  94,  95, 103, 106, 113, 118, 125, 126])
idx_C3 = np.array([ 10,  29,  32,  55,  74,  77,  78, 101, 120, 123, 124, 137])

view = nv.show_file("Angewandte/diastereomer_D3-2.pdb", default=False)
view.center()
view.add_representation("ball+stick")
view.add_representation('ball+stick', selection=idx_C1, color='red')
view.add_representation('ball+stick', selection=idx_C2, color='blue')
view.add_representation('ball+stick', selection=idx_C3, color='green')

view
```
---

Going back to the beginning of the question, what I would like to do now is to give a color to each atom according to an atomic quantity (charge, spin ...). I can make a loop on this `add_representation` function and set the color but this is not really clean. Does it exist a kind of mapping function ?

If not, I could try something and maybe try to contribute ...

**Comment by hainm** [comment]
> Ok, it works, but it is quite strange. Sometimes I have to execute the cell several times to get the widget to render the view.

yeah, it might be related to the bug fixed in master branch: https://github.com/arose/nglview/pull/882

**Comment by hainm** [comment]
> Going back to the beginning of the question, what I would like to do now is to give a color to each atom according to an atomic quantity (charge, spin ...). I can make a loop on this add_representation function and set the color but this is not really clean. Does it exist a kind of mapping function ?

Try to use `ColormakerRegistry` to see if that helps: https://github.com/arose/nglview/pull/839

**Comment by gVallverdu** [comment]
Where can I find the `**kwargs` of a function such as `add_ball_and_stick` for example ? Or the available options ?

**Comment by hainm** [comment]
it's `NGL`'s parameters.

http://nglviewer.org/ngl/api/manual/molecular-representations.html#ball-stick
(`nglview` convert camel to snake).
