### ISSUE TITLE
Interplay with ASE

### ISSUE THREAD

**Issue by hoba87** [arose/nglview#893]
There is a problem with the file handling between ASE and nglview on Windows. It happens already for the simple example:
```
import nglview
from ase import Atoms
atoms = Atoms('N2', positions=[[0, 0, -1], [0, 1, 1]])
nglview.show_ase(atoms)
```
See https://gitlab.com/ase/ase/-/issues/574 also. It is related to temporary file, which is opened twice, which is not allowed on Windows. An ASE developer proposed to use a temporary file path in nglview.

**Comment by hainm** [comment]
You can upgrade to the latest version, fixed here: https://github.com/arose/nglview/blob/e181b16a762eeabc8d6f2964d55a1986af7657bc/nglview/adaptor.py#L45-L61

**Comment by hoba87** [comment]
Ok, thanks
