### ISSUE TITLE
auto enable extension on installation for notebook >= 5.3

### ISSUE THREAD

**Issue by ericpre** [arose/nglview#896]
Unlike ipywidgets, nglview doesn't auto enable notebook extension when installing with conda. It seems that this is not clearly documented, but below are a couple of examples:
- https://github.com/jupyter-widgets/ipywidgets/pull/1911
- https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/9/files
- https://github.com/vega/ipyvega/pull/72
- https://github.com/maartenbreddels/ipyvolume/commit/415f0fb904b65a18cabb6939dc6a586c820ec797

[PR in notebook repository](https://github.com/jupyter/notebook/pull/3116/) for implementation details.

**Comment by hainm** [comment]
thanks for your suggestion. I thought `nglview` already have auto-activated stuff.

cc @marscher here (from your comment(s): https://github.com/conda-forge/nglview-feedstock/pull/26/files#r269034275)

**Comment by hainm** [comment]
I've tried and I think `nglview` works as expected.

```
conda create -n test-nglview python=3.8 -y
source  activate test-nglview
conda install nglview -c conda-forge -y
```

And that's it.

**Comment by ericpre** [comment]
This is what I have checked before opening this issue and trying again still does not work. Only running `jupyter-nbextension enable nglview --py --sys-prefix` make the nglview works in the notebook. I can reproduce this behaviour on windows and linux.

Do you have the following output being displayed when you run `conda install nglview -c conda-forge`? 
```
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK
```
In my case, I don't have this output but I have one for the `jupyter-js-widgets/extension` (`ipywidgets`)

Below is the output of `jupyter nbextension list` after installing in a new environment
```
>>> jupyter nbextension list
Known nbextensions:
  config dir: /opt/miniconda3/envs/test-nglview/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

To be compare with after enabling the nglview nbextension.
```
>>> jupyter-nbextension enable nglview --py --sys-prefix
Enabling notebook extension nglview-js-widgets/extension...
      - Validating: OK

>>> jupyter nbextension list
Known nbextensions:
  config dir: /opt/miniconda3/envs/test-nglview/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nglview-js-widgets/extension  enabled 
      - Validating: OK

```

**Comment by ericpre** [comment]
> cc @marscher here (from your comment(s): https://github.com/conda-forge/nglview-feedstock/pull/26/files#r269034275)

I am not familiar with how extensions works and their enabling mechanism but this doesn't follow the "standard" pattern mentioned in the fist post of this issue  (https://github.com/arose/nglview/issues/896#issue-611417553).
The conda recipes mentioned above don't do anything (no post-link script) for enabling the nbextensions but it seems that the installation of the package is configured to enable them when there are installed.

**Comment by hainm** [comment]
> Do you have the following output being displayed when you run conda install nglview -c conda-forge?

No I did not see it.

> I can reproduce this behaviour on windows and linux.

I see. So it's platform issue. I was using my mac. 
By the way, I will make a PR to fix (or review a PR from you if you would like to make one). Cheers.

**Comment by ericpre** [comment]
Sorry, I don't know anything about javascript (and its packaging) to make a PR. If not, I would already have done so!

**Comment by hainm** [comment]
@ericpre addressed in #898. Thanks.

**Comment by ericpre** [comment]
I built a conda package using the master branch (with #898 included) to check and enabling the extension automatically works perfectly! `pip` installation works perfectly too.

Thanks @hainm!
Any idea when the next release could be?

**Comment by hainm** [comment]
I am not sure since there are only commits from the latest release https://github.com/arose/nglview/releases

**Comment by ericpre** [comment]
Fair enough! I will keep a eye on the feedstock on conda-forge - for the next release, it may be worth cleaning up the recipe.
