### ISSUE TITLE
Possible to contribute the docs of the nglview

### ISSUE THREAD

**Issue by dou-du** [arose/nglview#897]
Dear developers,

Our group are using the Nglview to develop applications for computational material science. We are starting to write a tutorial about the usage of the Nglview. Particularly, we focus on the visualization of the solid state systems. Here is the link:

https://osscar-docs.readthedocs.io/en/latest/examples/index.html

We will continue to update the docs. We are wondering that is it possible to merge our docs into the Nglview docs, which could be beneficial for more people. Thanks.

**Comment by hainm** [comment]
hi @dou-du: Absolutely and fantastic. Please make a PR when it's ready. Thanks.
