### ISSUE TITLE
nglview in AT

### ISSUE THREAD

**Issue by hainm** [arose/nglview#899]
https://github.com/ParmEd/ParmEd/issues/1088#issue-619641837

**Comment by hainm** [comment]
@calgator1317: 

have you tried `amber.conda install -c conda-forge nglview` yet? your message says there is no module named `nglview`.

**Comment by calgator1317** [comment]
> have you tried `amber.conda install -c conda-forge nglview` yet?

Yes It was the first thing I tried following your suggest in Amber list email response but still no hope.

I just tried these tips to delete/uninstall and reinstall nglview. here is the output (https://github.com/SBRG/ssbio/wiki/Troubleshooting#nglviewer-fresh-install-tips)

`amber.conda install -c conda-forge ipywidgets`
Output:
The following NEW packages will be INSTALLED:

  ipywidgets         conda-forge/noarch::ipywidgets-7.5.1-py_0
  pip                conda-forge/noarch::pip-20.1-pyh9f0ad1d_0
  python_abi         conda-forge/osx-64::python_abi-3.7-1_cp37m
  widgetsnbextension conda-forge/osx-64::widgetsnbextension-3.5.1-py37_0

Then `amber.pip install nglview`
→ Successfully built nglview
Installing collected packages: nglview
Successfully installed nglview-2.7.5

`amber.jupyter nbextension list`
<img width="758" alt="Screen Shot 2020-05-18 at 3 32 47 PM" src="https://user-images.githubusercontent.com/44783102/82252355-dd59b800-991c-11ea-8337-ca907def231c.png">

To make sure extension is enable, 
`amber.jupyter nbextension enable --py --sys-prefix widgetsnbextension`
<img width="342" alt="Screen Shot 2020-05-18 at 3 35 10 PM" src="https://user-images.githubusercontent.com/44783102/82252669-6d97fd00-991d-11ea-9d27-7c9ba317e4c3.png">

` amber.jupyter nbextension enable nglview --py --sys-prefix`
<img width="675" alt="Screen Shot 2020-05-18 at 3 35 33 PM" src="https://user-images.githubusercontent.com/44783102/82252680-712b8400-991d-11ea-9ace-d70a466b425a.png">

Is there any alternative code for this  `kill $(pgrep jupyter)` to restart jupyter notebook. I tried so many but none has worked

**Comment by hainm** [comment]
what happens if

- From terminal: `amber.jupyter notebook` (to use the jupyter in amber20/miniconda/bin/)
- add some commands to the notebook, below:
```
import nglview as nv

nv.demo()
```

**Comment by calgator1317** [comment]
![Screen Shot 2020-05-18 at 4 14 02 PM](https://user-images.githubusercontent.com/44783102/82255524-c74ef600-9922-11ea-931f-0a9547f21987.png)

If nglview module is detected it would show as in blue text right?

**Comment by calgator1317** [comment]
same result for chrome and safari in case it matters

**Comment by hainm** [comment]
what's the output of below?
```
import sys
print(sys.prefix)
```

**Comment by calgator1317** [comment]
/Applications/amber20_src/build/CMakeFiles/miniconda/install

**Comment by hainm** [comment]
uhm, I think it's a wrong path. Your `python` should be in `/Application/amber20/miniconda/bin/`
(amber switches to use `cmake` in AT20).

Ok, so scratch what you tried, can you please follow below:

- `/Application/amber20/miniconda/bin/python -c 'import nglview; print(nglview)'`
- If above step is ok, follow:
 `/Application/amber20/miniconda/bin/jupyter notebook`
- try `nglview` again in the notebook.

**Comment by calgator1317** [comment]
`/Applications/amber20/miniconda/bin/python -c 'import nglview; print(nglview)'`
→ <module 'nglview' from '/Applications/amber20/miniconda/lib/python3.7/site-packages/nglview/__init__.py'>

In terminal, open jupyter-notebook from `/Applications/amber20/miniconda/bin/jupyter-notebook
`
```
import nglview as nv
nv.demo()
```

Still no

I noticed that, when I run amber.jupyter, it comes from `/Applications/amber20/bin`
(NOT `/Applications/amber20/miniconda/bin/`)

`/Applications/amber20/miniconda/bin/jupyter-nbextension list` shows that widgets/extension are enable
```
config dir: /Applications/amber20//miniconda/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      nglview-js-widgets/extension  enabled
      - Validating: OK
```
Still no

**Comment by hainm** [comment]
> /Applications/amber20/miniconda/bin/python -c 'import nglview; print(nglview)'
→ <module 'nglview' from '/Applications/amber20/miniconda/lib/python3.7/site-packages/nglview/init.py'>

This means that `nglview` is already installed in your path. 

> Still no

What do you mean? still no module `nglview`? for some reasons, your notebook picked the wrong kernel (wrong python path in this case). Can you please try to change the kernel here?

<img width="1187" alt="Screen Shot 2020-05-18 at 6 10 21 PM" src="https://user-images.githubusercontent.com/4451957/82264428-e5bced80-9932-11ea-8489-fa6d6f77519e.png">

**Comment by hainm** [comment]
Related issue: https://github.com/jupyter/notebook/issues/2563

**Comment by calgator1317** [comment]
> What do you mean? still no module `nglview`?

yes, sorry for the confusion. I still don't have nglview after. I already tried changing kernel to python3 as well (python2 does not appear here)

> Related issue: [jupyter/notebook#2563](https://github.com/jupyter/notebook/issues/2563)

Seems like many people successfully had it resolved by
`python3 -m ipykernel install --user`
I typed `amber.python -m ipykernel install --user`
→ Installed kernelspec python3 in /Users/LocHuynh/Library/Jupyter/kernels/python3

**Comment by calgator1317** [comment]
Should /kernels/python3 located inside $Applications/amber20/miniconda/bin or somewhere inside the amber20 directory?

**Comment by hainm** [comment]
oh so we need to manually update the python path.

Open the ` /Users/LocHuynh/Library/Jupyter/kernels/python3/kernel.json`
and change the python path to `/Applications/amber20/miniconda/bin/python3`

**Comment by calgator1317** [comment]
FINALLY!!!!! Thank you @hainm. You should you totally add this instruction to your tips. Awesome!

**Comment by hainm** [comment]
Enjoy and cheers.
