### ISSUE TITLE
Show two trajectories? 

### ISSUE THREAD

**Issue by hainm** [arose/nglview#9]
Any idea how I can do this? Thx.

**Comment by arose** [comment]
do you mean in the same widget? Using the same topology?

**Comment by hainm** [comment]
Yes. Same widget but not necessary same topology.

**Comment by arose** [comment]
Currently the widget can only handle one topology and one trajectory. The NGL Viewer itself can handle more but that is not implemented on the Python side. Shortly: There needs to be some sort of Python equivalent to the `stage` and the structure/representation `component` objects on the JS side.

**Comment by hainm** [comment]
ok. I will look into stage.

**Comment by hainm** [comment]
proposed syntax in python

```python
stage = nv.Stage(...)
view0 = nv.show_pytraj(...)
view1 = nv.show_pytraj(...)
stage.add(view0)
stage.add(view1)
```

**Comment by hainm** [comment]
done
