### ISSUE TITLE
nglview.show_openbabel() failed when using Open Babel >= 3.0.0

### ISSUE THREAD

**Issue by radifar** [arose/nglview#903]
- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.5
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```

- Problem report
I am using Open Babel 3.1.1, and it got error when I use nglview.show_openbabel(). It was caused by the deprecated import method. In Open Babel >3 it should be from openbabel import openbabel. 

- Solution
Therefore I modify OpenbabelStructure Class in `anaconda3/envs/teachopencadd/lib/python3.6/site-packages/nglview/adaptor.py`. changing line 174:
```
import openbabel
```
to
```
from openbabel import openbabel
```
And it works perfectly

**Comment by hainm** [comment]
thanks @radifar, should be updated in #904
