### ISSUE TITLE
import nglview prints "_ColormakerRegistry"?

### ISSUE THREAD

**Issue by jennyfothergill** [arose/nglview#905]
Code to see issue:
```python
import nglview
```
output is `_ColormakerRegistry`

Doesn't break anything, but it is unnecessary in my use case. (And adds clutter to some notebook examples.) Could this be a parameter which could be queried as needed?
Thank you for making this great visualization tool!

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
```
nglview 2.7.5
ipywidgets 7.5.1

**Comment by hainm** [comment]
hi @jennyfothergill , 
this issue is bugging me too but I don't know how to resolve it. I will keep in mind about that.
I can post the detail of "why" if you're interested in the technical issue. Cheers.

**Comment by hainm** [comment]
fixed in #906 

Let me know if  the latest `v2.7.7` has any issue. Cheers.

**Comment by jennyfothergill** [comment]
Wow, that was fast! Thank you very much!

**Comment by hainm** [comment]
yeah, thanks for "pushing" this so I can accelerate the process.
