### ISSUE TITLE
Binder example doesn't work

### ISSUE THREAD

**Issue by wfs-lilly** [arose/nglview#908]
I've been entirely unable to get nglview to work in Jupyter lab, so I tried the Binder version to get some hints.  It's broken also:  this is a screen cap of an attempt to execute the first cell in the "export_image.ipynb" notebook.  It shows the same problem I have -- the widget is not shown, just listed as the cell's output.

![image](https://user-images.githubusercontent.com/57267110/85474931-2d561b00-b56a-11ea-9206-71c46f2f0b6f.png)

**Comment by hainm** [comment]
hi @wfs-lilly, yeah, the binder for `nglview` is super outdated. 

Please try `pyiron'` binder that includes `nglview` (I've give it a try).

(Just create a new notebook and copy and paste the commands). 

https://mybinder.org/v2/gh/pyiron/pyiron/master

<img width="1025" alt="Screen Shot 2020-06-23 at 9 58 32 PM" src="https://user-images.githubusercontent.com/4451957/85488681-bab26300-b59c-11ea-898c-0b93341cc780.png">

**Comment by hainm** [comment]
@wfs-lilly I've updated a sample script to for the latest `jupyterlab` and `nglview` in `conda-forge` channel

https://github.com/arose/nglview/blob/master/devtools/nglview-jupyterlab.sh

Please give it a try.

**Comment by wfs-lilly** [comment]
Hi @hainm -- thanks for the reply and the help!  I will try to create a new environment with your script later today or tomorrow.
I was also able to do as you demonstrated in the `pyiron` binder using the class Notebook interface.  However, when I tried to do the same thing with the Lab interface I got a failure similar to ones I see on my own installations.   I've attached a screencap, showing that the extension is installed and enabled, what I see in the notebook and a bit of the Javascript console.  Should I give up on the Lab version for the time being?
![image](https://user-images.githubusercontent.com/57267110/85633946-2fce7880-b62f-11ea-8a6e-b008550617c3.png)

**Comment by wfs-lilly** [comment]
Oops

**Comment by hainm** [comment]
> Should I give up on the Lab version for the time being?

please try my script first. I already tested and seems ok.

**Comment by hainm** [comment]
I've updated the build for `nglview`'s binder. Please try again: https://mybinder.org/v2/gh/hainm/nglview-binder/master?urlpath=lab/tree/nglview/notebooks

<img width="1057" alt="Screen Shot 2020-06-24 at 8 45 29 PM" src="https://user-images.githubusercontent.com/4451957/85641141-b6994a80-b65b-11ea-8f93-0781bbbd1c34.png">

**Comment by wfs-lilly** [comment]
@hainm -- thanks for the updates.  I am able to get the demo working in binder.  Will try to create my own environment with your script today or tomorrow!

**Comment by wfs-lilly** [comment]
@hainm I was able to create a Jupyter environment which works using your script!  I decided to try first on Windows, my local machine, which is usually the hardest.  I ran into 1 install issue:  I had to install nodejs also because I got an error on the 

`jupyter-labextension install @jupyter-widgets/jupyterlab-manager`

step.  During the nodejs install I had to specify the conda-forge channel to get a good nodejs -- I got an old version with install problems.

I fired up Jupyter lab from the environment I had just built and things worked!

I did run into problems, however, when I tried to add that new environment as a kernel within Jupyter lab -- should I open a separate issue for that?

Thanks for all of the help!  May I suggest an update to the install docs?  I made lots of attempts and probably would never have gotten a working system without your help.

**Comment by hainm** [comment]
hi @wfs-lilly feel free to make a PR to update this instruction: https://github.com/arose/nglview#released-version

And/Or may be update the FAQ too: https://github.com/arose/nglview/blob/master/docs/FAQ.md


> I did run into problems, however, when I tried to add that new environment as a kernel within Jupyter lab -- should I open a separate issue for that?

which issue? :D

**Comment by wfs-lilly** [comment]
@hainm Thanks again.  I'm off for the next week, but will prepare a PR when I return.

The "issue" is that the kernel crashes, is restarted, crashes, ..., until it reaches the autorestart limit if I explicitly choose the nglview-enabled kernel.  If I launch Jupyter lab from that conda environment and then create a notebook with the default kernel all is good.  I'll investigate further and open a new issue after I get back.
