### ISSUE TITLE
release v0.5 todo

### ISSUE THREAD

**Issue by hainm** [arose/nglview#95]
- [autorun some basic notebooks](https://github.com/arose/nglview/wiki/Developer-guide)

- need to update new NGL features

- move LOG to different file

- probably update GIF to README (with new NGL version): its render is very pretty.

- add versions requirement in `setup.py`

**Comment by hainm** [comment]
My working versions

```python
In [6]: import notebook, ipywidgets, traitlets

In [7]: notebook.__version__
Out[7]: '4.2.0'

In [8]: ipywidgets.__version__
Out[8]: '4.1.1'

In [9]: traitlets.__version__
Out[9]: '4.2.1'
```

**Comment by hainm** [comment]
@arose  at some point, we should have a release soon. 

PS: AMBER16 is just released and I need to update nglview version in this tutorial too
http://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_notebook/

**Comment by arose** [comment]
I created a milestone to help us focusing https://github.com/arose/nglview/milestones/0.5

**Comment by hainm** [comment]
@arose: I just update wiki how to test notebook automatically. Work fine with my mac.

check it out: https://github.com/arose/nglview/wiki/Developer-guide

**Comment by hainm** [comment]
Uhm, nglview repo is now too heavy (>100 MB) to suggest to install via `pip install git+https...`
